powdr-labs/powdr

- src/analyzer/mod.rs
- src/bin/compiler.rs
- src/json_exporter/mod.rs
- src/parser/ast.rs
- src/parser/mod.rs
- src/parser/pil.lalrpop
Fixes https://github.com/chriseth/powdr/issues/8 
Fixes https://github.com/chriseth/powdr/issues/6
Fixes https://github.com/chriseth/powdr/issues/7
> More export features

- src/json_exporter/mod.rs
Fixes https://github.com/chriseth/powdr/issues/11
> Ignore specific values for idq in tests.

- src/analyzer/mod.rs
- src/analyzer/pil_analyzer.rs
- src/asm_compiler/mod.rs
- src/bin/compiler.rs
- src/commit_evaluator/mod.rs
- src/compiler.rs
- src/constant_evaluator/mod.rs
- src/parser/ast.rs
- src/parser/display.rs
- src/parser/mod.rs
- src/parser/powdr.lalrpop
- tests/integration.rs
- tests/sum_via_witness_query.pil
Part of https://github.com/chriseth/powdr/issues/51
> Witness hints

- src/commit_evaluator/mod.rs
- tests/sum_via_witness_query.pil
Fixes https://github.com/chriseth/powdr/issues/55
> Evaluate directly on next row if needed.

- src/commit_evaluator/mod.rs
- tests/integration.rs
- tests/witness_lookup.pil
Implements a first version of https://github.com/chriseth/powdr/issues/49
> Support lookups in witness computation.

- src/asm_compiler/mod.rs
- src/commit_evaluator/affine_expression.rs
- src/commit_evaluator/mod.rs
- tests/integration.rs
Fixes https://github.com/chriseth/powdr/issues/51
Fixes https://github.com/chriseth/powdr/issues/50
> Finite field hacky

- src/commit_evaluator/evaluator.rs
- src/commit_evaluator/machine.rs
- src/commit_evaluator/machine_extractor.rs
- src/commit_evaluator/mod.rs
- src/compiler.rs
- tests/integration.rs
- tests/palindrome.asm
What is missing:
- Do it non-hacky (will be done later)
> Machine extractor and executor

- src/asm_compiler/mod.rs
- src/commit_evaluator/double_sorted_witness_machine.rs
- src/commit_evaluator/evaluator.rs
- src/commit_evaluator/fixed_lookup_machine.rs
- src/commit_evaluator/machine.rs
- src/commit_evaluator/machine_extractor.rs
- src/commit_evaluator/mod.rs
- src/commit_evaluator/sorted_witness_machine.rs
- src/parser/asm_ast.rs
- src/parser/powdr.lalrpop
- tests/integration.rs
- tests/mem_read_write.asm
Implements #71 
(at least in a non-generic way)
> Read-write memory.

- src/analyzer/pil_analyzer.rs
- src/asm_compiler/mod.rs
- src/constant_evaluator/mod.rs
- src/parser/ast.rs
- src/parser/display.rs
- src/parser/powdr.lalrpop
- src/riscv/compiler.rs
- tests/asm.rs
- tests/asm_data/full_pil_constant.asm
- tests/asm_data/mem_read_write.asm
- tests/asm_data/palindrome.asm
- tests/common/mod.rs
- tests/pil_data/global.pil
- tests/pil_data/sum_via_witness_query.pil
addresses #114 
- concat `A + B`
- repeat `A*`
Todo:
> Complex array literal expressions

- src/lib.rs
- src/number.rs
- src/witness_generator/affine_expression.rs
- src/witness_generator/bit_constraints.rs
extracted from https://github.com/chriseth/powdr/pull/102
> make field more flexible

- src/witness_generator/machines/machine_extractor.rs
Fixes https://github.com/chriseth/powdr/issues/137
> Split out multiple machines.

- src/witness_generator/bit_constraints.rs
- src/witness_generator/machines/block_machine.rs
- src/witness_generator/machines/machine_extractor.rs
- src/witness_generator/machines/mod.rs
- src/witness_generator/mod.rs
- tests/pil.rs
- tests/pil_data/block_lookup_or.pil
Implements most of #116 and even some part of https://github.com/chriseth/powdr/issues/133
> Block machines.

- src/witness_generator/machines/fixed_lookup_machine.rs
- Look at output columns when building indices
- Only keep the first matching row
> Application indices

- src/asm_compiler/mod.rs
- src/parser/asm_ast.rs
- src/parser/powdr.lalrpop
- src/riscv/compiler.rs
- tests/asm_data/bit_access.asm
- tests/asm_data/functional_instructions.asm
- tests/asm_data/mem_read_write.asm
- tests/asm_data/multi_assign.asm
- tests/asm_data/palindrome.asm
- tests/asm_data/simple_sum.asm
> Functional instruction declaration syntax

- executor/src/analyzer/pil_analyzer.rs
- executor/src/constant_evaluator/mod.rs
- number/src/lib.rs
- parser/src/ast.rs
- parser/src/display.rs
- parser/src/powdr.lalrpop
- riscv/src/compiler.rs
- test_data/pil/fib_macro.pil
- test_data/pil/fibonacci.pil
- test_data/pil/global.pil
- test_data/pil/sum_via_witness_query.pil
Allow expressions on lhs of match arms
> Replace 0/0 hack with match

- compiler/src/lib.rs
- compiler/src/verify.rs
- executor/src/analyzer/pil_analyzer.rs
- executor/src/witgen/generator.rs
- pilgen/src/lib.rs
Fixes https://github.com/chriseth/powdr/issues/163
> Use match for prover query.

- executor/src/constant_evaluator/mod.rs
- pil_analyzer/src/lib.rs
- pil_analyzer/src/pil_analyzer.rs
Fixes https://github.com/chriseth/powdr/issues/201
> Do not unroll array repetitions during analysis.

- .github/workflows/rust.yml
- compiler/src/lib.rs
- compiler/src/verify.rs
- riscv/tests/riscv.rs
> Run ignored tests in release mode. 

- README.md
> docs: update readme example path

- executor/src/witgen/generator.rs
- executor/src/witgen/machines/fixed_lookup_machine.rs
- executor/src/witgen/util.rs
- pil_analyzer/src/lib.rs
> Make some use of poly ids.

- executor/src/witgen/machines/machine_extractor.rs
- executor/src/witgen/machines/sorted_witness_machine.rs
Now the extraction is hopefully deterministic, solving issue #199.
> Sorting in the places where HashSet order influences the result of machine extraction

- riscv/src/lib.rs
> Revert "Print cargo error output."

- pilgen/src/lib.rs
Fixes https://github.com/chriseth/powdr/issues/262
> Fix the case where a variable is used multiple times in an expression.

- riscv/tests/riscv.rs
- riscv/tests/riscv_data/password_checker/Cargo.toml
- riscv/tests/riscv_data/password_checker/src/lib.rs
We need to check why the loop is not detected for this example.
> add password checker example from risc0

- compiler/src/lib.rs
- riscv/runtime/src/print.rs
- riscv/src/compiler.rs
Now this needs the srai instruction.
> Debug out with MaybeUninit.

- riscv/runtime/Cargo.toml
- riscv/runtime/rust-toolchain.toml
- riscv/runtime/src/allocator.rs
- riscv/runtime/src/lib.rs
- riscv/src/compiler.rs
- riscv/src/lib.rs
- riscv/src/reachability.rs
- riscv/tests/riscv.rs
- riscv/tests/riscv_data/memfuncs/src/lib.rs
- riscv/tests/riscv_data/vec_median/Cargo.toml
- riscv/tests/riscv_data/vec_median/rust-toolchain.toml
- riscv/tests/riscv_data/vec_median/src/lib.rs
> Enabling global allocator

- pil_analyzer/src/pil_analyzer.rs
This is a refactoring that changes pil_analyzer to process the ast by value instead of by reference.
> Use direct values in pil analyzer.

- compiler/tests/pil.rs
- parser/src/ast.rs
- parser/src/display.rs
- parser/src/lib.rs
- parser/src/powdr.lalrpop
- pil_analyzer/Cargo.toml
- pil_analyzer/src/pil_analyzer.rs
- pilgen/src/lib.rs
- test_data/pil/simple_sum_asm.pil
> Allow assembly inside pil.

- compiler/src/lib.rs
- powdr_cli/src/main.rs
> Combine CLI for pil and asm compilation.

- number/src/goldilocks.rs
- number/src/macros.rs
- number/src/traits.rs
- pilgen/src/lib.rs
Fixes https://github.com/powdr-org/powdr/issues/307
> Allow literal numbers as instruction parameters.

- riscv/src/compiler.rs
> Move data init to the end

- compiler/tests/pil.rs
- parser/src/asm_ast.rs
- parser/src/ast.rs
- parser/src/lib.rs
- parser/src/macro_expansion.rs
- parser/src/powdr.lalrpop
- pil_analyzer/src/pil_analyzer.rs
- pilgen/src/lib.rs
- test_data/pil/simple_sum_asm_macro.pil
Fixes https://github.com/powdr-org/powdr/issues/309
> Add macros to assembly.

- parser/src/asm_ast.rs
- parser/src/display.rs
- pilgen/Cargo.toml
- pilgen/src/batcher.rs
- pilgen/src/lib.rs
- test_data/asm/batching/labels.asm
- test_data/asm/batching/labels_batched.asm
Split out of the now large batching PR
> Batch labels with the following statement

- compiler/src/lib.rs
- compiler/src/verify.rs
- compiler/tests/pil.rs
- executor/src/witgen/generator.rs
- test_data/pil/underdetermined_zero_no_solution.pil
Fixes #322
Depends on https://github.com/powdr-org/powdr/pull/325, otherwise ready
> Underdetermined constraints with zero not being a solution

- analysis/src/type_check.rs
- ast/src/analysis/display.rs
- ast/src/analysis/mod.rs
- ast/src/parsed/asm.rs
- ast/src/parsed/display.rs
- parser/src/powdr.lalrpop
- pilgen/src/lib.rs
- riscv/src/compiler.rs
- riscv/src/disambiguator.rs
- riscv/src/lib.rs
- riscv/src/reachability.rs
- riscv/src/riscv_asm.lalrpop
> Parse source references.

- backend/src/lib.rs
- halo2/Cargo.toml
- halo2/src/aggregation.rs
- halo2/src/lib.rs
- halo2/src/prover.rs
- powdr_cli/src/main.rs
This is based on the examples in https://github.com/privacy-scaling-explorations/snark-verifier/
> Halo2 aggregation

- powdr_cli/src/main.rs
Not sure if this should be merged, but I thought this is a convenient way to inspect the `commits.bin` and `constants.bin` files!
The command works similar to proving, e.g.:
```
cargo run pil test_data/asm/simple_sum.asm -i 6,3,1,2,3
cargo run export-csv simple_sum.pil
```
This will write a `columns.csv` which can be rendered easily using Excel or similar.
> Add Column CSV export

- Cargo.toml
- asm_to_pil/src/lib.rs
- ast/src/analyzed/build.rs
- ast/src/analyzed/mod.rs
- ast/src/parsed/build.rs
- ast/src/parsed/mod.rs
- compiler/Cargo.toml
- compiler/src/lib.rs
- executor/src/witgen/mod.rs
- halo2/src/circuit_data.rs
- pilopt/Cargo.toml
- pilopt/src/lib.rs
- powdr_cli/Cargo.toml
- powdr_cli/src/main.rs
- test_data/asm/full_pil_constant.asm
- test_data/pil/underdetermined_zero_no_solution.pil
> Remove constant fixed columns

- compiler/tests/pil.rs
- executor/src/witgen/machines/block_machine.rs
- test_data/pil/single_line_blocks.pil
- allow 1 as the block machine latch
- add test
> Support block machines with block size 1

- executor/src/witgen/affine_expression.rs
This is a bug, I came across while working on #412, and I'm pretty sure it also causes the failing test on #383.
**Background**: To implement integer division `divident // divisor`, we'd add a constraint that `divident = quotient * divisor + remainder`. Witness generation tries to detect this pattern and solves for `quotient` and `remainder` simultaneously, by performing the integer division.
However, this is only unique as long as `quotient * divisor + remainder` isn't overflowing. This PR checks for that and does nothing if there is a possible overflow.
The simplest example is: A constraint `x = y` can be rewritten as `0 = -y + x`, which fits this pattern for the integer division `0 // (-1)`, so previously witness generation would set `y = 0 // (-1) = 0` and `x = 0`, even though there …
> Fix falsely unique witness generation

- asm_to_pil/src/lib.rs
- ast/src/object/display.rs
- ast/src/object/mod.rs
- book/src/SUMMARY.md
- book/src/linker/README.md
- compiler/src/lib.rs
- compiler/src/verify.rs
- compiler/tests/asm.rs
- compiler/tests/pil.rs
- halo2/src/mock_prover.rs
- linker/src/lib.rs
- powdr_cli/src/main.rs
- riscv/src/lib.rs
Give the responsibility of handling machine degrees to the linker:
- degree defaults to 1024
- submachines must have a matching degree, or no degree
> Fallible linker

- compiler/src/util.rs
- number/src/macros.rs
- powdr_cli/src/main.rs
Load time for prove command is ridiculously slow, trying to improve it.
> improving prove command load time

- Cargo.toml
- airgen/Cargo.toml
- airgen/src/lib.rs
- analysis/src/lib.rs
- asm_to_pil/src/lib.rs
- ast/src/object/display.rs
- ast/src/object/mod.rs
- compiler/Cargo.toml
- compiler/src/lib.rs
- halo2/Cargo.toml
- halo2/src/mock_prover.rs
- linker/Cargo.toml
- linker/src/lib.rs
- powdr_cli/src/main.rs
I extracted the airgen extraction from #392
> Extract airgen

- airgen/src/lib.rs
Seems like this only showed up because I was using an old version of Clippy. Now I updated and it doesn't find it anymore.
Still, won't hurt to fix?
> Fix clippy

- .github/workflows/nightly-tests.yml
- .github/workflows/pr-tests.yml
- book/src/frontends/riscv.md
- powdr_cli/src/main.rs
- riscv/runtime/rust-toolchain.toml
- riscv/src/lib.rs
- riscv/tests/riscv_data/vec_median/rust-toolchain.toml
Don't yet have any atomic instruction implemented, as I am not sure what will be needed.
> Using the atomic variant of RISC-V.

- riscv/src/compiler.rs
hacky version for now, see https://github.com/powdr-labs/powdr/issues/548
> call every riscv submachine at least once

- .github/workflows/nightly-tests.yml
- .github/workflows/pr-tests.yml
- Cargo.toml
- executor/src/witgen/global_constraints.rs
- pilopt/src/lib.rs
- riscv/src/compiler.rs
- rust-toolchain.toml
- Updated Rust toolchain to 1.72 in `Cargo.toml`
- Added it to the Github workflows
- Re-ran `cargo fmt`
- This printed a warning that we should set the feature resolver. I set it to 2 ([see this post](https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html#cargos-new-feature-resolver))
> Use rust toolchain 1.72

- executor/Cargo.toml
- executor/src/witgen/generator.rs
- executor/src/witgen/identity_processor.rs
This now prints also how many identities have been processed per second and which percentage lead to progress. This is currently only 75%.
An extension could also do timing and identify the most expensive identity, but I think this is a good start for now.
> Statistics about identity processing.

- .github/workflows/pr-tests.yml
- executor/src/witgen/generator.rs
- executor/src/witgen/mod.rs
> Quick fix: Re-compute first row.

- halo2/src/prover.rs
$ cargo run --release prove ./test_chunk/simple_sum.pil -d ./test_chunk --field bn254 --backend halo2-chunk --params params.bin
Starting proof generation for chunks...
Generating app circuits and vks...
Generating compression circuit and vk...
Generating aggregation circuit and vk...
Generating proofs for chunks...
Generating compression proofs...
Generating aggregation circuits with proofs as witnesses...
Generating aggregation proof...
Verifying aggregated proof in the EVM...
[halo2/src/aggregation.rs:397] gas_cost = 599452
Proof of chunks => compression => aggregation done.
Wrote proof_chunk.bin.
> fix halo2 aggregation

- analysis/src/macro_expansion.rs
> Fix unused self in macro expansion

- test_data/pil/block_lookup_or.pil
> Fix typo in `block_lookup_or` comment

- executor/src/witgen/machines/block_machine.rs
- executor/src/witgen/sequence_iterator.rs
This gives me a 15% performance gain on Keccak
> BlockMachine: Remember if a query could not be completed

- compiler/src/lib.rs
- riscv/src/lib.rs
> Fixed missing endline.

- asm_utils/src/ast.rs
- riscv/src/compiler.rs
- riscv/src/riscv_asm.lalrpop
Extracted from https://github.com/powdr-labs/powdr/pull/553
> Make reg offset optional

- compiler/tests/asm.rs
- executor/src/witgen/mod.rs
- halo2/src/circuit_builder.rs
- pil_analyzer/src/pil_analyzer.rs
- test_data/asm/intermediate_nested.asm
This is done by inlining the intermediate polynomials at the beginning of witgen.
Todo:
> Implement witgen for intermediate polynomials

- .github/workflows/dead-links.yml
- .github/workflows/pr-tests.yml
Use the same jobs checking the PRs to gatekeep the merge queue.
> Enabling CI jobs for PRs as the merge queue conditional.

- .github/workflows/pr-tests.yml
- Cargo.toml
Should reduce the storage usage, because there is much less debug information generated.
> Using a custom cargo profile in the per PR tests.

- riscv/tests/riscv.rs
- riscv/tests/riscv_data/evm/Cargo.toml
- riscv/tests/riscv_data/evm/rust-toolchain.toml
- riscv/tests/riscv_data/evm/src/lib.rs
> Added revm test project.

- riscv/build.rs
- riscv/src/lib.rs
- riscv/src/riscv_asm.lalrpop
> Parsing .insn assembly directive.

- asm_utils/src/lib.rs
- asm_utils/src/reachability.rs
- riscv/src/compiler.rs
> Implementing fence and fence.i instructions.

- riscv/src/compiler.rs
> Multiplication returning both high and low bits.

- riscv/src/compiler.rs
- riscv/tests/instruction_tests/generated/mulhsu.S
- riscv/tests/instruction_tests/sources/mulhsu.S
~This can be improved a little if #648 is accepted.~
EDIT: Now uses #648.
> Complicated attempt of implementing mulhsu

- .circleci/config.yml
The biggest problem with this is that it still builds some stuff in the "test" jobs.
> Split circleci jobs.

- riscv/src/compiler.rs
This decreases the number of used rows in the trace by 15% in memory heavy cases (like my Merkle tree example).
The `addr` register can be fully removed once `mload` is also modified similarly.
> Add argument to mstore

- executor/src/witgen/machines/double_sorted_witness_machine.rs
- riscv/src/compiler.rs
> Implement mload with alignment correction built-in.

- executor/src/witgen/block_processor.rs
- executor/src/witgen/generator.rs
- executor/src/witgen/machines/block_machine.rs
- executor/src/witgen/mod.rs
> (1) Rename `Processor` -> `BlockProcessor`

- asm_utils/src/reachability.rs
- compiler/src/lib.rs
- halo2/src/mock_prover.rs
- pil_analyzer/src/pil_analyzer.rs
- powdr_cli/src/main.rs
- riscv/build.rs
- riscv/src/lib.rs
I know this is redundant, but my IDE still complains somehow...
> Explicitly allow printing to stdout.

- executor/src/witgen/mod.rs
This is needed when the query processor is refactored to use the generic evaluator. We might not need it anymore once we implement proper name resolution.
> Retain column access by name.

- analysis/src/macro_expansion.rs
- analysis/src/vm/inference.rs
- asm_to_pil/src/vm_to_constrained.rs
- ast/src/parsed/mod.rs
- parser/src/powdr.lalrpop
- pil_analyzer/src/evaluator.rs
- pil_analyzer/src/pil_analyzer.rs
> Allow namespaced names to be function-called.

- compiler/src/lib.rs
- executor/src/constant_evaluator/mod.rs
- executor/src/witgen/mod.rs
- executor/src/witgen/query_processor.rs
- executor/src/witgen/rows.rs
- halo2/src/mock_prover.rs
- pil_analyzer/src/condenser.rs
- pil_analyzer/src/evaluator.rs
- pil_analyzer/src/pil_analyzer.rs
Fixes https://github.com/powdr-labs/powdr/issues/673
Depends on #767
> Evaluate complex expressions including recursion and lambda functions

- analysis/src/macro_expansion.rs
- ast/src/analyzed/display.rs
- ast/src/analyzed/mod.rs
- ast/src/analyzed/visitor.rs
- ast/src/parsed/display.rs
- ast/src/parsed/mod.rs
- ast/src/parsed/visitor.rs
- executor/src/constant_evaluator/mod.rs
- executor/src/witgen/query_processor.rs
- parser/src/powdr.lalrpop
- pil_analyzer/src/evaluator.rs
- pil_analyzer/src/pil_analyzer.rs
- pilopt/src/lib.rs
> Replace Mapping enum alternative by Expression.

- pil_analyzer/src/condenser.rs
- pil_analyzer/src/evaluator.rs
- pil_analyzer/src/pil_analyzer.rs
> Allow function calls in condenser

- book/src/SUMMARY.md
- book/src/pil/declarations.md
- book/src/pil/expressions.md
Depends on https://github.com/powdr-labs/powdr/pull/773
> Document syntax a little.

- riscv/src/bootloader.rs
Starting the quest to make continuations sound (#814), this PR adds to the bootloader that memory pages are linearly hashed. I used a [Merkle–Damgård construction](https://en.wikipedia.org/wiki/Merkle%E2%80%93Damg%C3%A5rd_construction) with an initial value of 0. The underlying 512-bit-to-256-bit hash function is Poseidon with a capacity of 0.
The bootloader now contains this section:
```
// Store & hash 256 page words. This is an unrolled loop that for each each word:
// - Loads the word into the P{(i % 4) + 4} register
// - Stores the word at the address x3 + i * 4
// - If i % 4 == 3: Hashes registers P0-P11, storing the result in P0-P3
//
// At the end of the loop, we'll have a linear hash of the page in P0-P3, using a Merkle-Damgard
// construction. The initial P0-P3 values are 0, and …
```
> Bootloader: Hash pages

- executor/src/witgen/block_processor.rs
- executor/src/witgen/processor.rs
> Change `Processor::process_identity()` interface

- riscv/tests/riscv.rs
Depends on #832
Adds a test for continuations
> Add continuations test

- executor/src/witgen/vm_processor.rs
I find the logging for Rust examples (degree $2^{18}$) quite verbose.
With this PR, the Keccak example logs:
```
Detected machine: memory
Detected machine: block
Detected machine: block
Found loop with period 1 starting at row 18700
26214 of 262144 rows (9%) - 171 rows/s, 383k identities/s, 79% progress
52428 of 262144 rows (19%) - 1661 rows/s, 3397k identities/s, 100% progress
78642 of 262144 rows (29%) - 1694 rows/s, 3464k identities/s, 100% progress
104856 of 262144 rows (39%) - 1673 rows/s, 3421k identities/s, 100% progress
131070 of 262144 rows (49%) - 1682 rows/s, 3439k identities/s, 100% progress
157284 of 262144 rows (59%) - 1723 rows/s, 3524k identities/s, 100% progress
183498 of 262144 rows (69%) - 1701 rows/s, 3479k identities/s, 100% progress
209712 of 262144 rows (79%) - 1737 …
```
> VmProcessor: Reduce logging frequency

- riscv/Cargo.toml
- riscv/src/continuations.rs
- riscv/src/continuations/bootloader.rs
- riscv/src/lib.rs
Fixes #860
This would have prevented the errors fixed in https://github.com/powdr-labs/powdr_revm/pull/2
> Better error messages when using continuations

- powdr_cli/src/main.rs
- riscv/src/continuations.rs
- riscv/tests/riscv.rs
This is also just a hot fix needed for powdr_revm, we should find a proper solution using a new ser/de data format for both the Pipeline and this
> change the data type that continuations takes

- riscv/src/compiler.rs
Extracts the memory machine into a separate function in the RISC-V Compiler. Otherwise, there are no changes. This is to keep the diff in #893 smaller.
> RISC-V Compiler: Pull out memory

- riscv/src/continuations.rs
- riscv/src/continuations/bootloader.rs
Depends on #899 
This PR adds the claimed final register values to the bootloader inputs and exposes them as publics. They are currently ignored, but in the future, the shutdown routine can access them and assert that they are correct.
> Bootloader inputs: Add final register values

- riscv/src/continuations.rs
- riscv_executor/src/lib.rs
This saves a tiny bit of time when running continuations (from 18.7s to 18.1s on `many_chunks.rs`), and uses quite less memory when transposing the trace.
> Much smaller and faster trace to build.

- pipeline/Cargo.toml
- pipeline/src/lib.rs
- pipeline/src/pipeline.rs
- pipeline/tests/asm.rs
- pipeline/tests/pil.rs
- pipeline/tests/powdr_std.rs
- powdr_cli/src/main.rs
- powdr_riscv_rt/Cargo.toml
- powdr_riscv_rt/src/coprocessors.rs
- riscv/src/compiler.rs
- riscv/src/continuations.rs
- riscv/src/coprocessors.rs
- riscv/tests/common/mod.rs
- riscv/tests/instructions.rs
- riscv/tests/riscv.rs
- riscv/tests/riscv_data/evm/Cargo.toml
- riscv/tests/riscv_data/evm/src/lib.rs
- riscv_executor/Cargo.toml
- riscv_executor/src/lib.rs
This is easy to review commit by commit.
> Support serde data structures in pipeline

- riscv/tests/riscv.rs
> Fix expected error message for panic test.

- powdr/Cargo.toml
- powdr/src/lib.rs
The usage is a bit nicer, like this: https://github.com/powdr-labs/powdr-revme/pull/5/files#diff-322926ac8e657483f4af4b17984587cd911be04cdf671ecf5aac209867992c06R1-R7
> Add some aliases to powdr crate

- executor/src/witgen/machines/profiling.rs
This prevents panics in cases where the system clock is synced during witness generation.
> Use `Instant` instead of `SystemTime` for profiling

- ast/src/analyzed/mod.rs
Pulled out of #967
Allows this to work correctly:
```
let a, b;
col intermediate = a + b;
intermediate' = 3;
```
This inlines to:
`a' + b' = 3`
> Correctly apply next references to intermediate polynomials

- Cargo.toml
- airgen/Cargo.toml
- analysis/Cargo.toml
- asm-to-pil/Cargo.toml
- asm-utils/Cargo.toml
- ast/Cargo.toml
- backend/Cargo.toml
- cli/Cargo.toml
- executor/Cargo.toml
- halo2/Cargo.toml
- importer/Cargo.toml
- linker/Cargo.toml
- number/Cargo.toml
- parser-util/Cargo.toml
- parser/Cargo.toml
- pil-analyzer/Cargo.toml
- pilopt/Cargo.toml
- pipeline/Cargo.toml
- powdr/Cargo.toml
- riscv-executor/Cargo.toml
- riscv-runtime/Cargo.toml
- riscv/Cargo.toml
> add package info

- pil-analyzer/src/evaluator.rs
- std/dbg.asm
> Remove dbg.asm.

- riscv-executor/src/lib.rs
- riscv/src/compiler.rs
- riscv/src/continuations/bootloader.rs
Saved 2 witnesses and 2 fixed columns in vec_median.
> Merging instructions and saving a couple of columns.

- riscv/src/compiler.rs
> Bugfix: a couple of instructions were assigning to x0.

- pil-analyzer/src/statement_processor.rs
The function is defined on PILStatement already.
> Remove duplicate function.

- backend/src/pilstark/json_exporter/mod.rs
- pil-analyzer/src/lib.rs
- pil-analyzer/src/pil_analyzer.rs
- pilopt/src/lib.rs
- pipeline/src/pipeline.rs
- pipeline/tests/pil.rs
simplify the code a bit by just re-exporting the analyzer functions
> just re-export analyze functions

- analysis/Cargo.toml
- analysis/src/lib.rs
- asm-to-pil/Cargo.toml
- asm-to-pil/src/lib.rs
- parser/Cargo.toml
- parser/src/lib.rs
> Lazy parsers

- riscv/tests/riscv.rs
- riscv/tests/riscv_data/function_pointer/Cargo.toml
- riscv/tests/riscv_data/function_pointer/rust-toolchain.toml
- riscv/tests/riscv_data/function_pointer/src/lib.rs
Tests the mechanism used by function pointers and dynamic dispatch in general.
> Test for loading a function address into a register.

- backend/src/halo2_impl.rs
- backend/src/lib.rs
- backend/src/pilstark/estark.rs
- backend/src/pilstark/mod.rs
- cli/src/main.rs
- halo2/src/circuit_builder.rs
- halo2/src/circuit_data.rs
- halo2/src/mock_prover.rs
- halo2/src/prover.rs
- pipeline/src/pipeline.rs
- pipeline/src/test_util.rs
Fixes https://github.com/powdr-labs/powdr/issues/890
> Export verification key and use it for proof

- book/src/pil/declarations.md
- executor/src/constant_evaluator/mod.rs
- pilopt/src/lib.rs
- pipeline/tests/pil.rs
- std/arith.asm
- test_data/pil/arith_improved.pil
- test_data/pil/referencing_array.pil
> Support arrays of fixed columns.

- Cargo.toml
- backend/Cargo.toml
- halo2/Cargo.toml
> upgrade halo2

- halo2/src/circuit_builder.rs
- halo2/src/circuit_data.rs
- test_data/asm/full_pil_constant.asm
- test_data/asm/pil_at_module_level.asm
- test_data/pil/halo_without_lookup.pil
Fixes #1036 
See [this comment](https://github.com/powdr-labs/powdr/blob/339f777a52d2d8a752f73c290680c1df0cfc20d1/halo2/src/circuit_builder.rs#L55-L68) for how we build our Halo2 Circuits now.
Unfortunately, with the additional constraints, proof generation time has increased by around 25% :/
> Fix soundness bug in conversion to Halo2

- halo2/src/prover.rs
- pipeline/src/pipeline.rs
- pipeline/tests/pil.rs
- test_data/pil/trivial.pil
This reproduces an error in our Halo2 verification algorithm, see #1051.
> Test that proving fails for unsatisfying witness

- backend/src/halo2_impl.rs
- backend/src/lib.rs
- backend/src/pilstark/estark.rs
- backend/src/pilstark/mod.rs
- cli/src/main.rs
- halo2/src/prover.rs
- pipeline/src/pipeline.rs
- pipeline/src/test_util.rs
- pipeline/src/util.rs
- pipeline/src/verify.rs
Would like feedback first before changing eStark.
> Refactor of backend API

- std/binary.asm
- std/shift.asm
- std/split/split_bn254.asm
- std/split/split_gl.asm
- std/utils.asm
I also changed cross_product in the way it iterates through the rows. Now the first array element always updates and the last array elements updates when all the others have completed a cycle.
> Some more uses of cross_product

- riscv/tests/riscv_data/evm/Cargo.toml
- riscv/tests/riscv_data/evm/src/lib.rs
we can remove this TODO dependency now that nightly was updated
> update evm test

- ast/src/analyzed/display.rs
- ast/src/parsed/display.rs
- pil-analyzer/src/pil_analyzer.rs
- pil-analyzer/tests/types.rs
> Fix print function type

- cli/src/main.rs
- pipeline/src/pipeline.rs
The binary can get heavy at times so making it opt in for now
> make pilo output opt in

- std/array.asm
- std/hash/poseidon_bn254.asm
- std/hash/poseidon_gl.asm
Refactors the `PoseidonGL` machine in a way similar to `PoseidonBn254` (#1063). The diff between them is pretty small now!
> Refactor PoseidonGL machine

- executor/src/witgen/machines/block_machine.rs
- executor/src/witgen/sequence_iterator.rs
- std/hash/poseidon_bn254.asm
- std/hash/poseidon_gl.asm
> Poseidon Machines: Change latch to be on first row

- pipeline/src/test_util.rs
Somehow the type annotation is needed for my ide...
> Some fixes.

- pil-analyzer/src/statement_processor.rs
This check is now better done by the type checker.
> Remove constant check.

- executor/src/witgen/query_processor.rs
- pil-analyzer/src/evaluator.rs
- pipeline/src/test_util.rs
> Remove custom type from evaluator

- pipeline/src/verify.rs
Now it won't fill the tests output log with "ERROR" strings and scare me.
> Removing pilcom output on uneventful test runs.

- asm-to-pil/src/romgen.rs
- linker/src/lib.rs
- parser/src/powdr.lalrpop
Preparatory PR to add enum declaration which do not end in a semicolon.
> Parse semicolons as part of statements.

- riscv-executor/src/lib.rs
Fallback to field multiplication if native multiplication overflows.
> Fixing test_poseidon_gl.

- cli/Cargo.toml
- halo2/Cargo.toml
- pilopt/Cargo.toml
- pipeline/Cargo.toml
I'm confused why udeps does not flag some of these
> Remove unused dependencies

- backend/Cargo.toml
- backend/src/pilstark/estark.rs
- book/src/hello_world.md
- pipeline/src/pipeline.rs
- pipeline/src/test_util.rs
> Add verification key and verifier to estark

- cli/src/main.rs
- executor/src/witgen/affine_expression.rs
- executor/src/witgen/eval_result.rs
- pipeline/benches/executor_benchmark.rs
- pipeline/tests/pil.rs
- riscv/src/compiler.rs
- riscv/src/coprocessors.rs
- riscv/src/lib.rs
- riscv/tests/instructions.rs
- riscv/tests/riscv.rs
- test_data/pil/naive_byte_decomposition.pil
> Witgen: Don't derive non-unique witness when there might be overflow

- executor/src/witgen/machines/block_machine.rs
I tried implementing [this suggestion](https://github.com/powdr-labs/powdr/pull/1126#discussion_r1522967530) for the Poseidon machine, but hit some witgen issues when running:
```
cargo run pil test_data/std/poseidon_bn254_test.asm  -o output -f --field bn254 --prove-with halo2-mock
```
There were two problems:
- The Poseidon has two fixed columns: `FIRSTBLOCK` (the latch, offset 0 and period 66) and `LASTBLOCK` (offset 65 and period 66). Before this PR, `LASTBLOCK`'s offset of 65 was used as the latch row, which was wrong. This is fixed now by making sure we prefer fixed columns which appear in the selector expression.
- When setting the selector to 0 in the dummy block, we assumed that `latch_row == block_size - 1`. This is fixed now.
> Fix Witgen for machines connected by permutation with latch on first row

- riscv/src/continuations.rs
> make load memory from program function public

- asm-to-pil/src/vm_to_constrained.rs
- ast/src/analyzed/display.rs
- ast/src/analyzed/mod.rs
- ast/src/analyzed/visitor.rs
- ast/src/parsed/display.rs
- ast/src/parsed/mod.rs
- backend/src/pilstark/json_exporter/mod.rs
- book/src/pil/builtins.md
- executor/src/constant_evaluator/mod.rs
- executor/src/witgen/query_processor.rs
- parser/src/lib.rs
- parser/src/powdr.lalrpop
- pil-analyzer/src/condenser.rs
- pil-analyzer/src/evaluator.rs
- pil-analyzer/src/statement_processor.rs
- pil-analyzer/src/type_builtins.rs
- pil-analyzer/tests/parse_display.rs
- pipeline/src/test_util.rs
- pipeline/tests/pil.rs
- std/prover.asm
- test_data/pil/challenges.pil
> Challenges

- std/arith.asm
- std/binary.asm
- std/hash/poseidon_bn254.asm
- std/hash/poseidon_gl.asm
- std/shift.asm
- std/split/split_bn254.asm
- std/split/split_gl.asm
- test_data/std/arith_test.asm
- test_data/std/binary_test.asm
- test_data/std/poseidon_bn254_test.asm
- test_data/std/poseidon_gl_test.asm
- test_data/std/shift_test.asm
- test_data/std/split_bn254_test.asm
- test_data/std/split_gl_test.asm
> Allow and use permutation in all std machines

- pipeline/src/pipeline.rs
This is similar in behavior to what the Pipeline used to do before the DAG refactor. We keep important artifacts such as `asm_string`, `pil_string`, `optimized_pil` and the columns, and drop the artifacts that are built along the way. They can still be computed on-the-fly if some module needs them.
This saves 50% RAM during execution in a heavy benchmark.
> Drop some artifacts during pipeline

- airgen/src/lib.rs
- ast/src/asm_analysis/mod.rs
- ast/src/object/display.rs
- ast/src/object/mod.rs
- ast/src/parsed/asm.rs
- linker/src/lib.rs
- parser/src/powdr.lalrpop
- riscv/src/continuations.rs
- test_data/asm/empty_vm.asm
> Allow expression in degree statement

- powdr/Cargo.toml
- powdr/src/lib.rs
These are needed by https://github.com/0xEigenLabs/eigen-zkvm
> add more crates to powdr

- .github/workflows/build-cache.yml
- .github/workflows/nightly-tests.yml
- .github/workflows/pr-tests.yml
- asm-to-pil/src/vm_to_constrained.rs
- executor/src/witgen/affine_expression.rs
- executor/src/witgen/block_processor.rs
- executor/src/witgen/machines/profiling.rs
- executor/src/witgen/query_processor.rs
- pilopt/src/lib.rs
- rust-toolchain.toml
> Upgrade rust to 1.77

- .github/workflows/pr-tests.yml
- cli/src/main.rs
- executor/src/constant_evaluator/mod.rs
- executor/src/witgen/affine_expression.rs
- executor/src/witgen/block_processor.rs
- executor/src/witgen/global_constraints.rs
- linker/src/lib.rs
- number/src/lib.rs
- parser-util/src/lines.rs
- pil-analyzer/src/evaluator.rs
- pipeline/tests/asm.rs
- pipeline/tests/pil.rs
- riscv-executor/src/poseidon_gl.rs
- riscv/src/continuations/memory_merkle_tree.rs
- riscv/tests/riscv.rs
One is unecessary, the other is redundant.
> Removing pub and "test_" from test functions.

- .github/workflows/pr-tests.yml
- pipeline/src/pipeline.rs
- riscv/tests/riscv.rs
> Fixing broken example.

- pil-analyzer/src/evaluator.rs
delay the `split_off` decision to the `combine` method, many times we don't need a new `Vec`
> avoid `split_off` in `combine`

- ast/Cargo.toml
- ast/src/parsed/mod.rs
Implements part of https://github.com/powdr-labs/powdr/issues/1302
> Use auto_enums for expression children.

- ast/src/parsed/asm.rs
- ast/src/parsed/display.rs
- ast/src/parsed/mod.rs
- parser-util/src/lib.rs
- parser/src/powdr.lalrpop
- riscv/src/riscv_asm.lalrpop
- change lalrpop parsing errors to `String` to allow formatted msgs
- implement Display for MachineProperties and MachineArguments
> small improvements to machine properties handing

- executor/src/witgen/query_processor.rs
- pil-analyzer/src/evaluator.rs
Something I came across in #1306. This let's us do something like `let foo: fe = eval(some_column * some_challenge)`.
> Evaluate nested expressions

- book/src/SUMMARY.md
- book/src/publics.md
- pipeline/tests/asm.rs
- test_data/asm/sqrt_with_public.asm
Fixes https://github.com/powdr-labs/powdr/issues/1225
> Add book example that uses publics in asm

- LICENSE-APACHE
- LICENSE-MIT
- README.md
Followed https://github.com/arnavyc/dual-licensed-mit-apache
> Dual license

- Cargo.toml
- airgen/Cargo.toml
- analysis/Cargo.toml
- asm-to-pil/Cargo.toml
- ast/Cargo.toml
- backend/Cargo.toml
- cli-rs/Cargo.toml
- cli/Cargo.toml
- executor/Cargo.toml
- importer/Cargo.toml
- linker/Cargo.toml
- parser/Cargo.toml
- pil-analyzer/Cargo.toml
- pilopt/Cargo.toml
- pipeline/Cargo.toml
- powdr-test/Cargo.toml
- powdr/Cargo.toml
- riscv-executor/Cargo.toml
- riscv-runtime/Cargo.toml
- riscv/Cargo.toml
- schemas/Cargo.toml
Trying this out which will make releases much easier
> move internal dependencies to shared version

- Cargo.toml
- riscv-runtime/Cargo.toml
> bump version

- asm-utils/src/utils.rs
- riscv/src/compiler.rs
In preparation for supporting RISC-V from binary.
> Refactoring instruction processor to be more generic.

- asm-utils/src/utils.rs
- riscv/src/compiler.rs
Still not the full generic version: only supports zero offset.
> Implementing a more generic version of `jalr`.

- std/machines/arith.asm
- test_data/std/arith_test.asm
Only the asm file changes that's ready to merge. To be paired with another PR that will be updated and merged later: #1404
> modul asm only

- cli-rs/src/main.rs
- riscv-executor/Cargo.toml
- riscv-executor/src/lib.rs
- riscv-executor/src/profiler.rs
- riscv/src/continuations.rs
- riscv/tests/common/mod.rs
- riscv/tests/riscv.rs
Rust profiler (#1174) implemented by tracking the execution of the `riscv-executor`.
> profiler for powdr asm compiled from rust

- riscv/tests/riscv_data/vec_median/src/lib.rs
Closes #1387, thanks @onurinanc
> Fix instructions to run `vec_median`

- pipeline/tests/asm.rs
- test_data/asm/challenges.asm
Adds a simple test for challenges, should be a good starting point to test challenges with additional backends.
> Add simple challenges test

- ast/src/analyzed/mod.rs
- pil-analyzer/src/evaluator.rs
- pil-analyzer/tests/condenser.rs
> Allow prime on all algebraic expressions

- executor/src/witgen/machines/block_machine.rs
Some witness generation fixes needed to make #1508 work:
- When we check whether we already answered the query, we assumed that the latch row is the last row; now, we use the actual latch row.
- That same check might access any row in the last block, so now we never finalize the last block.
> Witgen: Bug fixes in Block machine witness generation

- executor/src/witgen/block_processor.rs
- executor/src/witgen/data_structures/finalizable_data.rs
- executor/src/witgen/generator.rs
- executor/src/witgen/machines/block_machine.rs
- executor/src/witgen/processor.rs
- executor/src/witgen/rows.rs
- executor/src/witgen/vm_processor.rs
The main goal here is to hide the inner structure of a Row so that it can be more easily optimized later.
> Refactor rows a little.

- std/math/fp2.asm
- std/protocols/fingerprint.asm
- std/protocols/lookup.asm
- std/protocols/mod.asm
- std/protocols/permutation.asm
- std/prover.asm
- std/utils.asm
- std/well_known.asm
This PR aims to merge common functions in `permutation.asm` and `lookup.asm` as much as possible.
> Merge common functions in permutation and lookup

- riscv/Cargo.toml
> Using mainline raki

- riscv/src/elf.rs
> Fixing atomic instructions in ELF translate.

- executor/src/witgen/machines/block_machine.rs
Since #1385 is resolved, we can fix this TODO.
> Block machine:  report side effect (fixes TODO)

- executor/src/constant_evaluator/mod.rs
- executor/src/witgen/query_processor.rs
- pil-analyzer/src/condenser.rs
- pil-analyzer/src/evaluator.rs
- pipeline/src/test_util.rs
Extracted from @Schaeff `s https://github.com/powdr-labs/powdr/pull/1623
> Improve evaluator

- ast/src/parsed/types.rs
- pil-analyzer/src/type_inference.rs
- pil-analyzer/src/type_unifier.rs
> Lazy substitution

- ast/src/analyzed/display.rs
- ast/src/analyzed/mod.rs
- ast/src/parsed/display.rs
- ast/src/parsed/mod.rs
- executor/src/constant_evaluator/mod.rs
- pil-analyzer/src/expression_processor.rs
- pil-analyzer/src/pil_analyzer.rs
- pil-analyzer/src/statement_processor.rs
- pilopt/src/lib.rs
Equivalent to #1623  but in Rust
Closes #1570
@georgwiese I wanted to add a test but everything I try either panics (we sometimes assume the fixed columns to be available in a single size) or runs forever (when I add fixed columns to a machine, I assume witgen keeps increasing the degree and never stops? or it picks the largest size and just takes time?) any thoughts?
> Delay array expression solving until constant evaluator

- cli-rs/src/main.rs
- executor/src/witgen/machines/double_sorted_witness_machine.rs
- riscv-executor/src/lib.rs
- riscv/Cargo.toml
- riscv/benches/executor_benchmark.rs
- riscv/src/continuations.rs
- riscv/src/continuations/bootloader.rs
- riscv/src/runtime.rs
- riscv/tests/riscv.rs
- riscv/tests/riscv_data/many_chunks/src/main.rs
Depends on https://github.com/powdr-labs/powdr/pull/1655
This PR is based on https://github.com/powdr-labs/powdr/pull/1533 on top of registers in memory and the new links.
> Use poseidon with memory in the riscv machine

- std/machines/hash/poseidon_gl.asm
- std/machines/hash/poseidon_gl_memory.asm
Depends on https://github.com/powdr-labs/powdr/pull/1599
Needed to be used with Plonky3.
> Decrease degree of constraints in poseidon_gl_memory

- backend/src/composite/mod.rs
- backend/src/composite/split.rs
- executor/src/constant_evaluator/data_structures.rs
- executor/src/witgen/mod.rs
Small one extracted from #1667
> Use degree type where applicable

- cli/src/main.rs
- cli/src/util.rs
- number/Cargo.toml
- number/src/baby_bear.rs
- number/src/lib.rs
- number/src/traits.rs
- riscv/src/code_gen.rs
Most minimal attempt at adding BabyBear, only adds the field and field tests, but no powdr tests using the field.
> baby bear field only

- plonky3/Cargo.toml
Merging https://github.com/powdr-labs/Plonky3/tree/uni-stark-with-fixed and changing dependencies accordingly.
> Switching dependencies to main branch of Plonky3 fork

- ast/src/parsed/mod.rs
- importer/src/path_canonicalizer.rs
- parser/src/powdr.lalrpop
https://github.com/powdr-labs/powdr/pull/1736#discussion_r1740736729
> Use expression as type param in trait implementation

- pipeline/tests/powdr_std.rs
- std/protocols/bus.asm
- std/protocols/lookup_via_bus.asm
- std/protocols/permutation.asm
- std/protocols/permutation_via_bus.asm
- test_data/asm/block_to_block_with_bus.asm
- test_data/std/bus_lookup_via_challenges.asm
- test_data/std/bus_lookup_via_challenges_ext.asm
- test_data/std/bus_permutation_via_challenges.asm
- test_data/std/bus_permutation_via_challenges_ext.asm
- test_data/std/permutation_via_challenges.asm
- test_data/std/permutation_via_challenges_ext.asm
Similar to #1796, changed the structure of the permutation function
> Create is_first inside the permutation

- std/array.asm
Really small. Just thought might not be appropriate to put in Keccak.
> Array reverse helper

- pipeline/src/lib.rs
handle both queries in the same place
> unify Query::Input/DataIdentifier handling

- pipeline/tests/powdr_std.rs
- std/machines/hash/mod.asm
- std/machines/split/mod.asm
- std/machines/split/split_bb.asm
- test_data/std/split_bb_test.asm
> SplitBB machine

- parser/src/powdr.lalrpop
- pil-analyzer/tests/evaluator.rs
> Support for non-spaced empty blocks

- .github/workflows/build-cache.yml
- .github/workflows/pr-tests.yml
BuildJet cache is broken and they won't answer support ticket.
> Using Warpbuild instead of BuildJet

- pipeline/tests/powdr_std.rs
- std/machines/add_sub16.asm
- std/machines/mod.asm
- test_data/std/add_sub16_test.asm
Extracted from https://github.com/powdr-labs/powdr/pull/1790
> add sub machine for BB riscv

- plonky3/src/params/baby_bear.rs
- plonky3/src/params/goldilocks.rs
p3 compilation started failing recently, this hopefully fixes it
> fix compilation p3

- std/machines/arith16.asm
- test_data/std/arith16_test.asm
Applied the feedback that I gave in my review for #1790. See in-line comments.
> Improvements to Arith16 machine

- executor/src/witgen/machines/double_sorted_witness_machine_16.rs
- std/machines/memory16.asm
This removes a complicated comparison mechanism introduced in #1874.
Previously, time steps were compared differently from addresses. Now, both are compared the same way which is:
- The prover provides a bit indicating whether the high limbs of the values are equal
- If this bit is 1, a constraints asserts this is actually the case
- The prover provides the 16-Bit difference minus one on the limb that differs. This asserts that the limb value is strictly increasing.
> Simplify BabyBear memory machine

- parser/src/lib.rs
- parser/src/powdr.lalrpop
> Parser: Allow trailing `,` in all lists.

- plonky3/src/params/baby_bear.rs
- plonky3/src/params/goldilocks.rs
- plonky3/src/params/mersenne_31.rs
- plonky3/src/params/mod.rs
- plonky3/src/params/poseidon2.rs
Repeating #1869 also for Goldilocks and M31. Builds on #1880.
> Sample Poseidon2 constants correctly also for Goldilocks and M31

- asm-to-pil/src/vm_to_constrained.rs
The `linearize` function reduces the degree of update constraints to linear. This is not strictly necessary and could be done at a later stage that is not specific to asm update constraints.
This function paniced for anything that is not a simple algebraic expression. This PR extends the functionality to any expression, linearizing all operands of a binary operator.
Note that this will still not result in a proper expression for anything that is more complex than a simple algebraic expression.
At some point, we should move this processing to a stage like the condenser or even later (close to the optimizer, or even make it backend-specific).
> Support any update constraint.

- plonky3/src/circuit_builder.rs
This turns `a**3` into `a * a * a` inside plonky3 instead of panicking. cc @leonardoalt
> Support constant exponentiation in p3

- jit-compiler/src/codegen.rs
- jit-compiler/src/compiler.rs
- pipeline/benches/evaluator_benchmark.rs
Closes https://github.com/powdr-labs/powdr/issues/1854
> JIT: Efficient vector

- riscv/src/small_field/code_gen.rs
> removing outdated comments

- backend/Cargo.toml
- number/Cargo.toml
- plonky3/Cargo.toml
Tag is also acceptable. Branch is not.
Solves #1914
> Pinning git dependencies to git revision.

- jit-compiler/tests/execution.rs
Speed up test execution by only compiling once per test.
> Only compile once in tests.

- plonky3/src/prover.rs
- plonky3/src/symbolic_builder.rs
- plonky3/src/verifier.rs
Just some minor adjustments I made while reading through the proving code.
> Refactor Plonky3 prover

- cargo-powdr/template/src/main.rs
- powdr/src/lib.rs
- riscv/src/large_field/code_gen.rs
- riscv/src/lib.rs
Just make the Session stuff a bit cleaner.
The removed files were merged by accident.
> Improve powdr lib

- Cargo.toml
> change version to 0.1.0

- parser-util/Cargo.toml
- plonky3/Cargo.toml
- riscv-executor/Cargo.toml
removes some unused dependencies as flagged by udeps in the nightly tests.
fmt also changed some random stuff
> remove unused deps

- .github/workflows/build-cache.yml
- .github/workflows/pr-tests.yml
Also, shallow git clones and more verbose build output, to make it easier to diagnose why something was rebuilt.
> Builds on better runner.

- pipeline/tests/powdr_std.rs
- std/protocols/fingerprint.asm
This will make it easier to verify refactorings like #1985.
> Add test of `fingerprint()` function

- examples/keccak/Cargo.toml
- examples/keccak/guest/Cargo.toml
- examples/keccak/src/main.rs
- powdr/src/lib.rs
- riscv/src/continuations.rs
Extracted from https://github.com/powdr-labs/powdr/pull/2012
> fix chunk artifact output

- std/machines/hash/mod.asm
- std/machines/hash/poseidon2_bb.asm
- std/machines/hash/poseidon2_common.asm
- std/machines/small_field/pointer_arith.asm
- test_data/std/poseidon2_bb_test.asm
> Split common parts of poseidon2 out of poseidon2_bb

- backend-utils/src/lib.rs
Fixes #1588
To test, you can run [Leo's example](https://gist.github.com/leonardoalt/7ba8071d9ac98f1b4e06f5b5c0d81f6b) (with `--prove-with plonky3`). The proof doesn't verify, but that appears to be a separate issue.
> `split_pil`: Put public declarations into the correct namespace

- std/machines/hash/poseidon2_bb.asm
- std/machines/hash/poseidon2_gl.asm
- test_data/std/poseidon2_bb_test.asm
- test_data/std/poseidon2_gl_test.asm
It is not clear that omiting the output of capacity helps with performance, nor that it is an adequate optimization, since the inner stages of sponge can be implemented by omitting the output of the rate (but need the capacity).
> Reverse early optimization on poseidon2 API.

- Cargo.toml
- riscv-runtime/Cargo.toml
> update main to 0.1.2

- powdr/src/lib.rs
- riscv/src/lib.rs
Needed this in order to make a host and accelerate https://github.com/leonardoalt/ecdsa-powdr/
> expose precompile choices to the user

- executor/src/witgen/sequence_iterator.rs
Fixes a bug I encountered in #2109:
- For blog machines, we have a cache which tracks a sequence of solving steps that led to a success in the past.
- However, the needed sequence could be different from call to call. In particular, it could depend on the operation ID.
- Because of that, in #1562, we added that the "default" sequence iterator is always run after the cached sequence.
- But, we never called `report_progress()` on the default iterator, which led to a bug in #2109.
> Bug fix in ProcessingSequenceIterator

- test_data/asm/block_to_block_empty_submachine.asm
See [this comment](https://github.com/powdr-labs/powdr/pull/2127#issuecomment-2493020030). This updated test would have caught a bug fixed in #2127.
> Make test more complicated

- riscv/src/large_field/code_gen.rs
- riscv/src/riscv_gl.asm
Fixes https://github.com/powdr-labs/powdr/issues/1619
> Extract RISCV machine from strings into template file

- executor/src/witgen/mod.rs
Fixes a performance issue with intermediate polynomials.
> `FixedData::polynomial_references`: Cache results for intermediate columns

- backend/src/lib.rs
This allows us too have VADCOP proofs with Stwo.
> Add `stwo-composite` backend

- riscv-executor/src/profiler.rs
makes execution ~2x faster when using the profiler
> profiler: use function ids instead of strings

- backend/src/mock/connection_constraint_checker.rs
- pipeline/tests/mock_backend.rs
- pipeline/tests/pil.rs
Adds some (negative) tests for `MockBackend`.
> Add `MockBackend` tests

- pipeline/tests/mock_backend.rs
> remove log init from test

- executor/src/witgen/processor.rs
- executor/src/witgen/query_processor.rs
This reverts commit d980c68f89386160e3ffd6b2ce4e62f26c045cdf from https://github.com/powdr-labs/powdr/pull/2176
> Revert "Parallelize calls to prover functions (#2176)"

- executor/src/witgen/machines/machine_extractor.rs
- executor/src/witgen/mod.rs
I tried to debug why the RISC-V machine doesn't work with `--linker-mode bus` yet, and this adds helpful error messages.
> Better error message if things go wrong in machine extraction

- executor/src/witgen/machines/double_sorted_witness_machine_32.rs
Change memory machine to use pages instead of a "flat" map.
> Paged memory

- executor/src/witgen/machines/fixed_lookup_machine.rs
- executor/src/witgen/machines/mod.rs
> Implement `process_lookup_direct` for KnownMachine & change interface slightly

- .github/workflows/deploy-book.yml
> Fix book deploy

- .github/workflows/pr-tests.yml
- asmopt/Cargo.toml
This PR fixes udeps again and finally adds it to the pr-tests so it fails in a PR already.
> fix udeps and add to pr-tests

- backend/src/plonky3/stark.rs
- plonky3/src/prover.rs
We removed them in the proof, but still ran second-stage witgen for it.
> Fix Plonky3 proofs for removed machines

- asm-to-pil/src/romgen.rs
> Rename `_start` to `_powdr_start`

- executor/src/witgen/jit/compiler.rs
- executor/src/witgen/jit/includes/README.txt
- executor/src/witgen/jit/includes/field_generic_up_to_64.rs
- executor/src/witgen/jit/includes/field_goldilocks.rs
- executor/src/witgen/jit/includes/interface.rs
- number/src/traits.rs
This is mostly a reduced copy of the goldilocks implementation we already have with the main difference that the division tries to perform integer division first if it can be done without remainder.
> Specialized code for goldilocks.

- cargo-powdr/template/Cargo.toml.template
- cargo-powdr/template/guest/Cargo.toml.template
- examples/fibonacci/Cargo.toml
- examples/fibonacci/guest/Cargo.toml
- examples/keccak/Cargo.toml
- examples/keccak/guest/Cargo.toml
I created a temporary tag 0.1.3 out of this branch for testing. Once this is merged into main I'll rewrite the tag and publish it.
> changes for release 0.1.3

- executor/src/witgen/data_structures/mutable_state.rs
- executor/src/witgen/jit/affine_symbolic_expression.rs
- executor/src/witgen/jit/compiler.rs
- executor/src/witgen/jit/single_step_processor.rs
- executor/src/witgen/jit/symbolic_expression.rs
- executor/src/witgen/jit/witgen_inference.rs
- executor/src/witgen/machines/double_sorted_witness_machine_32.rs
- executor/src/witgen/machines/fixed_lookup_machine.rs
- executor/src/witgen/machines/mod.rs
- executor/src/witgen/range_constraints.rs
> Simplify range constraints.

- executor/src/witgen/jit/witgen_inference.rs
If we want to propagate range constraints across completed assignments, we cannot delete them.
> Keep completed assignments.

- ast/src/analyzed/mod.rs
- executor/src/witgen/jit/processor.rs
- executor/src/witgen/jit/single_step_processor.rs
- executor/src/witgen/jit/witgen_inference.rs
Closes https://github.com/powdr-labs/powdr/issues/2342
> Occurrence map

- executor/src/witgen/jit/function_cache.rs
Uses the `?` operator to reduce indentation.
> Exit early in compile_witgen_function.

- executor/src/witgen/machines/double_sorted_witness_machine_32.rs
Extracted from https://github.com/powdr-labs/powdr/pull/2382
> Memory machine: Assert that step must not decrease

- executor/src/witgen/machines/dynamic_machine.rs
Refactoring extracted out of #2338
> Extract compute_row_block.

- .github/workflows/nightly_tests_list.txt
- executor/src/witgen/machines/double_sorted_witness_machine_32.rs
This should break the CI PR tests. The idea is to fix it in this PR.
Edit: it is fixed now
> add div instr test to pr tests

- executor/src/witgen/jit/prover_function_heuristics.rs
We will need the index later on when we add calls to prover functions to uniquely identify the prover function to be called.
> Store index with extracted prover functions.

- riscv-executor/src/submachines.rs
Fix required by #2389. Can only be merged after #2389.
> Single row binary executor

- jit-compiler/src/codegen.rs
- jit-compiler/src/lib.rs
Abstract away the access to definitions to help with testing.
> Abstract access to definitions.

- std/machines/large_field/arith.asm
- std/prover.asm
I think this is the last part for prover functions, which is needed for the arithmetic machine:
Compute the values of multiple cells at the same time from other known cells, but only if a condition is true. The biggest challenge here is that we need to be able to evaluate the condition at compile time.
> Compute multiple cell values conditionally from other cell values.

- linker/src/bus.rs
cc @leonardoalt 
32 bit interaction ids are too large for small fields. Switch to 16 bit.
> Make interaction ids 16 bits

- backend/Cargo.toml
- backend/src/stwo/circuit_builder.rs
- backend/src/stwo/prover.rs
Updated small API changes to align with the latest version of Stwo.
> update stwo version to the latest

- std/machines/large_field/arith256_memory.asm
Blocking #2425 , adapted from `arith256.asm`
> Make memory arith JIT ready

- ast/src/analyzed/display.rs
- ast/src/analyzed/mod.rs
- backend/src/estark/json_exporter/expression_counter.rs
- backend/src/estark/json_exporter/mod.rs
- backend/src/halo2/circuit_builder.rs
- backend/src/mock/connection_constraint_checker.rs
- backend/src/stwo/circuit_builder.rs
- executor/src/witgen/data_structures/identity.rs
- pil-analyzer/src/condenser.rs
- pilopt/src/lib.rs
- plonky3/src/circuit_builder.rs
- std/prelude.asm
WIP. For Stwo native logup use.
> Native bus interaction

- ast/src/analyzed/mod.rs
- executor/src/witgen/block_processor.rs
- executor/src/witgen/jit/block_machine_processor.rs
- executor/src/witgen/jit/compiler.rs
- executor/src/witgen/jit/interpreter.rs
- executor/src/witgen/jit/single_step_processor.rs
- executor/src/witgen/jit/variable.rs
- executor/src/witgen/jit/witgen_inference.rs
- executor/src/witgen/machines/machine_extractor.rs
- executor/src/witgen/machines/mod.rs
- executor/src/witgen/machines/second_stage_machine.rs
Adds intermediate columns as actual variables for the autowitjitgen.
> Represent intermediate columns as variables.

- executor/src/witgen/jit/block_machine_processor.rs
- executor/src/witgen/jit/code_cleaner.rs
- executor/src/witgen/jit/compiler.rs
- executor/src/witgen/jit/effect.rs
- executor/src/witgen/jit/identity_queue.rs
- executor/src/witgen/jit/interpreter.rs
- executor/src/witgen/jit/processor.rs
- executor/src/witgen/jit/single_step_processor.rs
- executor/src/witgen/jit/variable.rs
- executor/src/witgen/jit/witgen_inference.rs
Reverts #2527 
I was wrong, the change is not actually needed in #2488...
> Revert "Add type parameter to `MachineCallVariable` (#2527)"

- riscv-executor/src/lib.rs
- missing columns
- poseidon instruction change
> fix executor witness

- asm-to-pil/src/vm_to_constrained.rs
- riscv-executor/src/lib.rs
- riscv/src/continuations/bootloader.rs
update the fixed PC values of bootloader jump instructions
> fix bootloader

- ast/src/parsed/mod.rs
Small one, just the Children implementation.
> Function definition public declaration

- cli-rs/src/main.rs
- plonky3/src/bin/gen_poseidon_consts.rs
> Fix clippy.

- book/src/frontends/riscv.md
> link-Update riscv.md

- executor/src/witgen/jit/block_machine_processor.rs
- executor/src/witgen/jit/identity_queue.rs
- executor/src/witgen/jit/processor.rs
- executor/src/witgen/jit/single_step_processor.rs
Fixes https://github.com/powdr-labs/powdr/issues/2597
> Do now follow intermediate columns.

- autoprecompiles/src/lib.rs
change autoprecompile optimizations for the case where bus interaction kind is not available but implied from the multiplicity
> Autoprecompiles: support kind implied from multiplicity

- autoprecompiles/src/lib.rs
Some small refactors to help with clarity, remove unused things and flag things that could be removed.
> Clean up apc

- autoprecompiles/src/lib.rs
- autoprecompiles/src/powdr.rs
After rewriting history of the autoprecompiles v1 branch
> Redo https://github.com/powdr-labs/powdr/pull/2675

- constraint-solver/src/lib.rs
- constraint-solver/src/quadratic_symbolic_expression.rs
- constraint-solver/src/test_utils.rs
- constraint-solver/tests/solver.rs
Implementation of substitute_by_unknown & tests
> QSE: substitute_by_unknown

- autoprecompiles/src/lib.rs
- autoprecompiles/src/optimizer.rs
- constraint-solver/src/constraint_system.rs
Ready for a preliminary review. I'm not sure if CI will pass.
This is required for https://github.com/powdr-labs/powdr-openvm/pull/101.
> Apc remove all constant lookups

- autoprecompiles/src/lib.rs
Builds on #2696
With the current APC optimizer, the legacy optimizer does nothing, so we can remove it!
> Remove pilopt from APC optimizer

- autoprecompiles/src/lib.rs
- autoprecompiles/src/powdr.rs
> Revert "More apc clean up"

- constraint-solver/src/constraint_system.rs
Builds on #2722
Removes redundant code & fixes a TODO.
> Remove `expr_to_range_constraint`

- openvm/src/plonk/air_to_plonkish.rs
- openvm/src/plonk/mod.rs
Synchronise this [PR](https://github.com/powdr-labs/powdr-openvm/pull/116) in powdr-openvm
> Add air to plonk air circuit compiler 

- openvm/src/customize_exe.rs
Moved over from https://github.com/powdr-labs/powdr-openvm/pull/119. All changes reviewed and ready for merge.
> Removed unwanted basic block

- openvm/src/plonk/air_to_plonkish.rs
- openvm/src/powdr_extension/plonk/chip.rs
This should be a good entrypoint for #2779.
> PlonK compiler: Get entire machine

- openvm/src/plonk/air_to_plonkish.rs
- openvm/src/plonk/bus_interaction_handler.rs
With this PR, we don't allocate PlonK gates to compute the same expression twice anymore, and instead just re-use the existing variable.
I also couldn't resist to refactor the code: Rather than adding yet another `&mut ...` to `air_to_plonkish`, I introduced a `CircuitBuilder`. I recommend reviewing this code with the "Hide whitespace" setting, as most line changes are due to existing code being indented differently.
Reduces the number of gates for Keccak from 21747 to 11466, as printed by:
`RUST_LOG=powdr_openvm::powdr_extension::plonk=debug cargo test -r keccak_plonk_small_prove_mock -- --nocapture`
> Cache Plonk Gates & Refactor

- cli-openvm/Cargo.toml
- openvm/Cargo.toml
Needs to be updated with the correct hashes after merges of the prs in stark-backend and openvm
> Update openvm and stark-backend

- Cargo.toml
- cli-openvm/Cargo.toml
- openvm/Cargo.toml
Fewer places to change the rev
> Move deps to workspace

- openvm/src/customize_exe.rs
- openvm/src/lib.rs
We currently include the bus map in the powdr config. However, it is not a parameter we can chose, but rather depends on the original vm. Move it there, still returning the default one. Next step would be ideally generating it from the vm config.
Also use `OriginalProgram` when possible, to keep the program and config together.
> Refactor bus map retrieval

- autoprecompiles/src/lib.rs
- openvm/tests/apc_builder.rs
I still refuse to memorize bus IDs.
> Pretty tests

- autoprecompiles/src/symbolic_machine_generator.rs
Builds on #2900
Removes a hack that we needed to do because the solver wasn't able to solve for register addresses. This is fixed by #2900.
> Remove is_load heuristic

- constraint-solver/src/solver/exhaustive_search.rs
See performance discussion in #2900.
> Tweak exhaustive search params

- autoprecompiles/src/bus_map.rs
- openvm/src/bus_interaction_handler/mod.rs
- openvm/src/plonk/bus_interaction_handler.rs
- openvm/src/plonk/mod.rs
It's internal to sha256 which we don't use in apc
> Remove sha bus

- openvm/src/opcode.rs
Replace hard coded opcode numbers with OVM imports.
> Make opcode constant derivation more robust

- .github/workflows/nightly-tests.yml
Waiting for https://github.com/powdr-labs/powdr/actions/runs/15777736373/job/44475889809
> update nightly reth script

- Cargo.toml
- cli-openvm/Cargo.toml
- cli-openvm/src/main.rs
allows exporting metrics to a json file
> add `--metrics` to `prove` command

- openvm/guest-keccak-manual-precompile/Cargo.toml
- openvm/guest-keccak-manual-precompile/src/main.rs
- openvm/guest-keccak/Cargo.toml
- openvm/guest-keccak/src/main.rs
- openvm/guest-matmul/Cargo.toml
- openvm/guest/Cargo.toml
- openvm/guest/src/main.rs
Change the openvm guest tests to use powdr/openvm main branch and update the code accordingly.
> Update openvm guests

- openvm/guest-matmul/src/main.rs
- openvm/src/lib.rs
added a test to at least catch it on nightly
> fix `guest-matmul`

- .github/workflows/nightly-tests.yml
- openvm/scripts/basic_metrics.py
- openvm/scripts/requirements.txt
- openvm/scripts/run_guest_benches.sh
This PR runs a few benchmarks nightly, saving the results to a separate repo: `bench-results`.
Idea is to get something going on and improve reporting later.
Currently, it runs `keccak` and `reth`.
> nightly benchmarks

- openvm/scripts/basic_metrics.py
- openvm/scripts/metrics_utils.py
- openvm/scripts/plot_trace_cells.py
- Extracted a function to load the metrics file, which already separates the different proof stages
- Use it in `openvm/scripts/plot_trace_cells.py`
> `plot_trace_cells.py`: Only count app proofs

- .github/workflows/nightly-tests.yml
- openvm/scripts/plot_effectiveness.py
- openvm/scripts/run_guest_benches.sh
Builds on #3023 and https://github.com/powdr-labs/openvm-reth-benchmark/pull/23
Worked on this manually triggered nightly run:
https://github.com/powdr-labs/powdr/actions/runs/16182186333/job/45680988436
See these results:
https://github.com/powdr-labs/bench-results/tree/gh-pages/results/2025-07-10-0155
> Benchmarks: Generate effectiveness plots

- openvm/scripts/plot_effectiveness.py
fix the script for the new apc candidates json format
> Fix effectiveness plot

- .github/workflows/nightly-tests.yml
> Point reth to main

- riscv-elf/src/rv64.rs
Use iterators instead of while loop and globa state.
> Make rv64 label detection more idiomatic

- constraint-solver/src/indexed_constraint_system.rs
- constraint-solver/src/solver/exhaustive_search.rs
It is not really an intrinsic task of the constraint system to derive assignments.
> Move derive_more... to exhaustive search module.

- openvm/tests/apc_builder.rs
Added a wrong comment in #3097 :/
> Fix typo on comment

- constraint-solver/src/boolean_extractor.rs
Fixes https://github.com/powdr-labs/powdr/issues/3095
> Do not extract variables that are already boolean.

- constraint-solver/src/indexed_constraint_system.rs
- constraint-solver/src/journaling_constraint_system.rs
- constraint-solver/src/solver/quadratic_equivalences.rs
> Remove leftover code relating to bus field assignments.

- .github/workflows/nightly-tests.yml
This branch passed nightly test_apc here: https://github.com/powdr-labs/powdr/actions/runs/16828983380/job/47671913748
> Fix nightly

- autoprecompiles/src/constraint_optimizer.rs
- constraint-solver/src/solver.rs
- constraint-solver/src/solver/boolean_extracted.rs
- constraint-solver/src/solver/var_transformation.rs
This introduces a single solver layer that does the variable transformations. This way the trait bounds are much easier to state.
> Introduce var transformation.

- openvm/src/bus_interaction_handler/variable_range_checker.rs
Extracted from #3130 
See [this comment](https://github.com/powdr-labs/powdr/pull/3130/files#r2268175800):
> If the bit value is not in range, `handle_variable_range_checker` will return the expected range, and `handle_bus_interaction_checked` will intersect it with the previous range constraint (a known number), notice the ranges don't overlap, and return an error.
As part of #3130, it might happen that the brute-force algorithm tries to set the `bits` field to an out-of-range value. As mentioned in the comment above, this would anyway result in an error if `handle_bus_interaction_checked` is used, so panicking here is overly strict.
> Update Bus Interaction handler for the variable range checker bus

- openvm/scripts/basic_metrics.py
Adds `app_proof_cols` and `total_proof_time_ms` columns to the result CSV.
> Improve basic metrics summary

- openvm/extensions/hints-circuit/src/executors.rs
Normalize the hint before sending to prover from host
> Normalize the hint before sending to prover from host

- .github/workflows/post-merge-tests.yml
run some of the nightly tests in a non-blocking way after merging to main
> post merge APC tests

- autoprecompiles/src/lib.rs
- autoprecompiles/src/powdr.rs
> Remove bounds

- openvm/src/extraction_utils.rs
Ready for review. The whole thing doesn't compile yet but might as well just get features in as we eliminate compilation errors?
> [Ovm 1.4] get original airs

- openvm/src/extraction_utils.rs
They no longer provide convenient APIs for the buses so had to get them scattered around.
> [OVM-1.4] patch bus map
