powdr-labs/powdr

src/witness_generator/bit_constraints.rs
src/witness_generator/machines/fixed_lookup_machine.rs
src/witness_generator/mod.rs
tests/pil_data/pair_lookup.pil

When we see a lookup `{a, b, c} in {A, B, C}` where `A, B, C` are fixed, we currently do a linear search in `A, B, C`, filtering out rows where concrete values do not match.
Instead:
- take the subset of `{a, b, c}` which is constant. Say a = 2, b = 3. Let's call that the input. We call `[c]` the output.
- build an index for the corresponding fixed columns, here `[A, B]`, so that given concrete values `[a, b]` we can know in constant time the rows in which `A == a` and `B == b`
- get the values of the output at these rows, say `c in [4, 5, 6]`
- error out if we have more than one value (already implemented before this change)
- instead of solving for all columns, only solve for the outputs, as the inputs are already known
Todo:

Fixed lookup indices

---

src/witness_generator/generator.rs
src/witness_generator/mod.rs

A lot of times borrow checker issues stem from things being implemented on a struct rather than on its members. Doing the latter helps the borrow checker because it needs references to the members, not to the whole struct, which makes the references less likely to clash.

Avoid cloning witness cols for each row

---

Cargo.toml
src/analyzer/mod.rs
src/analyzer/pil_analyzer.rs
src/asm_compiler/mod.rs
src/bin/compiler.rs
src/compiler.rs
src/constant_evaluator/mod.rs
src/lib.rs
src/number.rs
src/parser/ast.rs
src/parser/powdr.lalrpop
src/riscv/mod.rs
src/witness_generator/affine_expression.rs
src/witness_generator/bit_constraints.rs
src/witness_generator/expression_evaluator.rs
src/witness_generator/fixed_evaluator.rs
src/witness_generator/generator.rs
src/witness_generator/machines/block_machine.rs
src/witness_generator/machines/double_sorted_witness_machine.rs
src/witness_generator/machines/fixed_lookup_machine.rs
src/witness_generator/machines/mod.rs
src/witness_generator/machines/sorted_witness_machine.rs
src/witness_generator/mod.rs
src/witness_generator/symbolic_evaluator.rs
src/witness_generator/symbolic_witness_evaluator.rs
tests/asm.rs
tests/common/mod.rs
tests/pil.rs
tests/riscv.rs

Using field division everywhere except for computation of constants.
Todo:

Use ark_ff under the hood

---

compiler/tests/asm.rs
parser/src/ast.rs
pilgen/src/lib.rs
test_data/asm/bit_access.asm
test_data/asm/functional_instructions.asm
test_data/asm/mem_read_write.asm
test_data/asm/multi_assign.asm
test_data/asm/palindrome.asm
test_data/asm/simple_sum.asm

Currently the pc can increase beyond the program pc. Force it to stay within bounds with an explicit infinite loop in asm.
This reduces the program lookup index.

Restrict pc

---

executor/src/witgen/affine_expression.rs

This makes the loop a little slower:
From 8.2k rows/sec to 7.7k rows/sec
But the regular computations roughly double in speed:
From 430 to 820 rows/sec

Use BTreeMap for AffineExpression.

---

executor/src/witgen/eval_result.rs
executor/src/witgen/expression_evaluator.rs
executor/src/witgen/fixed_evaluator.rs
executor/src/witgen/generator.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/symbolic_evaluator.rs
executor/src/witgen/symbolic_witness_evaluator.rs

Depends on #227 
Improves witness generation on keccak from 2.0k rows/sec to 2.8k

Use poly ref in expression evaluator.

---

compiler/src/lib.rs
compiler/src/verify.rs

If a relative output dir was used, it was concatenated twice in the json output path, causing a panic because path didn't exists.
This fixes it.

Fixed bug where output dir had to be absolute.

---

riscv/src/reachability.rs

Had two collections holding the same thing. Now have one.

Simplifying reachability.

---

riscv/src/compiler.rs
riscv/src/reachability.rs
riscv/tests/instruction_tests/generated/srai.S
riscv/tests/instruction_tests/sources/srai.S
riscv/tests/riscv_data/memfuncs/src/lib.rs

In order to activate the memcmp tests, `srai` needs to be implemented. It's implemented in powdr assembly, and not as a powdr instruction. Still in draft, as it needs more testing, but I am sharing it to ensure that this is the favored approach.

implement the srai instruction

---

riscv/tests/riscv.rs

Currently this is panicking at
```
running 1 test
error: manifest path `tests/riscv_data/print/Cargo.toml` does not exist
thread 'test_print' panicked at 'assertion failed: cargo_status.success()', riscv/src/lib.rs:187:5
```
Now it panics at
```
thread 'test_print' panicked at 'Unknown instruction: srai', riscv/src/reachability.rs:177:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
which I guess is not the intended behavior?

fix riscv print test

---

Cargo.toml
compiler/src/lib.rs
executor/src/witgen/bit_constraints.rs
executor/src/witgen/generator.rs
executor/src/witgen/machines/fixed_lookup_machine.rs
executor/src/witgen/mod.rs
executor/src/witgen/util.rs
halo2/Cargo.toml
halo2/src/circuit_builder.rs
halo2/src/circuit_data.rs
halo2/src/lib.rs
halo2/src/mock_prover.rs
number/src/lib.rs
number/src/macros.rs
number/src/serialize.rs
number/src/traits.rs
pil_analyzer/src/lib.rs
pilgen/src/lib.rs
powdr_cli/Cargo.toml
powdr_cli/src/main.rs
powdr_cli/src/util.rs

Extracted from the rest of https://github.com/chriseth/powdr/pull/102. The other PR got a bit too complicated to rebase onto main because of the amount of changes in the `main` branch and the merge commits into the feature branch.
The author credits are kept in this PR.
Notes from @Schaeff:
- the number of required extra rows is not trivial to calculate and seems to depend on the exact Halo2 configuration. Doubling the table size seems fine for this PR.
- This PR removes the wrapping behavior. This means that if this is merged, the first row is not constrained together with the last row. Moreover, witness generation does not use wrapping logic.
- This PR removes the requirement on the number of rows to be a power of two. This can be enforced by the backend instead: Halo2 just extends to …

halo2 backend

---

executor/src/witgen/machines/double_sorted_witness_machine.rs
riscv/runtime/src/allocator.rs
riscv/src/compiler.rs

Allows a large allocation heap by placing it last address-wise, avoiding a large address gap in the memory state machine when accessing stuff after the heap. Fixes issue #331.

Heap placement hack

---

Cargo.toml
backend/Cargo.toml
backend/src/lib.rs
compiler/Cargo.toml
compiler/src/backends.rs
compiler/src/lib.rs
compiler/src/util.rs
halo2/src/lib.rs
halo2/src/mock_prover.rs
halo2/src/prover.rs
powdr_cli/Cargo.toml
powdr_cli/src/main.rs

A previously generate params file can be passed to a prove command also.

Ad CLI `prove` and `setup` commands

---

Cargo.toml

kilic force pushed their fork which is under development and doesn't compile atm, so I forked their halo2 repo with the shuffles version that was working before

point to our halo2 fork for shuffles

---

compiler/src/lib.rs
compiler/src/verify.rs
powdr_cli/src/main.rs

Moved the CSV export inside the `pil` command. This way, the `--field` parameter only needs to be passed once.
Two other changes:
- I fixed the `prove` command (it would throw a runtime error because there are two `-t` flags...)
- In the CSV file, I also removed the `Assembly.` prefix from the column names for better readability
To test:
```bash
cargo run pil -f test_data/asm/simple_sum.asm -i 3,2,1,2 --export-csv
csvtool -u TAB namedcol Row,pc,A,CNT columns.csv | head
cargo run pil -f simple_sum.pil -i 3,2,1,2 --export-csv
```

Move CSV export to pil command

---

executor/src/witgen/machines/block_machine.rs
halo2/src/mock_prover.rs
test_data/asm/secondary_block_machine_add2.asm

Current witness generation for block machines fills empty blocks with zeros. Because all internal constraints are still checked on these blocks, this can lead to failing constraints.
With this PR, the first invocation of the block machine is recorded and used as the default block.

Block machine witness generation: Repeat first real block

---

compiler/src/lib.rs
executor/Cargo.toml
executor/src/witgen/eval_result.rs
executor/src/witgen/generator.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/machines/fixed_lookup_machine.rs
executor/src/witgen/machines/machine_extractor.rs
executor/src/witgen/mod.rs
executor/src/witgen/util.rs

I read and stepped through the witness generation code, very cool stuff!
On the way, I did some small refactorings, added comments, improved error messages and increased trace logging.
Some notable changes:
- A failed fixed lookup now reports the query
- In trace log level, it now reports how values are derived (for the main SM and block state machines)
- I was a bit worried about slowing the execution with trace logging, so I set `features = ["release_max_level_debug"]` in the `log` crate, so trace logging strings are never built in release mode
- Panics if not enough inputs are provided by the prover
- The looping period is detected using only the witness columns of the main SM
- If witness generation fails for a given row, it also prints the missing values of the previous row. In the …

Add logging to witness generation code

---

Cargo.toml
asm_utils/Cargo.toml
asm_utils/src/ast.rs
asm_utils/src/compiler.rs
asm_utils/src/data_parser.rs
asm_utils/src/lib.rs
asm_utils/src/parser.rs
asm_utils/src/reachability.rs
riscv/Cargo.toml
riscv/src/compiler.rs
riscv/src/disambiguator.rs
riscv/src/lib.rs
riscv/src/parser.rs
riscv/src/riscv_asm.lalrpop
riscv/tests/instructions.rs
riscv/tests/riscv.rs

This PR generalizes assembly handling to accommodate for additional architectures, using the existing riscv pipeline as the base. General assembly handling code is moved to the new `frontend-vm` crate and the elements specific to riscv are kept in the `riscv` crate.
closes #353

Generalize assembly handling

---

compiler/tests/pil.rs
halo2/src/circuit_builder.rs
halo2/src/circuit_data.rs
pil_analyzer/src/json_exporter/mod.rs
test_data/asm/secondary_block_machine_add2.asm
test_data/pil/constant_in_identity.pil

Fixes #397
There were two places were constants were not or incorrectly handled. This PR fixes those and adds test (both in ASM and PIL files) that ensure constants can be used in identities.

Fix using constants in identities

---

ast/src/analyzed/display.rs
ast/src/analyzed/mod.rs
ast/src/analyzed/util.rs
ast/src/parsed/mod.rs
executor/src/constant_evaluator/mod.rs
pil_analyzer/src/pil_analyzer.rs
pilopt/src/lib.rs

For example, if degree = 8, the following would currently fail:
```
col fixed foo = [1, 2, 3]*;
```
because 3 does not divide 8. This PR generalizes the behavior of `*` and would expand `foo` to `[1, 2, 3, 1, 2, 3, 1, 2]`.
Note that this might even truncate the list if it is longer than the remaining space.

Star operator: expand to arbitrary size

---

compiler/src/lib.rs
compiler/src/verify.rs
compiler/tests/pil.rs
powdr_cli/Cargo.toml
powdr_cli/src/main.rs

The CSV export was broken because it re-parsed the unoptimized PIL file. Now, the constants and witness values are bubbled up outside the compile functions and used directly to generate the CSV.
I also added a simple test case for the CLI code that should catch errors like this next time.

Fix CSV export

---

.github/workflows/nightly-tests.yml
.github/workflows/pr-tests.yml
Cargo.toml
backend/Cargo.toml
backend/src/lib.rs
compiler/Cargo.toml
compiler/src/lib.rs
compiler/tests/asm.rs
compiler/tests/pil.rs
powdr_cli/Cargo.toml
powdr_cli/src/main.rs

I didn't find wise to disable the warnings when building with no backends: it is a reminder that outputing Pilcom JSON is kind of a backend, but it currently doesn't share the same API as Halo2.

Enabling Halo2 via cargo feature.

---

riscv/runtime/src/coprocessors.rs
riscv/runtime/src/lib.rs
riscv/src/compiler.rs
riscv/src/lib.rs
riscv/tests/riscv_data/poseidon.rs

This PR implement a dummy `poseidon_hash` function, and substitutes it with a `poseidon` instruction in powdr assembly. This instruction is currently a stub that has to be replaced with a call to the actual poseidon coprocessor when #395 has been merged.
TODO:

Add the capability of replacing rust functions with coprocessor lookups

---

executor/src/witgen/affine_expression.rs
executor/src/witgen/machines/block_machine.rs
number/src/macros.rs
number/src/traits.rs

The Poseidon block machine performs many steps of computation in a given row. That currently isn't supported; the witness generation just does once pass over the identities for each row.
With this PR, things work similar to the main state machine: For each row, over all identities until no further progress was made.
The approach I went for is to implement a custom "iterator" that yields steps and receives a message whether or not any progress was made. Perhaps it can be used in the main state machine in the future!
In order to prevent infinite loops, I needed to make the notion of what is a progress stricter (e.g., if the given cell already had a value, that doesn't count as progress). That should also make the `ProcessingSequenceCache` more effective.

Block machine witness generation: allow for multiple passes per row

---

analysis/Cargo.toml
analysis/src/lib.rs
analysis/src/macro_expansion.rs
analysis/src/romgen.rs
analysis/src/type_check.rs
asm_to_pil/src/lib.rs
ast/src/asm_analysis/mod.rs
ast/src/object/display.rs
ast/src/object/mod.rs
ast/src/parsed/asm.rs
ast/src/parsed/build.rs
ast/src/parsed/display.rs
book/src/asm/machines.md
compiler/tests/asm.rs
linker/src/lib.rs
parser/src/powdr.lalrpop
riscv/src/compiler.rs
test_data/asm/book/simple_static.asm
test_data/asm/full_pil_constant.asm
test_data/asm/vm_to_block_multiple_interfaces.asm
test_data/asm/vm_to_block_unique_interface.asm

partially closes #381
Witness generation fails for machines whose functions have different interfaces:
```
// given
function foo x, y -> z {
}
// then this is ok
function bar x, y -> z {
}
// but this is not
function baz z, x, -> y {
}
```

Calls from VM to block machine whose functions share the same interface

---

asm_to_pil/src/lib.rs
ast/src/analyzed/mod.rs
executor/src/witgen/fixed_evaluator.rs
executor/src/witgen/generator.rs
executor/src/witgen/global_constraints.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/machines/machine_extractor.rs
executor/src/witgen/mod.rs
executor/src/witgen/symbolic_witness_evaluator.rs

Fixes #449
Global range constraints are now indexed by the *witness* polynomial ID (`PolyID`) instead of `&PolynomialReference`. This has the following consequences:
- There are no more range constraints for constant columns (should not be needed)
- The `next` flag is ignored (which was actually a bug, as described in the issue)
- The types are a lot simpler now (at the expense of not easily being able to print the polynomial's name anymore)

Simplify global range constraints

---

.github/workflows/nightly-tests.yml

Detect unused dependencies in our nightly builds
Kept two commits to demonstrate it works as expected, will squash if accepted.

Run `cargo udeps` on CI

---

ast/src/analyzed/mod.rs
executor/src/witgen/column_map.rs
executor/src/witgen/fixed_evaluator.rs
executor/src/witgen/generator.rs
executor/src/witgen/global_constraints.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/machines/double_sorted_witness_machine.rs
executor/src/witgen/machines/fixed_lookup_machine.rs
executor/src/witgen/machines/machine_extractor.rs
executor/src/witgen/machines/sorted_witness_machine.rs
executor/src/witgen/mod.rs
executor/src/witgen/symbolic_witness_evaluator.rs

Background:
- A `PolyID` is a polynomial type (committed or fixed) and a `u64`
- A `PolynomialReference` has a `PolyID`, a `next` flag, and a `name: String`
We had various places where we used a `&PolynomialReference` as a key to reference columns. This is semantically wrong and can lead to subtle bugs. I started refactoring this in #458.
In this PR, I tried to cover all places in witness generation where columns are being referenced. Some examples:
- A row often times used to be a `Vec<Option<T>>` where the index was `poly_id.id as usize`. I implemented a `ColumnMap` which encapsulates this behavior and implements `Index<&PolyID>`.
- BTW, I tried to use `BTreeMap<PolyID,, Option<T>>` instead, but that hurt performance
- Global range constraint computation now uses `PolyID` instead of …

Use `PolyID` instead of `PolynomialReference` or `usize`

---

.github/workflows/nightly-tests.yml
compiler/Cargo.toml
compiler/benches/executor_benchmark.rs
test_data/asm/keccak.asm

To make sure I'm not causing any performance regression in the upcoming refactoring PRs, I added some benchmarks. Witness generation for all non-panicking files in `test_data` are benchmarked. Additionally, I added a Keccak via RISC-V asm file, which is probably the best real-live example.
This benchmark currently lives in the `compiler` crate, as do the end-to-end tests. In the future, we should create a separate crate for end-to-end tests and benchmarks.
To test:
```
cd compiler
cargo bench
```
On my machine (virtual server, so exact numbers depend on the time of day...), I get these results:
```
executor-benchmarks/simple_sum.asm
time:   [9.6671 ms 10.068 ms 10.483 ms]
executor-benchmarks/palindrome.asm
time:   [17.373 ms 18.155 ms 18.964 ms] …
```

Add witness generation benchmarks

---

riscv/src/riscv_asm.lalrpop

It's currently difficult/impossible to share one larlpop grammer in multiple places while adding slight tweaks. This requires a change to larlpop like:
https://github.com/lalrpop/lalrpop/issues/42#issuecomment-288973232
We could fix this in the future by closing https://github.com/lalrpop/lalrpop/issues/42, or via some other means.

Documenting why making parsing generic at this moment might not be worthwhile

---

test_data/asm/poseidon_bn254.asm

Refactors the Poseidon example so that it lives in a separate block machine, so that @gballet can copy-paste it to use in the RISC-V VM.
Two notes on that:
- ~The `degree` field will need to changed so that it's the same as all other machines in the RISC-V VM~
- Since the `poseidon_permutation` function takes 3 inputs and returns 1 output, there will need to be an additional assignment register (which we can undo once #480 is implemented)

Refactor Poseidon example into its own machine

---

riscv/src/compiler.rs

In #398 a request for a code rewrite was made by @Schaeff , to improve readability. The PR was merged before I could make the suggestion to work, so here it is.

rewrite coprocessor substitution routine

---

asm_utils/src/ast.rs
asm_utils/src/data_parser.rs
riscv/src/compiler.rs

This is needed for rust evm with memory.
In fact it didn't really need a feature to be added, rather two bugs to be fixed.

Transpile assembly jump table properly

---

ast/src/analyzed/mod.rs
executor/src/witgen/column_map.rs
executor/src/witgen/eval_result.rs
executor/src/witgen/generator.rs
executor/src/witgen/identity_processor.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/mod.rs
executor/src/witgen/query_processor.rs
executor/src/witgen/rows.rs
executor/src/witgen/symbolic_witness_evaluator.rs
halo2/src/mock_prover.rs

This PR refactors the `Generator` type, which is responsible for witness generation of the main state machine. I pulled out the logic that computes and applies updates to a given pair of rows using a given identity. In a future PR (#457), we should be able to re-use these abstractions in the `BlockMachine`, which will allow us to remove a lot of code and more easily support features like sub-sub-machines.
The main machine witness generation algorithm can be summarized as follows:
- Repeat until no more progress:
- For identity in identities:
- Compute updates (assignments or range constraint updates) and apply them
- If all variables are known, remove identity
- For query in queries:
- Compute updates and apply them
- For all unknown cells, assume zero and check that all identities hold …

Refactor Main Machine Witness Generation

---

executor/src/witgen/generator.rs
executor/src/witgen/identity_processor.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/machines/double_sorted_witness_machine.rs
executor/src/witgen/machines/machine_extractor.rs
executor/src/witgen/machines/mod.rs
executor/src/witgen/machines/sorted_witness_machine.rs
executor/src/witgen/mod.rs
executor/src/witgen/rows.rs

With this PR, the list of all machines changes from `Vec<Box<dyn Machine<T>>>` to `Vec<KnownMachine<T>>` where `KnownMachine` is an enum listing all known machine types.
As a consequence, machines can have non-static lifetime parameters. This was the only reason for us to leak column names in #470, which can be removed now 🎉

Witgen: Use enums instead of `Box` to store machines

---

asm_utils/src/reachability.rs
riscv/src/compiler.rs
riscv/tests/instruction_tests/generated/lhu.S
riscv/tests/instruction_tests/sources/lhu.S

Implements `lhu` and adds the riscv test for it.
Two caveats:
1. Previously, the data reachability analyzer would remove data objects that are not directly referenced in the code. However, it's still possible to access such data objects via negative and positive offsets over directly referenced data. We could still have a similar pass also taking into account offsets, but that's more complex. Tracked in https://github.com/powdr-labs/powdr/issues/490.
2. We still don't have unaligned memory access, so the added assembly test was modified to use `.word` instead of `.half` and all offsets that are multiples of 2 are further multiplied by 2 to satisfy word alignment. There's one test that's commented out that has fully unaligned access (address + 7). We should revisit this file once unaligned …

Add lhu instruction and test

---

executor/src/witgen/machines/block_machine.rs
executor/src/witgen/rows.rs

Fixes some overly verbose trace logs introduced by #457.
It's a bit unfortunate that the logging now leaks into the `BlockMachine`, but I think the root of the problem is more that `RowUpdater` can't handle outer queries in the first place. I think in the future we might change that anyway and process the outer query just once in the beginning (to set input values) and once in the end (to write output values).

Reduce verbosity

---

.github/workflows/pr-tests.yml

The "Check benches compile without running them" step in the PR tests took up to 10 minutes and delayed the results of the tests.
I moved to the end of the release tests. Now test results are in faster, and also the step itself is faster, because benchmarks are compiled in release mode, so more computation can be shared.

CI: Move 'Check benches compile without running them'

---

executor/src/witgen/identity_processor.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/machines/double_sorted_witness_machine.rs
executor/src/witgen/machines/fixed_lookup_machine.rs
executor/src/witgen/machines/mod.rs
executor/src/witgen/machines/sorted_witness_machine.rs
executor/src/witgen/sequence_iterator.rs

In `Machine::process_lookup`, changes `left: &[AffineResult<&'a PolynomialReference, T>]` to `left: &[AffineExpression<&'a PolynomialReference, T>]`, since called machines cannot do anything anyway any expression on the LHS isn't an affine expression. This simplifies the code a bit.

Refactor Witgen call interface

---

executor/src/witgen/machines/fixed_lookup_machine.rs
executor/src/witgen/machines/machine_extractor.rs
executor/src/witgen/mod.rs
executor/src/witgen/processor.rs

Adds a simple unit test to `Processor`. The main point is to get the boilerplate code out of the way, so it can be tested as we add more features.

Add unit test to Processor

---

executor/src/witgen/machines/block_machine.rs
executor/src/witgen/processor.rs
test_data/asm/poseidon_bn254.asm

Improves the error message of the `Processor` in the case of an `EvalError`.
The `Processor` is only used to fix the last row of the block machine, so because of #548, you can trigger this by commenting all invocations of `poseidon` in `poseidon_bn254.asm` and running:
`cargo run pil test_data/asm/poseidon_bn254.asm -f -o output`
This now prints the following error:
```
Filling empty blocks with zeros, because the block machine is never used. This might violate some internal constraints.
Detected error in last row! Will attempt to fix it now.
Error in identity: main_poseidon.a0 = (main_poseidon.in0 + main_poseidon.C_0);
Known values in current row (local: 0, global 1022):
main_poseidon.function_id = 0
main_poseidon.in0 = 0
main_poseidon.in1 = 0
main_poseidon.cap = 0 …
```

Witgen: Improve error messages

---

riscv/Cargo.toml
riscv/src/lib.rs
riscv/tests/riscv.rs

So that we can avoid rebuilding everything always.
It is also easier to debug, as we can keep the files output by cargo build.

Keeping cargo target directory

---

compiler/benches/executor_benchmark.rs

This was caused by an interference of #530 and #547.
I'm not sure why the "Check benches compile without running them" step in the CI didn't catch it? It did when I ran it locally on `main`. Can branches be merged without being rebased to the most recent `main`?

Fix benchmark (again)

---

executor/src/witgen/machines/block_machine.rs
executor/src/witgen/processor.rs
executor/src/witgen/sequence_iterator.rs

A smaller, self-contained refactoring in preparation for #528.
**Background**: In witness generation, the `Processor` is an abstraction that implements the high-level solving algorithm (i.e., how to get from a list of identities to a unique witness). It is currently used only to handle an edge case in `BlockMachine` (where the witness might be different in the last line). In the future, it should be used in both `BlockMachine` (#527) and `Generator`.
This PR introduces the following changes:
- `DefaultSequenceIterator` now records the steps on which it made progress, so its user does not have to do it anymore.
- `Processor` now gets passed and uses a `ProcessingSequenceIterator`. This reduces the complexity of the processor's optimization loop and makes it more customizable (e.g. it can …

Processor: Use sequence iterator

---

executor/src/witgen/affine_expression.rs
executor/src/witgen/machines/sorted_witness_machine.rs

Affine expressions only rarely use the same variable multiple times. This means using a BTreeMap from the variable ID to the coefficient is overkill. I changed the code such that duplicates are only resolved when it is actually needed.
This makes keccak go from 2.4k rows/sec to 3.0k rows/sec

Lazy affine expression

---

Cargo.toml

Note that the halo2 dependency is still disabled through a feature.
The idea here is that the CLI depends on all crates anyway. So the only effect of the `default-members` property here is that `cargo test` only runs the cli tests, which is hardly what we want.

Compile and test all crates by default.

---

executor/src/witgen/affine_expression.rs

This bug has been with us since the existence of `AffineExpression::assign()`! 🤯 
The reason it hasn't surfaced is because it's only used in `BlockMachine` to assign to `left_mut`, which is only done such that the same update is not computed multiple times (which would lead to an infinite loop). For that, it doesn't actually matter which value is being assigned. The bug caused an `EvalError`, but somehow the block machine code thought it can recover from it..

Bug fix in `AffineExpression::assign()`

---

compiler/tests/asm.rs
executor/src/witgen/generator.rs
executor/src/witgen/identity_processor.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/machines/machine_extractor.rs
executor/src/witgen/machines/mod.rs
executor/src/witgen/mod.rs
executor/src/witgen/processor.rs
executor/src/witgen/query_processor.rs

This PR is a step towards being able to do VM-to-VM witness generation:
- `Generator` now has an empty implementation of `Machine`
- Machine extraction instantiates any machine that can be called (i.e., no the main machine) and is not a machine of a different type as a `Generator` and adds it to the list of machines
- The moment the machine is actually called, things fail now with `unimplemented!()`.
Stopping there to keep the PR small. Also, the main machine is still instantiated and used exactly as before (which could change in the future).
This already forces `Generator` to work more like other machines (e.g. `BlockMachine`): Everything global that needs to be mutated (the list of sub machines, the fixed lookup and the query callback) can't be owned by `Generator` anymore. Instead it …

Witgen: Detect VM Submachines

---

ast/src/analyzed/display.rs
ast/src/analyzed/mod.rs
ast/src/analyzed/util.rs
ast/src/parsed/display.rs
ast/src/parsed/mod.rs
backend/src/pilcom_cli/json_exporter/mod.rs
compiler/src/lib.rs
compiler/tests/asm.rs
executor/src/constant_evaluator/mod.rs
pil_analyzer/src/pil_analyzer.rs
pilopt/src/lib.rs
test_data/asm/intermediate.asm
test_data/asm/intermediate_nested.asm

- this reuses `FunctionDefinition` with a new variant to encode `col intermediate = e`
- it fails in witgen, to be fixed separately

Support intermediate polynomials

---

ast/src/parsed/asm.rs
importer/src/path_canonicalizer.rs

Removes `derive(Clone)` on the parse tree and operates over references in the importer. Paths are still cloned but not entire modules.

Avoid cloning in importer

---

book/src/pil/README.md

It seems that the link to Polygon's PIL documentation is outdated. It redirects to the main Polygon zkEVM docs site. Updated the link to point to the right URL.

docs: fix link to Polygon's PIL docs

---

analysis/src/macro_expansion.rs
asm_to_pil/src/romgen.rs
asm_to_pil/src/vm_to_constrained.rs
ast/src/analyzed/display.rs
ast/src/analyzed/mod.rs
ast/src/analyzed/util.rs
ast/src/asm_analysis/utils.rs
ast/src/parsed/display.rs
ast/src/parsed/mod.rs
ast/src/parsed/utils.rs
backend/src/pilcom_cli/json_exporter/mod.rs
executor/src/constant_evaluator/mod.rs
executor/src/witgen/expression_evaluator.rs
executor/src/witgen/machines/double_sorted_witness_machine.rs
executor/src/witgen/machines/machine_extractor.rs
executor/src/witgen/machines/sorted_witness_machine.rs
executor/src/witgen/query_processor.rs
executor/src/witgen/util.rs
halo2/src/circuit_builder.rs
parser/src/powdr.lalrpop
pil_analyzer/src/pil_analyzer.rs
pilopt/src/lib.rs

closes #597
We had tons of code duplication (display, visitor, etc) because we had almost exactly the same ast for both the parsed and the analyzed expressions.
This combines it and introduces generic parameters for the differences.
This PR can be seen as just a stepping stone, I would like to simplify it further, so that expressions are generic enough to fit the needs for all expressions that arise in powdr.
This does not mean it will stay exactly like this, thibaut and me discussed some ideas to make it more flexible but also more type-safe at the same time.

Unify parsed and analyzed expressions

---

.github/workflows/pr-tests.yml

Except for the one that tests a different feature, obviously.
This should speedup the run a little.

Using same feature set for all cargo commands in checks.

---

executor/src/witgen/machines/block_machine.rs
executor/src/witgen/processor.rs
executor/src/witgen/rows.rs

A refactoring with essentially two changes:
- Implements handling outer queries in `Processor::solve`
- Uses `Processor` in `BlockMachine::process_lookup`, allowing us to remove a significant amount of code

Use `Processor` in `BlockMachine`

---

compiler/benches/executor_benchmark.rs
number/src/lib.rs
number/src/macros.rs
number/src/traits.rs
riscv/src/compiler.rs
riscv/src/lib.rs
riscv/tests/instructions.rs
riscv/tests/riscv.rs

In the RISC-V compiler, we need a way to distinguish between the field we're compiling the VM for. For example, we might include different Poseidon or Wrapping VMs depending on the field.
This small refactoring prepares this by introducing a `FieldElement::known_field()` function which can be used like this in the futue:
```rust
pub fn machine_decls<T: FieldElement>() -> Vec<&'static str> {
match T::known_field().expect("Expected known field") {
KnownField::Bn254Field => todo!(),  // Include BN254-specific machines
KnownField::GoldilocksField => todo!(),  // include Goldilocks-specific machines
}
```

Allow for field-specific code in RISC-V compiler

---

executor/src/witgen/machines/block_machine.rs
executor/src/witgen/processor.rs
executor/src/witgen/rows.rs
test_data/asm/secondary_block_machine_add2.asm

An alternative solution to the problem #503 tried to solve.
When compiling a block machine from Powdr ASM, this introduces a witness polynomial `_operation_id_no_change` constrained as:
`_operation_id_no_change = ((1 - _block_enforcer_last_step) * (1 - <Latch>))`
This is a problem, because block machines fill up unused rows by copy-pasting a default block, which will have `_operation_id_no_change = 1` in all rows but its last, so if the block size does not divide the degree, `_operation_id_no_change` does not fulfill the constraints in the last row.
#503 solved this by:
1. Detecting that this is the case
2. Removing row $n - 1$ and computing it again, using rows $n - 2$ and $0$ as context.
When working on #625, I noticed that `test_data/asm/poseidon_gl_test.asm` fails if the degree is set …

Block Machine Witgen: Handle last row differently

---

riscv/src/compiler.rs
riscv/src/riscv_asm.lalrpop
riscv/tests/instruction_tests/generated/lh.S
riscv/tests/instruction_tests/sources/lh.S

Dismembered from PR #553.
Built upon PR #617 because it changes `riscv_asm.larlpop` and #617 fixes the larlpop build.

lh instruction

---

compiler/tests/asm.rs
executor/src/witgen/generator.rs
executor/src/witgen/identity_processor.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/machines/double_sorted_witness_machine.rs
executor/src/witgen/machines/machine_extractor.rs
executor/src/witgen/machines/mod.rs
executor/src/witgen/machines/sorted_witness_machine.rs
executor/src/witgen/mod.rs
executor/src/witgen/processor.rs
test_data/asm/vm_to_block_to_block.asm

With this PR, witness generation is able to generate witnesses for block machines which call other block machines.
The required changes are:
- Some changes in machine detection to actually detect the machines properly in this case
- `IdentityProcessor` now holds a `Vec<&mut KnownMachine<'a, T>>` instead of `machines: Vec<KnownMachine<'a, T>>`, wrapped in a new type.
- When a sub-machine is called, the current machine is removed from the vector of machines and the other machines are passes to the callee. This way, a machine can call other machines, but there can't be any cycles. With #515 implemented, cycles can be supported and the code can be simplified.
Note that this creates a new (small) vector of mutable references of machines for each row (this can change once `Generator` computes …

Witgen: Handle Block-to-Block calls

---

analysis/src/vm/inference.rs
asm_to_pil/src/lib.rs
asm_to_pil/src/vm_to_constrained.rs
ast/src/asm_analysis/display.rs
ast/src/asm_analysis/mod.rs
ast/src/parsed/asm.rs
ast/src/parsed/display.rs
book/src/asm/functions.md
compiler/tests/asm.rs
parser/src/powdr.lalrpop
test_data/asm/book/function.asm
test_data/asm/multi_return.asm
test_data/asm/multi_return_wrong_assignment_register_length.asm
test_data/asm/multi_return_wrong_assignment_registers.asm
type_check/src/lib.rs

Allows an instruction to return more than one field element, see example in the new `multi_return` test.

Implement Multi-return

---

ast/src/analyzed/display.rs
ast/src/analyzed/mod.rs
backend/src/pilstark/json_exporter/expression_counter.rs
backend/src/pilstark/json_exporter/mod.rs
compiler/src/util.rs
executor/src/constant_evaluator/mod.rs
executor/src/witgen/query_processor.rs
pil_analyzer/Cargo.toml
pil_analyzer/src/pil_analyzer.rs

This is a first step towards fully integrating `let` declarations, where the actual kind of declaration is determined from the type.
As a next step, I will remove the special handling of constants (constant numbers, not fixed columns), so that the Analyzed struct is just a collection of definitions and identities.

Generalize definitions.

---

riscv/src/compiler.rs
riscv/tests/instruction_tests/generated/amoadd_w.S
riscv/tests/instruction_tests/sources/amoadd_w.S

Dismembered from PR #553.
Built upon PR #619 because the test file contains 64-bit hex literals, and #619 fixes parsing of 64-bit hex literals.

amoadd.w instruction

---

compiler/tests/pil.rs
executor/src/witgen/generator.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/mod.rs
executor/src/witgen/processor.rs
executor/src/witgen/rows.rs

During debugging Leo's multiplexer block machine (leading to the fixes in #651), I improved the logging & error reporting, specifically:
- When a machine prints a row, it only includes the columns of the current machine (all others will be unknown anyway)
- In the main machine, when we are finalizing a row, we fail if any lookup identity has not been completed, with a better error message. Previously, it would try to validate the identity (assuming 0 for unknown values), but because the block machine has no concept of this strategy, it would lead to random error messages.
- We now detect a name for the block machine to include in the log messages.
- If it happens multiple times that we detect a loop but then the constraints are not valid, we only log that once in the "info" level, and …

Improve logging & error reporting in witness generation

---

compiler/tests/asm.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/processor.rs
executor/src/witgen/sequence_iterator.rs
test_data/asm/block_machine_cache_miss.asm

This PR fixes two bugs:
1. We always inferred block machine witnesses always as if the block started at row `block_size - 1`. This works only if constant columns are the same for each block, which is not always the case.
2. The block machine uses a cache to store the computation steps (which identity is processed in which row) that actually lead to progress and uses this sequence for subsequent calls. This fails if the required sequence depends on the input (for example the operation ID) or any non-periodic constant columns. With this PR, this case is detected and the witgen procedure is repeated with the default strategy. This way, witgen will be slower in these cases, but it will succeed. I added a test that provokes this case.

Bug fixes in block machine witness generation

---

executor/src/witgen/generator.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/machines/machine_extractor.rs
executor/src/witgen/mod.rs
executor/src/witgen/rows.rs

A refactoring that changes the interface of `Generator`: Instead of `compute_next_row()`, `propose_next_row()`, etc, it just exposes a `run()` method. This makes the interface of `Generator` more similar to `Machine::process_lookup()` (which is a step towards supporting VM-to-VM witgen), and simplifies code.
The major changes are:
- Instead of owning single rows, `Generator` now owns the entire data, similar to `BlockMachine`. Like any other machine, the data gets exposed via `Machine::take_witness_col_values()`.
- As a consequence, loop detection is moving inside the new `Generator::run()` method.
- The `update_first_row()` mechanism from #555 could be removed, because `Generator` is now aware of the wrapping.

Generator: Compute block instead of rows

---

executor/src/witgen/generator.rs
executor/src/witgen/mod.rs
executor/src/witgen/vm_processor.rs

This PR introduces a new type `VmProcessor` (very similar to the existing `Processor`, might be unified in the future) that does all the work to produce a valid block of a VM. The diff is big, but 99% of the code in `VmProcessor` is moved from `Generator`, so I recommend viewing the diff between the old `Generator` and `VmProcessor`.
To provide more context, these are the steps I'm planning:
1. With this PR, the `Generator` does barely anything, as there will always only be one block, because of the "sigma" logic Thibaut implemented to force the `operation_id` to point to the infinite loop.
2. I think the next step could be to remove the "sigma" logic. Then, the `operation_id` is unconstrained after the first return, in which case the prover (i.e., witness generation) can choose the …

Witgen: Extract block production from Generator into VmProcessor

---

ast/src/analyzed/visitor.rs
ast/src/asm_analysis/mod.rs
ast/src/parsed/visitor.rs

This makes the ExpressionVisitable trait generic over the expression type itself.
It allows us to introduce a new expression type without having to modify the more generic types like SelectedExpression etc.

Change expression visitor to be more flexible.

---

asm_to_pil/src/romgen.rs
linker/src/lib.rs

Depends on #674
This PR removes the `_sigma` columns Thibaut introduced for the main VM in #674.
The purpose of these extra constraints was to make sure witness generation finds a unique witness after the main function returns. This was done by constraining `_operation_id` to be equal to the default function (an infinite loop) that can be used to fill up unused rows.
However, these constraints are not necessary for soundness: The prover is anyway forced to correctly complete the main function. After that, the execution trace does not matter, we only need a way not to violate any constraints.
With #674, witness generation is aware of this can sets the operation ID to the default function even though no constraint enforces that. Therefore, this can now be removed.

Remove `_sigma` logic

---

executor/src/constant_evaluator/mod.rs
pil_analyzer/src/evaluator.rs
pil_analyzer/src/lib.rs
pil_analyzer/src/pil_analyzer.rs

Also part of #647 
The purpose of this PR is to isolate two components: The expression evaluator and the expression processor.
The former was previously present both in the constant_evaluator and the pil_analyzer. In the pil_analyzer it evaluated parsed expressions, in the constant_evaluator it evaluated analyzed expressions.
Since the analyzed expressions will be closer to what in the future will be type-enriched expressions, I switched it over to that, since it is will not be possible in the future to evaluate expressions of unknown type.
The expression processor was extracted from the pil_analyzer to better separate mutable state: The mutable state in the expression processor is just the list of local function parameters. In the pil_analyzer, the mutable state is mostly the list of …

Extract evaluator and processor.

---

importer/src/path_canonicalizer.rs
importer/test_data/cycle.asm
importer/test_data/import_after_usage.asm
importer/test_data/import_after_usage.expected.asm

Detect cases of the form
```
use module::Machine;
mod module {
use super::Machine;
}
```
Note that this does not cover #662, which is unrelated to the import system, but rather related to recursive data structures.
I simplified the canonicalizer to rely on single absolute paths instead of tuples.

Detect circular dependency in use statements

---

executor/src/witgen/generator.rs
executor/src/witgen/processor.rs
executor/src/witgen/rows.rs
executor/src/witgen/sequence_iterator.rs
executor/src/witgen/symbolic_witness_evaluator.rs
executor/src/witgen/vm_processor.rs

This refactor pulls out the wrapping handling out of `VmProcessor`. Instead, `Generator` explicitly computes the first row (by running identities on the (degree - 1, 0) row pair), runs the `VmProcessor` to compute `<degree + 1>` rows, and then explicitly stitches together rows `<degree>` and `0`.
The reasoning behind this is as follows: In the future, `VmProcessor` won't have access to all rows, because it will only be responsible for a single block (e.g. a single call to the machine). So, it won't be able to handle wrapping. Right now, because of the `_sigma` logic (after the main function returns, a constraint enforces that the operation ID points to the infinite loop), there is only one massive block. #674 relaxes this and #677 removes the `_sigma` logic.

Witgen Refactoring: Pull out wrapping handling into Generator

---

ast/src/analyzed/mod.rs
ast/src/analyzed/visitor.rs
pil_analyzer/src/pil_analyzer.rs
pilopt/src/lib.rs

Since we will have two different expression types for identities and for definitions, we need to split the visitor implementation for Analyzed into two different functions taking two different expression types.
This is a preparatory pull request that does not yet change the expression types, but introduces two different visit functions.

Prepare expression split

---

executor/src/witgen/generator.rs
executor/src/witgen/identity_processor.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/machines/double_sorted_witness_machine.rs
executor/src/witgen/machines/mod.rs
executor/src/witgen/machines/sorted_witness_machine.rs
executor/src/witgen/mod.rs

Most machines that need access to a `FixedData` reference already store it in `self`, so there is no need to pass it in `Machine::process_lookup()` and `Machine::take_witness_col_values()`.

Remove fixed data from machine functions

---

compiler/src/lib.rs
halo2/src/mock_prover.rs

With this, we can replace the `_sigma` logic with something like:
`col witness _operation_id(i) query ("hint", <default operation ID>);`

Implement hint query

---

ast/src/analyzed/display.rs
ast/src/analyzed/mod.rs
backend/Cargo.toml
backend/src/pilstark/json_exporter/expression_counter.rs
backend/src/pilstark/json_exporter/mod.rs
executor/src/constant_evaluator/mod.rs
pil_analyzer/src/condenser.rs
pil_analyzer/src/evaluator.rs
pil_analyzer/src/pil_analyzer.rs
pilopt/src/lib.rs

This is needed because in the future, the values of intermediate columns need to be "simple expressions".

Treat intermediate columns specially.

---

executor/src/witgen/eval_result.rs
executor/src/witgen/machines/double_sorted_witness_machine.rs

This fixes an issue in #706, where the address argument to the memory operation is no longer known when the lookup is being processed.
In that case, the `DoubleSortedWitnesses` failed hard. Instead, it should just return an "incomplete" `EvalValue`, just as it does when the value is not yet set.
I introduced a new `IncompleteCause::NonConstantRequiredArgument(&'static str)` which is used for both cases.

Memory machine witgen: Handle unknown address

---

compiler/benches/executor_benchmark.rs
compiler/src/lib.rs
compiler/tests/pil.rs
executor/src/witgen/generator.rs
executor/src/witgen/identity_processor.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/machines/double_sorted_witness_machine.rs
executor/src/witgen/machines/mod.rs
executor/src/witgen/machines/sorted_witness_machine.rs
executor/src/witgen/mod.rs
executor/src/witgen/processor.rs
executor/src/witgen/vm_processor.rs
halo2/src/mock_prover.rs

With this PR, `Machine::process_lookup()` receives a `&mut MutableState`, instead of separate mutable references to `fixed_lookup` and `machines`. This means that secondary machines now also have access to the query callback!
Lifetimes get a little complicated, but this the rough idea:
- Machines receive a `&mut MutableState`, which itself holds mutable references:
- `fixed_lookup: & mut FixedLookup`: The "special" fixed lookup machine
- `machines: Machines` (which is essentially a `Vec<&mut KnownMachine>`): all other secondary machines
- `query_callback: &mut QueryCallback`: The query callback
- When the `IdentityProcessor` calls another machine, it creates a new `MutableState` which:
- Re-borrows `fixed_lookup` & `query_callback` (with a lifetime shorter than the original one, only for …

`Machine` trait: pass through entire `MutableState`

---

airgen/src/lib.rs
analysis/src/block_enforcer.rs
asm_to_pil/src/romgen.rs
ast/src/object/display.rs
ast/src/object/mod.rs
ast/src/parsed/asm.rs
ast/src/parsed/display.rs
book/src/asm/machines.md
compiler/tests/asm.rs
linker/src/lib.rs
parser/src/powdr.lalrpop
test_data/asm/empty.asm
test_data/asm/full_pil_constant.asm
test_data/asm/single_operation.asm
type_check/src/lib.rs

Optional latch and operation_id

---

executor/src/constant_evaluator/mod.rs
pil_analyzer/src/condenser.rs
pil_analyzer/src/evaluator.rs
pil_analyzer/src/pil_analyzer.rs

An intermediate column is a witness column, so should not be referenced here.

Do not allow reference to intermediate columns for fixed evaluation.

---

riscv/src/compiler.rs

one of the latest mstore/mload messed this up, apparently we have no tests for this :upside_down_face:

fix riscv asm

---

riscv/Cargo.toml
riscv/src/compiler.rs
riscv/tests/riscv.rs
riscv/tests/riscv_data/evm/src/lib.rs
std/binary.asm
std/shift.asm

This PR:
- fixes the EVM test by executing the tx after setting it up
- changes the EVM test to receive the program's bytecode via prover input instead of hardcoded
- removes `degree` statements from std machines
- changes the riscv compiler to auto detect the degree needed by the program

Improve EVM test

---

compiler/tests/asm.rs
compiler/tests/pil.rs
executor/src/witgen/block_processor.rs
executor/src/witgen/data_structures/finalizable_data.rs
executor/src/witgen/generator.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/machines/double_sorted_witness_machine.rs
executor/src/witgen/machines/mod.rs
executor/src/witgen/machines/sorted_witness_machine.rs
executor/src/witgen/mod.rs
executor/src/witgen/query_processor.rs
executor/src/witgen/rows.rs
executor/src/witgen/vm_processor.rs
test_data/asm/vm_to_vm.asm
test_data/asm/vm_to_vm_dynamic_trace_length.asm
test_data/asm/vm_to_vm_to_block.asm
test_data/asm/vm_to_vm_to_vm.asm

This PR adds automatic witness generation for secondary VMs.
The main changes are:
1. `Generator` now implements `process_lookup()`.
2. `VmProcessor` can now handle outer queries.
3. `VmProcessor` also has a way to handle inputs passed via the outer query.
Change (2) mostly involved copying code from `Processor`, which already implements the functionality.  The amount of code duplication is now very high between the two, but I'd suggest to fix that in an upcoming refactoring PR. The two processors are now feature-complete, so now is a good to evaluate if they can be merged or otherwise share code.
Change (3) is probably the most novel code. Handling inputs works as follows:
- When a query is processed `VmProcessor` remembers any values assigned to simple polynomials via the lookup.
- When …

VM-to-VM witgen

---

executor/src/witgen/block_processor.rs
executor/src/witgen/generator.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/mod.rs
executor/src/witgen/processor.rs
executor/src/witgen/vm_processor.rs

Second step towards #737, builds on #736.
Introduces a new `Processor` that is used by `BlockProcessor`. In the future, we should be able to use it in `VmProcessor` as well. All the code is moved without any changes.

(2) Separate out `Processor` from `BlockProcessor`

---

compiler/src/lib.rs
compiler/src/verify.rs
compiler/tests/asm.rs
compiler/tests/pil.rs
compiler/tests/powdr_std.rs
number/Cargo.toml
number/src/lib.rs
number/src/serialize.rs
powdr_cli/src/main.rs

This PR changes:
- The currently custom-written CSV exporter has been rewritten. It now lives in `number::write_polys_csv_file` (analogous to `number::write_polys_file`) and uses the `csv` crate
- One feature I removed is that common prefixes are removed. This is for compatibility with the read method; we want to preserve the full column names.
- I recommend [this viewer](https://gist.github.com/georgwiese/af06566dd187533b16cd90b590492bfd), which deals nicely with the slightly longer names.
- Added a `number::read_polys_csv_file`, with a test that the two are compatible.
- Added an `--witness-values` argument to the `pil` command that allows us to pass a CSV file with externally-computed witnesses to use during witness generation.
To test:
```bash
cargo run pil …
```

Enable passing externally-generated witness via command line

---

powdr_cli/src/main.rs

The backends themselves already do the degree computation from the entire length internally, so what we should pass here is the trace length and not the log. Not sure why we didn't catch this earlier. The tests are still passing because only CLI is affected.

Fix degree passing in CLI

---

backend/src/halo2_impl.rs
backend/src/lib.rs
backend/src/pilstark/estark.rs
backend/src/pilstark/mod.rs
compiler/src/lib.rs
compiler/src/util.rs
compiler/src/verify.rs
compiler/tests/pil.rs
halo2/src/circuit_builder.rs
halo2/src/circuit_data.rs
halo2/src/mock_prover.rs
halo2/src/prover.rs
number/src/serialize.rs
powdr_cli/src/main.rs

This PR moves *almost* all FS operations out of the `compiler` crate. PIL and ASM files are still output by that crate, but I decided to leave it to a different PR.
The main motivation to stop writing witnesses and proofs directly in `compiler` is that that's something the client should do. In fact, the client may not even want to write them to disk yet, and do some sort of continuations or aggregation. Currently the main client is the CLI crate, who does write them to disk. It's also important to keep this separated because the compiler only knew about one witness and one proof, but with continuations we will have more and that's something the compiler should not be concerned about. PIL and ASM files are fine to stay there for now because they are always a single artifact.

compiler cleanup

---

analysis/src/macro_expansion.rs
asm_to_pil/src/romgen.rs
asm_to_pil/src/vm_to_constrained.rs
ast/src/analyzed/display.rs
ast/src/analyzed/mod.rs
ast/src/asm_analysis/mod.rs
ast/src/parsed/build.rs
ast/src/parsed/display.rs
ast/src/parsed/mod.rs
ast/src/parsed/visitor.rs
backend/src/pilstark/json_exporter/mod.rs
executor/src/witgen/query_processor.rs
parser/src/lib.rs
parser/src/powdr.lalrpop
pil_analyzer/src/condenser.rs
pil_analyzer/src/evaluator.rs
pil_analyzer/src/pil_analyzer.rs
pilopt/src/lib.rs

Depends on #733 
This turns index access into a proper operator that can be applied everywhere, not just right after a symbol.

Parse index access as operator.

---

ast/src/analyzed/mod.rs
backend/src/pilstark/estark.rs
compiler/benches/executor_benchmark.rs
compiler/src/lib.rs
compiler/src/verify.rs
executor/src/constant_evaluator/mod.rs
executor/src/witgen/block_processor.rs
executor/src/witgen/global_constraints.rs
executor/src/witgen/mod.rs
halo2/src/circuit_data.rs
halo2/src/mock_prover.rs
halo2/src/prover.rs
number/src/serialize.rs
pil_analyzer/src/condenser.rs
pil_analyzer/src/pil_analyzer.rs
test_data/asm/empty.asm
test_data/asm/single_operation.asm

We currently get the degree of the table from the length of the first constant column. This creates a hard requirement of having at least one constant column. This PR removes this requirement by getting the length of the table from the degree of the namespaces: they must all match (which is already a requirement now).
I ended up simplifying code in a few places where the degree was passed around, as it is now accessible directly from `Analyzed`.

Get degree from namespaces

---

.github/workflows/pr-tests.yml

So that if they fail, they save waiting time.

Placing faster checks first.

---

ast/src/analyzed/display.rs
ast/src/analyzed/mod.rs
backend/src/pilstark/json_exporter/mod.rs
compiler/src/util.rs
compiler/tests/pil.rs
executor/src/witgen/mod.rs
executor/src/witgen/query_processor.rs
executor/src/witgen/util.rs
halo2/src/circuit_builder.rs
halo2/src/mock_prover.rs
number/src/serialize.rs
pil_analyzer/src/condenser.rs
pil_analyzer/src/pil_analyzer.rs
pilopt/src/lib.rs
test_data/pil/fib_arrays.pil

This removes `index` from AlgebraicReference and instead stores the index as an offset inside the poly ID (we already left gaps in the IDs for arrays). In the end, witgen does not care if two columns are defined as elements of the same array or not.

Witgen for arrays

---

riscv/src/compiler.rs

Execution result report was being skipped in case there was no reservation.

Regression: fixing instruction sc.w

---

executor/src/witgen/block_processor.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/processor.rs

Third step towards #737, builds on #738.
Getting rid of the complicated distinction between a (Block)Processor with and without an outer query. Now, it works more similar to the `VmProcessor`:
- `BlockProcessor::solve()` now returns an `EvalValue` (similar to `VmProcessor::run`), which encodes whether the outer query has been completed or not (= all values on the LHS are known)
- This removes the need for `BlockProcessor::finish()` to return the LHS of the outer query.
Note that this actually changes the block machine processing: If the block machine has not completed, but has updates for the caller, they are now returned.

(3) Simplify processors

---

riscv/src/compiler.rs

In our label based implementation, `tail` should actually be identical to jump.

Removing `tail` instruction.

---

riscv/runtime/src/allocator.rs

This may save some cycles of zeroing already zeroed memory.

Providing alloc_zeroed instead of using default implementation.

---

parser/src/powdr.lalrpop

This special case is needed because `||` is parsed as `logical or`.

Allow lambda expression without parameters.

---

compiler/src/lib.rs
compiler/tests/pil.rs
executor/src/witgen/block_processor.rs
executor/src/witgen/eval_result.rs
executor/src/witgen/mod.rs
executor/src/witgen/processor.rs
executor/src/witgen/query_processor.rs
executor/src/witgen/vm_processor.rs
halo2/src/mock_prover.rs

This removes the option for the prover to say "I don't know". If it does not answer, this will result in a failure. Do we want that?
Thinking about it, we kind of need the option to say "I don't know": In the case where there is no free input, it is probably better to go with "no assignment" than assigning a random value.

Allow prover query to return error.

---

compiler/src/verify.rs
compiler/tests/asm.rs
compiler/tests/powdr_std.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/machines/machine_extractor.rs
executor/src/witgen/machines/mod.rs
executor/src/witgen/machines/write_once_memory.rs
riscv/tests/riscv.rs
test_data/asm/mem_write_once.asm
test_data/asm/mem_write_once_external_write.asm

Adds witgen support for write-once memory, e.g.:
```
let ADDR = |i| i;
let v;
// Loads a value. If the cell is empty, the prover can choose a value.
instr mload X -> Y { {X, Y} in {ADDR, v} }
// Loads a value. If the cell is empty, the prover can choose a value.
instr mload X -> Y { {X, Y} in {ADDR, v} }
```
It's implemented as a new `Machine`.
When used in conjunction with external witness generation (passing the memory content), this primitive can be seen as a way to pass prover inputs. Compared to passing them via queries (e.g. `${ ("input", 0) }`), the program can ask for the same index several times and be guaranteed to receive the same value.

Write-Once Memory

---

analysis/src/macro_expansion.rs
analysis/src/vm/inference.rs
asm_to_pil/src/vm_to_constrained.rs
ast/src/parsed/display.rs
ast/src/parsed/folder.rs
ast/src/parsed/mod.rs
ast/src/parsed/visitor.rs
parser/src/powdr.lalrpop
pil_analyzer/src/condenser.rs
pil_analyzer/src/evaluator.rs
pil_analyzer/src/pil_analyzer.rs
riscv_executor/src/lib.rs

Before this PR, the function part of a function call (`<function>(<arguments>)`) only allowed an explicit string. This change allows terms, i.e. you can do things like `x[0](7)` or `(|i| i + 1)(8)` and all the other fun stuff you could expect from a language.
Fixes https://github.com/powdr-labs/powdr/issues/367
Depends on #776

Allow arbitrary expressions to be function-called.

---

pil_analyzer/src/expression_processor.rs
pil_analyzer/src/lib.rs
pil_analyzer/src/pil_analyzer.rs

Extracts the expression processor into its own file with no changes.
Also abstracts the interface to resolve name references to absolute names into a trait.

Extract expression processor.

---

pil_analyzer/src/expression_processor.rs

This has proven to be the right way in the new evaluator.

Remove outdated todo.

---

riscv/src/compiler.rs

These were needed by `revme` which runs the Ethereum tests on revm.

More linking table entries

---

backend/Cargo.toml

their latest commit on main pushed some unstable features, so pinning to the last commit that worked, since the latest release is a few months old

pin starky

---

compiler/benches/executor_benchmark.rs
powdr_cli/src/main.rs
riscv/Cargo.toml
riscv/src/bootloader.rs
riscv/src/compiler.rs
riscv/src/lib.rs
riscv/tests/common/mod.rs
riscv/tests/instructions.rs
riscv/tests/riscv.rs
riscv_executor/src/lib.rs

Pulled this out of #789
This PR add an option to build the RISC-V machine with a bootloader, a small program that let's the prover initialize memory and registers. This is needed for continuations.
~For now, the bootloader is largely disabled and only included if a program is run using the `--just-execute` flag.~
The `with_bootloader` flag is always set to `false` in this PR, so there is no way to test this right now and this PR should just be code-reviewed. In #789, this will be exposed to the CLI.

Add Bootloader

---

pil_analyzer/src/evaluator.rs
pil_analyzer/src/expression_processor.rs
pil_analyzer/src/pil_analyzer.rs

Previously, all constants were always in the global scope, no matter where they are defined.
This changes the behaviour so that only constants whose names start with `%` are in the global namespace.
It also abstracts namespace access.

Unify namespaces wrt constants.

---

riscv_executor/src/lib.rs
riscv_executor/src/poseidon_gl.rs

Implements the `poseidon_gl` and `split_gl` instructions on the RISC-V executor.
To test:
```
cargo run -r rust riscv/tests/riscv_data/poseidon_gl_via_coprocessor.rs -o output -f --coprocessors binary,shift,split_gl,poseidon_gl -j
```
Or, equivalently (which fails on main):
```
cargo test --all --all-features --profile pr-tests -- --ignored --exact test_poseidon_gl
```

RISC-V Executor: Implement poseidon_gl and split_gl

---

compiler/src/lib.rs
powdr_cli/src/main.rs
riscv/src/bootloader.rs
riscv/tests/riscv_data/many_chunks.rs
riscv_executor/src/lib.rs

Depends on #804
This PR implements continuations (in a non-sound way) as follows:
- When activated the bootloader added in #804 is added to the program
- A full execution trace is generated by running the RISC-V executor for an infinite number of steps
- Then, until all rows of the full trace are re-generated:
- The executor is run for `degree - 2` steps
- Assert that all rows are indeed the same as they were in the full trace
- The bootloader inputs for the next chunk are computes, which involves:
- Setting all registers to their last value in the previous chunk
- Finding out which memory pages will be accessed and paging those in using the bootloader
I tested this on two examples. The first one is added in this PR:
```bash
cargo run --release rust riscv/tests/riscv_data/many_chunks.rs …
```

Continuations Prototype

---

asm_to_pil/src/vm_to_constrained.rs
ast/src/parsed/display.rs
ast/src/parsed/folder.rs
ast/src/parsed/mod.rs
ast/src/parsed/visitor.rs
book/src/pil/expressions.md
executor/src/constant_evaluator/mod.rs
parser/src/powdr.lalrpop
pil_analyzer/src/evaluator.rs
pil_analyzer/src/expression_processor.rs
pil_analyzer/src/pil_analyzer.rs
riscv_executor/src/lib.rs

The `else` part is currently required. It does not make sense to skip the else part because we don't have statement lists as part of expressions yet.

Implement if expression.

---

ast/src/asm_analysis/mod.rs

I think just blindly deriving Clone, Eq and Ord is very misleading. IMO it is totally OK for basic data types but the more complicated the data gets, it gets less and less clear what it acutally means. If I have two local variables with the same ID and different names, are they the same or not? Are they even the same if they have the same local ID and local name, but used in different contexts?
Also providing Clone for a gigantic data structure like a whole ASM machine is not really useful. If there is a clone, then it should be reasonably expensive, or at least needed, I think.

Remove some unneeded (and misleading) derived implementations.

---

compiler/tests/pil.rs
executor/src/witgen/block_processor.rs
executor/src/witgen/generator.rs
executor/src/witgen/identity_processor.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/processor.rs
executor/src/witgen/vm_processor.rs

Fixes #737
Depends on #827
With this PR, the `VmProcessor` is now also using the `Processor` introduced in #738, which is already used by `BlockProcessor`:
```mermaid
graph LR
BlockProcessor --> Processor
VmProcessor --> Processor
```
This reduces code duplication between the two processors.
Changes:
- `Processor` no longer keeps a reference to the identities; instead `Processor::process_identity()` receives a reference to the identity
- Additional features of `Processor`:
- `Processor::process_identity()` also receives an `UnknownStrategy`
- `Processor::set_inputs_if_unset()` is moved from `VmProcessor`
- Some smaller stuff, like getting the number of rows or pushing new rows is exposed
- `VmProcessor` uses `Processor`, removes a bunch of code
Benchmark results:
``` …
```

(4) Use `Processor` by `VmProcessor`

---

compiler/src/pipeline.rs
compiler/src/test_util.rs
executor/src/witgen/mod.rs
halo2/src/mock_prover.rs
powdr_cli/src/main.rs

Applies the suggestion in [this comment](https://github.com/powdr-labs/powdr/pull/826#discussion_r1419183443). Now all (optional) arguments are supplied once in the beginning and then the pipeline is run. I think that's a more natural interface, especially in the presence of optional arguments.
For example, note how we don't have to supply external witnesses or prover inputs anymore if the PIL file doesn't require it:
```rust
let mut pipeline = Pipeline::<GoldilocksField>::default()
.from_file(resolve_test_file("pil/fibonacci.pil"))
.with_backend(BackendType::PilStarkCli);
// Advance to some stage (which might have side effects)
pipeline.advance_to(Stage::Proof).unwrap();
// Get the result
let proof = pipeline.proof().unwrap();
```

Pipeline: Refactor argument handling

---

.circleci/config.yml
.github/workflows/pr-tests.yml
backend/src/lib.rs
compiler/src/lib.rs
compiler/src/pipeline.rs
compiler/src/verify.rs
executor/src/witgen/mod.rs
powdr_cli/src/main.rs
riscv/Cargo.toml
riscv/src/continuations.rs
riscv/tests/riscv.rs
riscv/tests/riscv_data/many_chunks.rs

Depends on #834
Implements proving of continuation chunks:
- Renamed `rust_continuations` -> `rust_continuations_dry_run`, now returns bootloader inputs for each chunk
- Implemented a `chain_callback()` function and `Pipeline::add_callback()`. This allows us to add more than one callback.
- Note that with this approach, we might end up following many pointers, because there is one indirection for each chained callback. However, in #834, I didn't notice any performance issues switching from `QueryCallback<T>` to `Box<dyn QueryCallback<T>>`.
- Removed bootloader inputs from `compiler::inputs_to_query_callback`
- Instead, `riscv::continuations::rust_continuations()` now implements:
- Performing a dry run to collect all bootloader inputs
- For each chunk, adds the bootloader inputs to the …

Implement proving of continuations

---

compiler/src/pipeline.rs
compiler/src/test_util.rs
compiler/src/verify.rs
compiler/tests/asm.rs
compiler/tests/pil.rs
number/src/serialize.rs
powdr_cli/src/main.rs
riscv/src/continuations.rs
riscv/tests/riscv.rs

Fixes #836
Mainly a re-write of `powdr_cli/src/main.rs`, with some added functionality to the Powdr `Pipeline`.
The structure of `main.rs` is now the following:
```mermaid
graph TD
main --> run_command
run_command --> run_rust
run_command --> run_riscv_asm
run_command --> optimize_and_output
run_command --> run_pil
run_command --> read_and_prove
run_command --> setup
run_rust --> bind_cli_args
run_rust --> run
run_riscv_asm --> bind_cli_args
run_riscv_asm --> run
run_pil --> bind_cli_args
run_pil --> run
```
Most commands end up calling `run()`, which is quite powerful:
- It calls the executer if the `--just-execute` flag is active
- It includes / runs continuations if the `--continuations` flag is active
Also the `Pipeline` now handles all writes to the file system, including CSV export …

Refactor `main.rs`

---

compiler/src/pipeline.rs
compiler/src/test_util.rs
compiler/src/util.rs
compiler/src/verify.rs
powdr_cli/src/main.rs
riscv/src/continuations.rs

Fixes #839
Includes the name of the current file in all artifacts, not just the PIL files. This allows us to overwrite the name for continuations.
For example:
```
cargo run -r rust riscv/tests/riscv_data/many_chunks.rs \
-o output -f -c --coprocessors binary,shift,split_gl,poseidon_gl \
--prove-with pil-stark-cli --export-csv
```
Leads to the following files:
```
cargo_target                                                    many_chunks_chunk_1_commits.bin
many_chunks.asm                                                 many_chunks_chunk_1_constants.bin
many_chunks_chunk_0.pil                                         many_chunks_chunk_1_constraints.json
many_chunks_chunk_0_columns.csv                                 many_chunks_chunk_1_opt.pil
many_chunks_chunk_0_commits.bin …
```

Pipeline Artifacts: Include name

---

riscv/src/bootloader.rs
riscv/src/compiler.rs
riscv/tests/riscv.rs
riscv_executor/src/lib.rs

This PR fixes two bugs in continuations:
- The bootloader now calls every sub-machine once. This fixes the `many_chunks` test, which was failing because some machine was not called at least once in the second chunk.
- I added the `P0-P11` registers to be initialized with the bootloader.
To put this in a graph:
```mermaid
graph TD
A["Continuations broken"] --> B["Continuations fixed"]
```

Fix continuations

---

executor/Cargo.toml

Removes the `release_max_level_debug` feature from the `log` crate, which enables trace logs also for release binaries.
I introduced this feature a while ago and believe that I used to check the static maximum log level and only do some work if it was `trace`. This saved some performance.
However, I don't find any of this code anymore, and even if, it could be replaced with a runtime check using `log_enabled!()`.
According to the benchmark, there are no performance implicaions:
```
keccak-executor-benchmark/keccak
time:   [12.000 s 12.192 s 12.501 s]
change: [-5.4506% -1.4929% +2.3987%] (p = 0.51 > 0.05)
No change in performance detected.
```

Allow trace logs in release mode

---

ast/src/analyzed/mod.rs
halo2/src/circuit_builder.rs
halo2/src/circuit_data.rs
halo2/src/mock_prover.rs
halo2/src/prover.rs

Fixes #820 
Step towards #814 
This PR implements public outputs for the Halo2 backend (for eStark, they were already supported).

Implement publics for Halo2 backend

---

compiler/src/pipeline.rs
compiler/src/test_util.rs
executor/src/witgen/machines/write_once_memory.rs
executor/src/witgen/mod.rs
number/src/serialize.rs
powdr_cli/src/main.rs
riscv/src/bootloader.rs
riscv/src/compiler.rs
riscv/src/continuations.rs
riscv_executor/src/lib.rs

Depends on #838
Step towards #814
With this PR, bootloader inputs come from a write-once memory instead of being passed via the free input. This has two advantages:
- We can expose some of them as publics, without having to know in which row of the trace they are queried. For example, initial register values are now public outputs, but the row in which there are set depends on the number of pages.
- We can force the prover to provide the *same* value at different times during bootloader execution. This will be needed for updating the Merkle root (which works by doing two Merkle proofs using the same siblings).
The overhead is pretty minor: just two additional columns (one fixed for the memory address, one witness for the memory values) and two additional lookups (which could be merged …

Bootloader inputs: Read from read-only memory

---

ast/src/lib.rs

And do not indent empty lines.

Use spaces for indentation.

---

airgen/src/lib.rs
analysis/src/vm/batcher.rs
analysis/src/vm/inference.rs
asm_to_pil/src/romgen.rs
ast/Cargo.toml
ast/src/asm_analysis/display.rs
ast/src/lib.rs
ast/src/parsed/asm.rs
ast/src/parsed/display.rs
importer/src/path_canonicalizer.rs
importer/test_data/import_after_usage.expected.asm
importer/test_data/import_module.expected.asm
importer/test_data/import_of_import.expected.asm
importer/test_data/submachine_found.expected.asm
importer/test_data/usage_chain.expected.asm
parser/src/powdr.lalrpop
type_check/src/lib.rs

The goal of this PR is to make the distinction between AbsoluteSymbolPath and SymbolPath also apparent in the source.
Currently, we resolve relative paths in code like
```
mod x {
machine X { ... }
}
mod y {
machine Y {
super::x::X my_x; // sub-machine with relative path
}
}
```
into
```
mod x {
machine X { ... }
}
mod y {
machine Y {
x::X my_x; // sub-machine with relative path
}
}
```
Now the issue is that, internally, the `x::X` in the second version is an AbsoluteSymbolPath, but if we print and re-parse the code, it is treated as a relative path again and does not resolve.
Because of that, I'm changing `AbsoluteSymbolPath::display` to prepend a `::` to make this distinction clear.
As a next step, we should of course also allow to parse paths that start with a `::`. Whether we should …

Clean up paths

---

riscv/src/compiler.rs
riscv/src/continuations.rs
riscv/src/continuations/bootloader.rs
riscv/src/continuations/memory_merkle_tree.rs
riscv/src/lib.rs
riscv/tests/common/mod.rs
riscv_executor/src/lib.rs

Another step towards #814.
This PR adds a public outputs to expose the root hash of the initial memory content. Then, the prover (privately) provides a Merkle proof which is validated by the bootloader, for each paged-in memory page.
This makes sure that the prover can only page-in pages that are actually part of the tree.

Bootloader: Validate Merkle proofs

---

analysis/src/vm/inference.rs
asm_to_pil/src/romgen.rs
asm_to_pil/src/vm_to_constrained.rs
ast/src/analyzed/display.rs
ast/src/asm_analysis/display.rs
ast/src/parsed/asm.rs
ast/src/parsed/build.rs
ast/src/parsed/display.rs
ast/src/parsed/mod.rs
compiler/tests/asm.rs
executor/src/constant_evaluator/mod.rs
linker/src/lib.rs
parser/src/powdr.lalrpop
pil_analyzer/src/expression_processor.rs
pil_analyzer/src/lib.rs
pil_analyzer/src/pil_analyzer.rs
pil_analyzer/src/statement_processor.rs
riscv/src/continuations/bootloader.rs
riscv_executor/src/lib.rs
test_data/pil/arith_improved.pil

Changes references in PIL to use SymbolPath instead of NamspacedPolynomialReference, i.e. we can use `super` and arbitrarily nested namespaces. It also changes `namespace` to allow a `SymbolPath`. Because namespaces currently cannot be nested, you need to use
```
namespace A::B::C(N);
```
if you want nested namespaces.
It also changes `PILAnalyzer` to work in three stages instead of doing it all at once:
1. import resolution and parsing dependent files
2. register all declarations / names
3. resolve names.
And finally, the name resolution in PILAnalyzer does not blindly add the current namespace, but instead, it tries to find the reference name relative to the current namespace but if that fails, it descends step by step to the root to discover it.
This is preparation for combining PIL …

Proper name resolution in PIL.

---

executor/src/witgen/vm_processor.rs

This is an error introduced in #848: We used to log every 1k rows, but now the logging frequency is more dynamic. The rows/s calculation hasn't been adjusted.

Fix performance logging

---

executor/src/witgen/generator.rs
executor/src/witgen/identity_processor.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/machines/double_sorted_witness_machine.rs
executor/src/witgen/machines/fixed_lookup_machine.rs
executor/src/witgen/machines/machine_extractor.rs
executor/src/witgen/machines/mod.rs
executor/src/witgen/machines/profiling.rs
executor/src/witgen/machines/sorted_witness_machine.rs
executor/src/witgen/machines/write_once_memory.rs
executor/src/witgen/mod.rs

Add the end of witness generation, prints a summary of how much time was spent in each machine, for example:
```
== Witgen profile (534856 events)
61.5% (   28.3s): Main Machine
34.9% (   16.1s): FixedLookup
2.4% (    1.1s): witgen (outer code)
1.1% ( 502.1ms): Secondary machine 3: main_poseidon_gl (BlockMachine)
0.0% (   8.1ms): Secondary machine 5: main_split_gl (BlockMachine)
0.0% (   4.2ms): Secondary machine 0: main (WriteOnceMemory)
0.0% (   3.1ms): Secondary machine 2: main_binary (BlockMachine)
0.0% ( 791.0µs): Secondary machine 4: main_shift (BlockMachine)
0.0% ( 325.0µs): Secondary machine 1: main (DoubleSortedWitnesses)
---------------------------
==> Total: 45.965185s
```
Changes:
- I added that each machine must implement `name(&self) -> &str`. Most machines already had that …

Witness generation profiling

---

compiler/benches/executor_benchmark.rs

I think `many_chunks` is actually a better benchmark, at least in some situations. Compared to Keccak it:
- Includes the Poseidon and SplitGL machines
- Includes the bootloader
- Does not reach the infinite loop in the first chunk
On my system:
```
executor-benchmark/keccak
time:   [12.258 s 12.342 s 12.429 s]
executor-benchmark/many_chunks_chunk_0
time:   [45.671 s 46.436 s 47.459 s]
```

Add `many_chunks` example to benchmarks

---

riscv_executor/src/lib.rs

`get_pc()` saves a hash table lookup on every instruction that reads PC

Introduced get_pc()

---

executor/src/witgen/machines/double_sorted_witness_machine.rs
executor/src/witgen/vm_processor.rs

In out memory machine, we have something like:
```
col fixed POSITIVE(i) { i + 1 };
// ...
(1 - LAST) { m_change * (m_addr' - m_addr) + (1 - m_change) * (m_step' - m_step) } in POSITIVE;
```
this check will fail if the *difference* between two memory addresses is larger than the degree. However, we used to have a check that the address must not be larger than the degree. I don't think this is actually a problem, so I changed the checks.
Also changed some log levels.

DoubleSortedWitnesses: Remove overly cautious error

---

compiler/benches/executor_benchmark.rs
compiler/src/pipeline.rs
compiler/src/test_util.rs
halo2/src/mock_prover.rs
riscv/src/continuations.rs
riscv/tests/riscv.rs

A typical continuations workflow looks like this:
```mermaid
graph TD
AsmFile --> ...
... --> PilWithConstants
PilWithConstants --> GeneratedWitness
GeneratedWitness --> Proof
style GeneratedWitness fill:#ffe7e6
style Proof fill:#ffe7e6
```
Only the two last steps are chunk-specific, yet we used to run the entire pipeline for each chunk.
With this PR, it is advanced to the `PilWithConstants` stage once, the result of which is kept in memory. This artifact is now clonable (rather than the entire pipeline as suggested in #840). As a result, the pipeline can be re-started from this step.

Continuations: Don't re-run pipeline parts that can only be run once

---

riscv/src/compiler.rs
riscv/src/continuations/bootloader.rs
riscv_executor/src/lib.rs

Taking a different approach from #838, this PR eliminates that there is a special PC (0) that can be provided to the bootloader so that it does nothing (i.e., updates `pc := pc + 1`, this is what we want to happen in the very first chunk). Now, the PC to jump to has to be explicitly provided in the first chunk.
This eliminates some special treatment of the first chunk and makes #878 easier.
However, in order to avoid having to count the bootloader and machine initialization instructions (as before #838), the code now looks like this:
```
// Skip the next instruction
jump submachine_init;
// For convenience, this instruction has a known fixed PC (3) and just jumps
// to whatever comes after the bootloader. This avoids having to count the instructions
// of the bootloader and the submachine …
```

Bootloader: Pass correct PC in the first chunk

---

executor/src/witgen/machines/double_sorted_witness_machine.rs
riscv/src/compiler.rs
test_data/asm/mem_read_write.asm

In our implementation of read/write memory, we had an unnecessary column called `m_op`, which is only used in the following constraints:
```
m_op * (1 - m_op) = 0;
m_is_write * (1 - m_op) = 0;
m_is_read * (1 - m_op) = 0;
```
This is not useful, because setting `m_op` to 1 will satisfy the constraints.
This is likely an artefact of porting code from [Polygon's implementation](https://github.com/0xPolygonHermez/zkevm-proverjs/blob/main/pil/mem.pil): They need that, because they have a [single permutation](https://github.com/0xPolygonHermez/zkevm-proverjs/blob/main/pil/main.pil#L752-L765) for both reads and writes (and `mOp` is the selector). We, on the other hand, have two permutations & selectors: `m_is_read` and `m_is_write`.

Remove `m_op`

---

ast/src/parsed/display.rs
parser/src/lib.rs
pil_analyzer/src/pil_analyzer.rs

Without the additional parentheses, displaying and re-parsing `(|x| x)(2)` would result in `|x| x(2)`.

Fix display of lambda functions.

---

pipeline/benches/executor_benchmark.rs
riscv/src/continuations.rs
riscv/src/continuations/bootloader.rs
riscv/tests/common/mod.rs
riscv/tests/riscv_data/many_chunks.rs

With this PR, accessed memory pages are paged-in by the bootloader also for the first chunk (like for any other chunk).
The idea is that, to make continuations sound (#814), we'll want to enforce that the first access to any memory cell was a write by the bootloader. This PR starts by enforcing that the first access is a read. This is in addition to the existing rule that if the first access is a read, the value should be 0. This rule becomes obsolete if the RISC-V machine has been compiled with the bootloader.
As a result, I needed change the continuations code to actually page-in accessed pages in the first chunk.
Also, I made the `many_chunks` example slightly larger, so that it needs 3 chunks instead of 2.

Bootloader: Page in accessed page on first chunk

---

Cargo.toml
powdr_riscv_rt/Cargo.toml
powdr_riscv_rt/rust-toolchain.toml
powdr_riscv_rt/src/allocator.rs
powdr_riscv_rt/src/coprocessors.rs
powdr_riscv_rt/src/fmt.rs
powdr_riscv_rt/src/lib.rs

For now this is a copy of the `runtime` crate that still lives inside the `riscv` crate. I think this is better UX and I'm using it here: https://github.com/powdr-labs/powdr_revm/blob/continuations/evm/Cargo.toml#L11 . This is quite similar to how we use the `riscv-rt` crate in https://github.com/leonardoalt/ecdsa-powdr/blob/main/riscv-bin/Cargo.toml#L7 when running in `qemu`.

extract the riscv runtime crate into its own crate

---

executor/src/witgen/machines/double_sorted_witness_machine.rs
executor/src/witgen/machines/machine_extractor.rs
pipeline/tests/asm.rs
riscv/src/compiler.rs
test_data/asm/mem_read_write_large_diffs.asm

Get's rid of the restriction that in the memory machine, consecutive rows can have a diff of at most the degree.
Instead, we have two new witness columns, `m_diff_upper` and `m_diff_lower`, both constrained to be 16 bit. Using those, we can we can make sure that the diff can be represented as a 32-bit number.

Read/Write memory: Allow bigger diffs

---

Cargo.toml
analysis/Cargo.toml
ast/Cargo.toml
importer/Cargo.toml
linker/Cargo.toml
powdr/Cargo.toml
powdr/src/lib.rs

this is done in a very simple way right now just to get it started. Follow up PRs should
- use this crate in `powdr_cli`
- re-export relevant symbols directly

new powdr crate

---

riscv/Cargo.toml
riscv/tests/riscv.rs
riscv/tests/riscv_data/evm/Cargo.toml

Fixing the EVM test inputs and trying it out on our CI again. If CI fails because of OOM I'll comment the function out but will leave the updated inputs and `verify_riscv_crate` adjustment.

fix evm test inputs

---

executor/Cargo.toml
executor/src/witgen/generator.rs
executor/src/witgen/machines/machine_extractor.rs
executor/src/witgen/machines/profiling.rs
executor/src/witgen/mod.rs
executor/src/witgen/vm_processor.rs
riscv/src/continuations.rs

Changes:
- Increase the log level to debug for a bunch of messages:
- Witgen Profile
- Machine detection logs
- Externally witness witness smaller than the degree (this is normal, e.g. the continuations code does this)
- A failing loop detection in the last few rows
- I used [indicatif](https://docs.rs/indicatif/latest/indicatif/) to render a progress bar for the main machine
An interesting test case is this:
`cargo run -r rust riscv/tests/riscv_data/many_chunks.rs -o output -f --coprocessors binary,shift,split_gl,poseidon_gl --prove-with pil-stark-cli -c`
Which leads to a witness generation output of:
```
Running chunk 1 / 3...
Running main machine for 262144 rows
[00:00:49 (ETA: 00:00:00)] ████████████████████████████████████████ 100% - 6186 rows/s, 655k identities/s, 83% progress …
```

Improve witness generation logging

---

executor/src/witgen/machines/double_sorted_witness_machine.rs
pipeline/src/verify.rs
pipeline/tests/asm.rs
riscv/src/compiler.rs
riscv/src/continuations/bootloader.rs
riscv_executor/src/lib.rs
test_data/asm/mem_read_write_no_memory_accesses.asm
test_data/asm/mem_read_write_with_bootloader.asm

This PR introduces an `mstore_bootloader` instruction in addition to the `mstore` instruction. It works just like `mstore`, but is only used by the bootloader. Additionally, there is a rule that the first access to any memory cell has to be a write by the bootloader.
This checks an item from #814: We make sure that only paged-in memory cells are accessed during execution.
Unfortunately, this required some changes to the memory machine which are explained in a comment in `riscv/src/compiler.rs`.

Introduce `mstore_bootloader` instruction

---

ast/src/analyzed/mod.rs
executor/src/witgen/mod.rs

Prints the values of public outputs after witness generation.
This will be nice to be able to manually perform additional checks. For example that the public bootloader inputs are as they should be.
For example:
`RUST_LOG=debug cargo run -r rust riscv/tests/riscv_data/many_chunks.rs -o output -f --coprocessors binary,shift,split_gl,poseidon_gl --prove-with pil-stark-cli -c`
Now prints:
```
...
Publics:
initial_x1: 2437
initial_x2: 65520
initial_x3: 0
initial_x4: 0
initial_x5: 0
initial_x6: 0
initial_x7: 0
initial_x8: 0
initial_x9: 0
initial_x10: 66612
initial_x11: 4029186946
initial_x12: 98116
initial_x13: 4029186946
initial_x14: 3798458975
initial_x15: 66616
initial_x16: 0
initial_x17: 0
initial_x18: 0
initial_x19: 0
initial_x20: 0
initial_x21: 0
initial_x22: 0
initial_x23: 0 …
```

Print publics after witgen

---

riscv/src/continuations.rs
riscv/src/continuations/bootloader.rs
riscv/src/continuations/memory_merkle_tree.rs

This PR adds a few bootloader inputs, which are (for now) largely ignored:
- A *claimed* memory hash at the end of the execution. This is exposed as public output but otherwise ignored.
- For now, we just set it to the same value as the initial memory hash, i.e., we always claim memory does not change.
- For each page, the *claimed* page hash at the end of the execution. This value is completely ignored for now.
- Again, we just set it to the initial page hash, as if the page is never changed.
This is supposed to be a small PR that prepares for the next step: Validating the Merkle tree update.

Bootloader inputs: Add final memory hash and updated page hashes

---

airgen/src/lib.rs
analysis/src/block_enforcer.rs
analysis/src/vm/batcher.rs
analysis/src/vm/inference.rs
asm_to_pil/src/lib.rs
asm_to_pil/src/romgen.rs
ast/src/asm_analysis/display.rs
ast/src/asm_analysis/mod.rs
ast/src/object/display.rs
ast/src/object/mod.rs
ast/src/parsed/asm.rs
ast/src/parsed/display.rs
ast/src/parsed/folder.rs
ast/src/parsed/mod.rs
book/src/SUMMARY.md
book/src/asm/declarations.md
importer/src/path_canonicalizer.rs
importer/src/powdr_std.rs
linker/Cargo.toml
linker/src/lib.rs
parser/src/powdr.lalrpop
pil_analyzer/src/pil_analyzer.rs
pipeline/tests/asm.rs
riscv/src/continuations.rs
riscv_executor/src/lib.rs
test_data/asm/book/declarations.asm
test_data/asm/book/modules.asm
test_data/asm/pil_at_module_level.asm
test_data/asm/secondary_block_machine_add2.asm
type_check/src/lib.rs

This now is able to handle:
```
let x = 12;
mod M {
use super::x as r;
let y = r + 2;
}
mod R {
use super::x;
use super::M::y;
machine FullConstant {
degree 2;
let C = |i| match i % 2 {
0 => x,
1 => y,
};
col commit w;
w = C;
}
}
```
and translates this through all the stages of the assembly handling, object, pilgraph, linker, whatever ... to:
```
namespace M(2);
let y = (x + 2);
namespace Global(2);
let x = 12;
namespace main(2);
let C = |i| match (i % 2) { 0 => x, 1 => M::y, };
pol commit w;
w = C;
```
which is then properly parsed and executed!
TODO:

Pil in asm at global level

---

riscv/src/continuations.rs
riscv/src/continuations/bootloader.rs
riscv/src/continuations/memory_merkle_tree.rs

Contributes to #814 
With this PR, the bootloader inputs introduced in #896 are actually correct. Furthermore, the provided Merkle proofs for the current page now proof membership assuming the tree was already updated for the previous pages (see approach 2 in [this comment](https://github.com/powdr-labs/powdr/issues/814#issuecomment-1884513561)). The bootloader changes from #898 verify this.
The output for the `many_chunks` example is now as follows:
```
Running chunk 0...
Building bootloader inputs for chunk 0...
214 unique memory accesses over 3 accessed pages: {63, 64, 65}
Bootloader inputs length: 1105
Simulating chunk execution...
Initial memory root hash: 4b2c7fafd0e0fa550605585fa45580097fb2a998e2fe440f77189866453eb6e3
Final memory root hash: …
```

Correct updated page hashes

---

airgen/src/lib.rs
analysis/src/lib.rs
analysis/src/machine_check.rs
asm_to_pil/src/lib.rs
asm_to_pil/src/romgen.rs
asm_to_pil/src/vm_to_constrained.rs
ast/src/analyzed/mod.rs
ast/src/asm_analysis/mod.rs
ast/src/lib.rs
ast/src/parsed/asm.rs
ast/src/parsed/mod.rs
backend/src/pilstark/json_exporter/mod.rs
linker/src/lib.rs
parser/src/lib.rs
parser/src/powdr.lalrpop
parser_util/src/lines.rs
pil_analyzer/src/lib.rs
pil_analyzer/src/pil_analyzer.rs
pil_analyzer/src/statement_processor.rs
pipeline/src/pipeline.rs
riscv_executor/src/lib.rs

This PR at first was only intended to add a way for analyzing a `PILFile` directly without having to go back to source form.
In doing that, I ran into some logic in the analyzer related to matching parsed statements to the originating source.
This PR encapsulates this logic into the parser, so parsed PIL and ASM statements carry a `SourceRef` which points to the file, line and column where it originated from.
For now, generated statements (e.g., linker step) use a SourceRef::unknown(), which just points to no file.

Generate references to the source while parsing

---

.github/workflows/pr-tests.yml

I think this avoids fully recompiling some dependencies.

Use pr-tests for clippy as well.

---

.github/workflows/pr-tests.yml

This should improve our timing statistics: I think the CI time reported on "running tests" also includes building the tests because we don't really build them in the previous step.

Build all targets.

---

.github/workflows/pr-tests.yml

Cache entry from `main` keeps getting evicted. Prevent other branches from writing cache entries (they can only fetch from main).

github actions: only store cache from main

---

executor/src/witgen/identity_processor.rs
executor/src/witgen/processor.rs

Pulled out of #967
In the Arith machine of #967, I convert between 32-Bit (outside the machine) and 16-bit (inside the machine) values using a lookup like this:
```
instr_eq0 { 0, A0, ... } in main_arith.CLK32_31 { main_arith.operation_id, ((main_arith.x1[1] * (2 ** 16)) + main.arith.x1[0]), ... };
```
This PR fixes witgen for this case.

Witgen: Use `solve_with_range_constraints()` when processing outer queries

---

executor/src/witgen/sequence_iterator.rs

Pulled out of #967
In the block machine default sequence iterator, we now do one more pass (down, up, down, and up again). This was necessary for the Arith machine.
Performance shouldn't change much because we're caching the sequence anyway.
Benchmark results:
```
executor-benchmark/keccak
time:   [12.838 s 13.128 s 13.512 s]
change: [-8.8834% -3.9610% +0.7503%] (p = 0.17 > 0.05)
No change in performance detected.
executor-benchmark/many_chunks_chunk_0
time:   [55.676 s 57.184 s 59.712 s]
change: [-2.6013% +1.0872% +5.7883%] (p = 0.71 > 0.05)
No change in performance detected.
```

Block Machine Default Sequence Iterator: Do one more pass

---

pipeline/src/pipeline.rs

This can be helpful for debugging, because the condenser has run but the optimizer has not yet run.

Persist Analyzed PIL as well

---

riscv/src/riscv_asm.lalrpop

So that in `(42 -2)`, `-2` doesn't get parsed as a single token.

Resolving unary minus at AST level.

---

riscv-executor/src/lib.rs

Fixes:
`cargo run -r rust riscv/tests/riscv_data/sum.rs -f -o /tmp/sum -i "6,3,1,2,3" --coprocessors "binary,shift" --field bn254 --just-execute`

Fix `Elem::from_fe` for Bn254 field

---

ast/src/analyzed/mod.rs
ast/src/asm_analysis/mod.rs
ast/src/lib.rs
ast/src/object/mod.rs
ast/src/parsed/asm.rs
executor/src/witgen/mod.rs
pipeline/benches/executor_benchmark.rs
pipeline/src/pipeline.rs
pipeline/src/test_util.rs

Benchmark result (relevant because query callback now lives in an `Arc` instead of `Box`):
```
executor-benchmark/keccak
time:   [12.424 s 12.939 s 13.524 s]
change: [-9.7680% -4.4556% +1.4262%] (p = 0.16 > 0.05)
No change in performance detected.
executor-benchmark/many_chunks_chunk_0
time:   [47.732 s 48.429 s 49.229 s]
change: [+0.7940% +2.8040% +4.9215%] (p = 0.02 < 0.05)
Change within noise threshold.
```

Make Pipeline Clonable

---

cli/src/main.rs
pipeline/src/pipeline.rs
riscv/src/continuations.rs
riscv/tests/riscv.rs

Using the fact that `Pipeline` can now be cloned (#841) to get rid of the pipeline factory business we had going on in the continuations code.

Simplify continuations with clonable pipeline

---

riscv/tests/instruction_tests/README
riscv/tests/instruction_tests/README.md
riscv/tests/instruction_tests/generated/sb.S
riscv/tests/instruction_tests/generated/sh.S
riscv/tests/instruction_tests/generated/slt.S
riscv/tests/instruction_tests/generated/sltiu.S
riscv/tests/instruction_tests/generated/sltu.S
riscv/tests/instruction_tests/generated/srli.S
riscv/tests/instruction_tests/generated/sw.S
riscv/tests/instruction_tests/sources/sb.S
riscv/tests/instruction_tests/sources/sh.S
riscv/tests/instruction_tests/sources/slt.S
riscv/tests/instruction_tests/sources/sltiu.S
riscv/tests/instruction_tests/sources/sltu.S
riscv/tests/instruction_tests/sources/srli.S
riscv/tests/instruction_tests/sources/sw.S

Also listed in the README.md all tests that were not included and why.
One of the newly included tests, `instruction_tests::slt`, actually performed its duty and found a possible bug (issue #989), so it is not currently passing.
Supersedes PR #257.

Added riscv32imac userspace tests that we currently support.

---

riscv-executor/src/lib.rs
riscv/src/compiler.rs
riscv/src/continuations/bootloader.rs

Contributes to #814 
Changes:
- Prefix all labels in the bootloader with `bootloader_` to avoid collisions
- Add a shutdown routine that is not currently called. It works very similar to the bootloader and does two things:
- Assert that final register values are as claimed
- Hash all pages again (the *same* that are hashed in the bootloader) and assert that they are equal to the claimed final page hashes (which was already used by the bootloader to update the Merkle root)

Implement shutdown routine assembly

---

pipeline/src/pipeline.rs
riscv/src/continuations.rs
riscv/src/continuations/bootloader.rs

Depends on #904
Contributes to #814
With this PR, we have a new `jump_to_shutdown_routine` which is *supposed* to be 1 exactly once. The idea is that when it is active, the execution jumps to the shutdown routine introduced in #904. The continuations code has been adjusted so that we already set the column correctly (leaving enough rows for the shutdown routine to finish).
However, none of this is enforced yet and the new column is ignored. See #915 for a prototype that enforces it and actually runs the shutdown routine.

Introduce `jump_to_shutdown_routine`

---

halo2/Cargo.toml

Our CI is currently [broken](https://github.com/powdr-labs/powdr/actions/runs/7738811236/job/21100393682?pr=991), because of [this commit](https://github.com/privacy-scaling-explorations/snark-verifier/commit/946536fc01901db93a3e7cdb8a7359a7ef675b55) in the `snark-verifier` repo. It upgrades the `halo2curves` dependency, causing us to have both version `0.6.0` and `0.3.2`. But version `0.6.0` needs a newer version of `subtle` and apparently doesn't specify it...
I guess a better solution would be to also upgrade Halo2, but that might be more involved.

Pin `snark-verifier`

---

pipeline/tests/powdr_std.rs
std/arith.asm
std/mod.asm
test_data/pil/arith_improved.pil
test_data/std/arith_test.asm

Adds an arithmetic machine to the Powdr standard library, supporting equation 0 for now.
This brings together the work by @0xKitetsu-smdk (#831, Machine wrapper, unit test) and @chriseth (`arith_improved.pil`, an ergonomic implementation of Polygon's arithmetic machine).

Arith machine, Equation 0

---

book/src/installation.md

Rebased up as per @leonardoalt's request in #996. 
---
At the moment the docs for newcomers are misleading, if they follow the Installation page and then navigate to the Hello World page, the SNARK generation for the minimal VM fails as the Halo2 backend is not built by default in the CLI module.
I've proposed that the feature flag is enabled for the Halo2 backend in the Installation page to prevent others from having this issue.
A note could alternatively be added to the Hello World page, but I'm thinking in terms of which place will ensure people aren't going to hit snags when they first try out powdr.
The simplest solution would just be to enable the Halo2 backend by default, but no doubt you've disabled it for a reason.

Add feature flag to include Halo2 backend

---

riscv/build.rs

`jal` instruction test didn't run locally, and I somehow thought it did, which led me to push broken code and break nightly.
Now newly added tests will run.

bugfix: file addition and removal wasn't triggering a rebuild

---

analysis/README.md
ast/src/parsed/display.rs
linker/src/lib.rs
number/src/macros.rs
parser/Cargo.toml
parser/src/lib.rs
parser/src/powdr.lalrpop
pipeline/tests/pil.rs
riscv/src/coprocessors.rs
test_data/asm/block_machine_cache_miss.asm
test_data/asm/book/modules.asm
test_data/asm/different_signatures.asm
test_data/asm/sqrt.asm
test_data/asm/vm_to_block_array.asm
test_data/asm/vm_to_block_multiple_interfaces.asm
test_data/asm/vm_to_block_to_block.asm
test_data/asm/vm_to_block_unique_interface.asm
test_data/asm/vm_to_vm.asm
test_data/asm/vm_to_vm_dynamic_trace_length.asm
test_data/asm/vm_to_vm_to_block.asm
test_data/asm/vm_to_vm_to_vm.asm
test_data/std/arith_test.asm
test_data/std/poseidon_bn254_test.asm
test_data/std/poseidon_gl_test.asm
test_data/std/split_bn254_test.asm
test_data/std/split_gl_test.asm

Require semicolon on instr `=` declarations.
Added test that parses, writes and reparses all `pil|asm` files under `test_data`.
This revealed some issues with `Display` implementations that this PR also fixes

require semicolon in `instr and Y, Z -> X = binary.and;` declarations

---

ast/src/analyzed/display.rs
ast/src/analyzed/mod.rs
ast/src/analyzed/types.rs
ast/src/analyzed/visitor.rs
ast/src/asm_analysis/display.rs
ast/src/asm_analysis/mod.rs
ast/src/object/display.rs
ast/src/object/mod.rs
ast/src/parsed/asm.rs
ast/src/parsed/display.rs
ast/src/parsed/mod.rs
ast/src/parsed/visitor.rs
book/src/pil/declarations.md
executor/src/constant_evaluator/mod.rs
importer/src/path_canonicalizer.rs
linker/src/lib.rs
parser/src/lib.rs
parser/src/powdr.lalrpop
pil-analyzer/src/condenser.rs
pil-analyzer/src/evaluator.rs
pil-analyzer/src/pil_analyzer.rs
pil-analyzer/src/statement_processor.rs
std/arith.asm
std/array.asm
std/debug.asm
std/utils.asm
test_data/asm/pil_at_module_level.asm
test_data/pil/arith_improved.pil
test_data/pil/book/declarations.pil
test_data/pil/book/generic_to_algebraic.pil

TODO:
Maybe we should instead add an explicit conversion call during analysis if the type turns out to be int instead of fe.
Whenever functions are called, we probably want to check the types. At least until we have a proper type checker, then we don't need that any more.

Support types for declarations

---

riscv/src/compiler.rs

It is redundant now that `li` can do the same thing.

Remove load_dynamic instruction

---

std/arith.asm
test_data/std/arith_test.asm

Small changes that prepare the implementation of equations 1-4.
Changes:
- Renamed `eq0` -> `affine_256`
- Added dummy operations `ec_add` and `ec_double`
- Added the `x3` witness columns needed for the two new operations
- Added the equation selectors `selEq[]`. It is determined from the operation via bit-decomposition
- I added 2 additional carries, which will be needed later in the other equations
- Also changed that carries can be negative, which is needed for the other equations
~Unfortunately, the resulting constraint system seems to trigger a bug in eStark, see #986. I turned of eStark proof generation for the unit test for now. The constraints are still checked by Pilcom.~
This is fixed.

Arithmetic Machine: Add `ec_add` and `ec_double` (dummy) operations

---

executor/src/witgen/mod.rs
executor/src/witgen/query_processor.rs
test_data/asm/sqrt.asm

Pulled out of #991
With this change, we can access functions when evaluating expression for queries. I demonstrated this in the `sqrt.asm` test, which on `main` would fail with `Symbol main_sqrt.sqrt_hint not found.`.

`QueryProcessor`: Give access to functions

---

.github/workflows/pr-tests.yml

This way, we can change the subset of tests run in each job without changing the branch protection rules.

Rename CI slow test jobs

---

cli/src/main.rs
number/src/serialize.rs
pipeline/build.rs
pipeline/src/pipeline.rs
pipeline/src/test_util.rs
riscv/build.rs

* Added buffer in places that didn't have it,
* removed buffer in places that didn't need it,
* replaced `Vec<u8>` reads with `fs::read()`,
* replaced `&[u8]` writes with `fs::write()`.

Cleanup on file reads and writes.

---

pipeline/src/pipeline.rs
riscv/src/continuations.rs

With a change introduced in #957, our `rust_continuations()` function expected the passed pipeline to be advanced to the `OptimizedPIL` stage at most. With this PR, we also accept pipelines which are already in the `PilWithEvaluatedFixedCols` stage.

Continuations: Don't assume the pipeline to be in an early stage

---

.github/workflows/nightly-tests.yml
pipeline/src/test_util.rs
pipeline/tests/asm.rs
pipeline/tests/pil.rs
pipeline/tests/powdr_std.rs

#1037 is currently failing because the `split_bn254_test` times out. In general, this test is slowing down our CI time. This is because it calls `gen_halo2_proof()` with a fairly large instance ($2^{16}$ rows), which creates two Halo2 proofs.
With this PR:
- By default, we call a new function `test_halo2()` which normally only computes a mock proof. This is much faster and generates better error message in the case of failing constraints.
- An exception is `poseidon_bn254_test`. This way PR tests still fail if something is wrong with proof generation in general.
- On nightly tests, `test_halo2()` calls `gen_halo2_proof()`.

Halo2 tests: Only run Mock prover in PR tests

---

pipeline/tests/powdr_std.rs

Looks like it works! but I wonder if the nightly tests are going to fail now?

Enable Halo2 test for arithmetic machine

---

executor/src/witgen/mod.rs
halo2/src/prover.rs
pipeline/src/test_util.rs
pipeline/tests/pil.rs

Depends on #1053
Fixes the bug reproduced in #1051 (which wasn't a soundness bug after all).
Because verification is working now properly, a few bugs in `gen_halo2_proof()` surfaced that are fixed in this PR as well, for example publics are handled properly now.

Fix Halo2 verification

---

ast/Cargo.toml
ast/src/analyzed/mod.rs
ast/src/analyzed/types.rs
ast/src/lib.rs
ast/src/parsed/mod.rs
cli/src/main.rs
number/Cargo.toml
number/src/bn254.rs
number/src/goldilocks.rs
number/src/macros.rs
number/src/serialize.rs
number/src/traits.rs
pipeline/src/pipeline.rs
pipeline/tests/pil.rs

This PR adds serde for  `Analyzed<T>` and every included data structures (as well as the `FieldElement` trait).
This aims to avoid a second analyze/optimize phase when calling `powdr prove`.
In order to do so, `powdr prove` can now accept the serialized `Analyzed<T>` as `{name}_opt.cbor` and start from there.
Note: This adds a new constraint, namely to use the same field for both phases. There should be a way to check that at runtime and print a nice error message, because actually it just fails to deserialize with an obscure serde message like `failed to fill the whole buffer`. Any input on that would be greatly appreciated :)

Serialize optimized PIL and load it for the prove phase

---

std/math/ff.asm

Pulled out of #1005.
I think the two cases are rather different and have different causes. It's helpful to know which we are dealing with!

Improve error message in `std::math::ff:inverse`

---

airgen/src/lib.rs
analysis/src/vm/inference.rs
asm-to-pil/src/romgen.rs
asm-to-pil/src/vm_to_constrained.rs
ast/src/asm_analysis/mod.rs
ast/src/parsed/asm.rs
ast/src/parsed/build.rs
ast/src/parsed/display.rs
book/src/asm/instructions.md
linker/src/lib.rs
parser/src/powdr.lalrpop
pipeline/tests/asm.rs
test_data/asm/book/instructions.asm
test_data/asm/vm_instr_param_mapping.asm

Allow mapping register usage on the RHS of `instr` declarations.
Included file `vm_instr_param_mapping.asm` shows possible usages.

`instr` declaration parameter mapping

---

cli/Cargo.toml

This way, `cargo run` runs `powdr` and doesn't ask you to specify a binary via `--bin` (since we also have the `powdr-schemas` binary).
Or is there a reason not to do this?

Set default binary to `powdr`

---

executor/src/witgen/generator.rs
pipeline/tests/pil.rs
test_data/pil/sum_via_witness_query.pil

For a description, see the comment in the code.
This fixes an issue Leo had when providing witness columns externally: The last row did a memory access which was executed before witgen was really starting. There is no reason to look at references without a next reference at this point anyway, so this is a quick fix.

On (N-1, 0) row pair, only execute identities with next reference

---

executor/src/witgen/block_processor.rs
executor/src/witgen/generator.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/processor.rs
executor/src/witgen/query_processor.rs
executor/src/witgen/rows.rs
executor/src/witgen/vm_processor.rs

This PR changes our strategy our strategy to handle non-rectangular block shapes and wrapping in block machines.
Previously, we used to insert a "dummy" block in the beginning (mostly the same as the first "real" block, so the first block was repeated twice).
Instead, this PR does two things:
- Introduces a new `RowIndex` type, which handles wrapping, i.e., `-1 == N - 1`
- In `block_machine.rs` we initialize the data with an empty *last* block. This way, the first block can write to the last block as well. In `take_witness_col_values()`, we remove the block, but any values written to it go into the default block, used to fill up unused rows.
The resulting witness is like it was before, except that the default block in the beginning is moved to the end instead.

Get rid of dummy blocks in BlockMachines

---

executor/src/witgen/eval_result.rs
executor/src/witgen/processor.rs

For example, when running the `block_lookup_or` test:
`cargo run pil test_data/pil/block_lookup_or.pil -o output -f`
In this particular example it will detect a loop and then fail, reverting to do the proper solving. But each time that happened, it printed an error.
Now the entire error message is stored in the `EvalError::Generic`.

Witgen: Don't log errors if they can be recovered from

---

backend/src/halo2_impl.rs
backend/src/lib.rs
cli/src/main.rs
halo2/src/mock_prover.rs
pipeline/benches/executor_benchmark.rs
pipeline/src/lib.rs
pipeline/src/pipeline.rs
pipeline/src/test_util.rs
pipeline/tests/pil.rs
powdr-test/examples/hello_world.rs
riscv/src/continuations.rs
riscv/tests/common/mod.rs
riscv/tests/riscv.rs

This PR refactors Pipeline to be more like a DAG that holds all possible artifacts at the same time, instead of a single-artifact linear path.
In this version:
- every artifact is owned by Pipeline at all times
- for each artifact:
* we have an `<artifact>()` function that checks whether that artifact exists
* if it doesn't, call `compute_<artifact>()` and sets the artifact to `Some(<computed_artifact>)`
- each `compute_<artifact>` function knows about its own dependencies up the graph, and simply calls `let dep1 = self.dep1(); let dep2 = self.dep2();` recursive up the DAG, which in turn may call other `compute_<artifact>()` functions.
This is an implementation that @georgwiese and I thought made sense for the use cases we have.
A few caveats with this current implementation:
1. All these …

refactor pipeline to be a DAG instead of a linear path

---

executor/src/witgen/affine_expression.rs
executor/src/witgen/machines/sorted_witness_machine.rs

- with `Cow` we can return a reference to coefficients directly when the affine is `clean`
- also removed the `nonzero_variables` method which as used in a single place and required another cloning

use `Cow` for returning `nonzero_coefficients`

---

riscv-executor/src/lib.rs
riscv/src/continuations/bootloader.rs
riscv/src/coprocessors.rs

This PR makes use of the recent changes in the instruction delegation to use state registers directly in poseidon.
This saves 60 columns in the poseidon rust test.

Use state registers directly in Poseidon

---

executor/src/witgen/affine_expression.rs
executor/src/witgen/expression_evaluator.rs
executor/src/witgen/machines/sorted_witness_machine.rs

Internally represent as an enum of Constant | One | Many, to avoid allocations in the common case of a single variable.
Also rewrote `ExpressionEvaluator::evaluate_binary_operation`, allowing it to shortcut earlier on Err when possible.

AffineExpression enum (improve executor benchmarks ~13/23%)

---

backend/src/pilstark/estark.rs
pipeline/src/pipeline.rs
pipeline/src/test_util.rs
pipeline/src/verify.rs
pipeline/tests/asm.rs
pipeline/tests/pil.rs
pipeline/tests/powdr_std.rs
riscv/tests/common/mod.rs
riscv/tests/riscv.rs
test_data/pil/fibonacci.pil

Some small changes and utility functions to make it easier to make tests that assert that proof generation fails if the witness is invalid.
I think we should add more in the future, also including lookups and permutation, but this one already needed a lot of changes, so I'll postpone that to another PR.

Add tests with invalid witnesses

---

halo2/src/circuit_builder.rs
halo2/src/prover.rs
pipeline/src/test_util.rs
pipeline/tests/pil.rs
test_data/pil/lookup_with_selector.pil
test_data/pil/permutation_with_selector.pil

This fixes a soundness bug we had for lookups & permutations with selectors: We used to multiply each element with the selector and then pass it to Halo2's lookup / permutation argument.
The issue is that this adds a 0 to the RHS (as long as the RHS selector is 0 at least once), allowing the prover to falsely claim that 0 is in the set. This PR fixes this by applying the technique described in section 3.3 of the [eStark paper](https://eprint.iacr.org/2023/474).

Fix Soundness Bug in Halo2 implementation

---

asm-to-pil/src/vm_to_constrained.rs
ast/src/parsed/build.rs
book/src/pil/builtins.md
book/src/pil/types.md
executor/src/constant_evaluator/mod.rs
executor/src/witgen/query_processor.rs
executor/src/witgen/rows.rs
linker/src/lib.rs
pil-analyzer/src/condenser.rs
pil-analyzer/src/evaluator.rs
pil-analyzer/src/pil_analyzer.rs
pil-analyzer/src/type_builtins.rs
riscv-executor/src/lib.rs
riscv/src/compiler.rs
std/mod.asm
std/prover.asm
std/split/split_bn254.asm
std/split/split_gl.asm
test_data/asm/palindrome.asm
test_data/asm/simple_sum.asm
test_data/asm/sqrt.asm
test_data/pil/witness_lookup.pil

This is the first step in removing the "Custom" feature of the evaluator by making `expr` and `constr` native to the evaluator. It makes sense since those are also native types for the type checker.

Make expressions and constraints native values.

---

Cargo.toml
backend/src/halo2_impl.rs
halo2/src/mock_prover.rs
pipeline/src/test_util.rs
pipeline/tests/pil.rs

This let's us test that the mock prover fails as well for invalid witnesses.
I think this can be merged now that https://github.com/privacy-scaling-explorations/halo2/pull/292 is merged. On the next Halo2 upgrade, we can remove the reliance on my fork.

Don't panic on Halo2 Mock errors

---

riscv/src/continuations.rs
riscv/src/continuations/bootloader.rs
riscv/src/continuations/memory_merkle_tree.rs

It saves up to 8GB of memory on running continuations and about 3 seconds on the construction of the MerkleTree.

Making the merkle tree sparse.

---

airgen/Cargo.toml
asm-to-pil/Cargo.toml
ast/Cargo.toml
ast/src/asm_analysis/mod.rs
ast/src/parsed/asm.rs
backend/src/pilstark/estark.rs
executor/Cargo.toml
executor/src/constant_evaluator/mod.rs
executor/src/witgen/affine_expression.rs
executor/src/witgen/query_processor.rs
executor/src/witgen/range_constraints.rs
halo2/Cargo.toml
number/src/bn254.rs
number/src/lib.rs
number/src/macros.rs
number/src/traits.rs
parser/Cargo.toml
parser/src/powdr.lalrpop
pil-analyzer/Cargo.toml
pil-analyzer/src/evaluator.rs
pil-analyzer/src/statement_processor.rs
pipeline/Cargo.toml
pipeline/benches/executor_benchmark.rs
pipeline/src/test_util.rs
pipeline/tests/powdr_std.rs
riscv-executor/src/lib.rs
riscv/src/continuations.rs

This allows to swap out the bigint implementation more easily.

Unify bigints

---

airgen/Cargo.toml
analysis/Cargo.toml
ast/Cargo.toml
backend/Cargo.toml
executor/Cargo.toml
halo2/Cargo.toml
number/Cargo.toml
parser-util/Cargo.toml
parser/Cargo.toml
pil-analyzer/Cargo.toml
pipeline/Cargo.toml
riscv/Cargo.toml

`cargo udeps` doesn't undertand why `env_logger` is needed on development dependencies. This fixes the `udeps` job on the nightly run.

Nightly fix: ignoring env_logger on cargo udeps.

---

pipeline/src/pipeline.rs

For the `rust` command on keccak, this produces:
```
Wrote /tmp/k7/keccak_riscv_alloc-5f10af7f806aff90.asm
Wrote /tmp/k7/keccak_riscv_compiler_builtins-221b3504ee5a99c1.asm
Wrote /tmp/k7/keccak_riscv_core-798c9a2f37dab981.asm
Wrote /tmp/k7/keccak_riscv_crunchy-dd3e87f4add5d272.asm
Wrote /tmp/k7/keccak_riscv_half-cc592384db433a36.asm
Wrote /tmp/k7/keccak_riscv_keccak-cfc210d8fbf52a4f.asm
Wrote /tmp/k7/keccak_riscv_powdr_riscv_runtime-cb0db18b7cfed7fa.asm
Wrote /tmp/k7/keccak_riscv_rustc_std_workspace_core-da8979b805546eff.asm
Wrote /tmp/k7/keccak_riscv_serde-b32e975fcf328287.asm
Wrote /tmp/k7/keccak_riscv_serde_cbor-36ff361265ab000d.asm
Wrote /tmp/k7/keccak_riscv_tiny_keccak-2be065d903a0b925.asm
Inferred degree 2^18
Wrote /tmp/k7/keccak.asm
Deducing witness columns...
Analyzing pil...
Run …
```

Change pipeline log level to info.

---

executor/src/constant_evaluator/mod.rs
executor/src/witgen/query_processor.rs
pil-analyzer/src/condenser.rs
pil-analyzer/src/evaluator.rs
pipeline/src/test_util.rs

Improves constant evaluation for keccak from 11 to 4.4 seconds.
This only caches the symbols themselves, i.e. for a column, it does not store the actual cell values, but only the function closure.
The Arc commit reduces it to 4 seconds.

Use evaluation cache for symbols.

---

ast/src/analyzed/mod.rs
pilopt/src/lib.rs

This fixes a bug where zero sized arrays could cause a crash when removing polynomials during optimization.
The issue is that `array_elements()` won't return anything for a zero sized array, but the array definition itself still has an `id` which is referenced by the code and needs to be updated.

fix `remove_polynomials` to work with zero sized arrays

---

executor/src/constant_evaluator/mod.rs
executor/src/witgen/query_processor.rs
pil-analyzer/src/evaluator.rs

When implementing the SymbolLookup trait and delegating to the Definitions implementation, that one could do recursive evaluations that would ignore the first implementation of SymbolLookup. This PR provides a mechanism where you can re-use parts of the Definitions implementation while recursive evaluations would still go through your own implementation.

Fix recursive lookups.

---

pilopt/src/lib.rs

This actually fixes an issue in #1126, because there the ASM code compiles to a duplicate identity, which witgen doesn't handle well. There is no point in keeping duplicate identities, so I added this step to the optimizer.

Remove duplicate identities

---

executor/src/witgen/machines/double_sorted_witness_machine.rs
executor/src/witgen/machines/machine_extractor.rs
executor/src/witgen/machines/mod.rs
executor/src/witgen/util.rs
riscv/src/compiler.rs
test_data/asm/mem_read_write.asm
test_data/asm/mem_read_write_large_diffs.asm
test_data/asm/mem_read_write_no_memory_accesses.asm
test_data/asm/mem_read_write_with_bootloader.asm

Pulled out of #1129.
This PR changes how we implement the memory machine, in a way that's closer to the PIL we'll compile to once we've extracted the memory machine as a separate ASM machine in the standard library (#1129).
Previously, constraints looked like this:
```
instr mload -> X { { ADDR, STEP, X } is m_is_read { m_addr, m_step, m_value } }
instr mstore X { { ADDR, STEP, X } is m_is_write { m_addr, m_step, m_value } }
```
Now, it looks like this:
```
instr mload -> X { { 0, ADDR, STEP, X } is m_selector1 { m_is_write, m_addr, m_step, m_value } }
instr mstore X { { 1, ADDR, STEP, X } is m_selector2 { m_is_write, m_addr, m_step, m_value } }
```
The selector no longer serves the role of "communicating" which operation should be performed. This makes it similar to how we connect …

Memory machine: Don't use selectors to distinguish operations

---

halo2/src/circuit_builder.rs
halo2/src/prover.rs

Bounds should be avoided on structs unless necessary (when using associated types)

Remove unnecessary bound on generic struct parameter

---

number/src/serialize.rs
pipeline/src/pipeline.rs
pipeline/src/util.rs
pipeline/tests/asm.rs

Assert that `read_polys_file` is not called with no columns.
Now `read_poly_set` returns an `Option`, with `None` being returned when there are no columns of the type.

bugfix #1155: read_polys_file with 0 columns

---

std/arith.asm
std/array.asm
test_data/std/arith_test.asm

Adds hints to the arithmetic machine, which fixes witness generation. I also converted Polygon's test cases.

Hints for arithmetic machine

---

std/split/split_bn254.asm
std/split/split_gl.asm

Because of #593, witgen didn't actually use the hint. When I tried to fix it, I noticed this bug.

Fix hints in split machines

---

cli/src/main.rs
pipeline/benches/executor_benchmark.rs
riscv/src/compiler.rs
riscv/src/coprocessors.rs
riscv/src/lib.rs
riscv/tests/instructions.rs
riscv/tests/riscv.rs

Fixes: #713
Fixes a soundness bug in the `mul` instruction in the RISC-V machine, when instantiated on the Goldilocks field. Instead of naively decomposing the result into bytes, we now use the `SplitGL` machine. This machine is now part of the default processors if the field is Goldilocks.

Fix soundness bug in `mul` instruction of RISC-V machine

---

airgen/Cargo.toml
airgen/src/lib.rs
analysis/src/machine_check.rs
asm-to-pil/src/vm_to_constrained.rs
ast/src/asm_analysis/display.rs
ast/src/asm_analysis/mod.rs
ast/src/object/mod.rs
ast/src/parsed/asm.rs
ast/src/parsed/display.rs
importer/src/path_canonicalizer.rs
linker/src/lib.rs
parser/src/lib.rs
parser/src/powdr.lalrpop
pipeline/tests/asm.rs
test_data/asm/permutations/block_to_block.asm
test_data/asm/permutations/incoming_needs_selector.asm
test_data/asm/permutations/simple.asm
test_data/asm/permutations/vm_to_block.asm
test_data/asm/permutations/vm_to_vm.asm

Allow `asm` machines to be linked by permutation arguments.
The syntax is the same as for lookups, but  uses a `~` (tilde) instead of `=`.
This PR is written in a way that there's no change to existing asm/pil code and tests, and so witgen support can be implemented separately

Permutation instructions/links

---

cli/src/main.rs
pipeline/benches/executor_benchmark.rs
riscv/src/compiler.rs
riscv/src/coprocessors.rs
riscv/tests/instructions.rs
riscv/tests/riscv.rs

The idea here is to move the machines/instructions that are always needed by the RISCV machine to the fixed implementation.
These are Binary, Shift and SplitGL. The first 2 are used in the RISCV asm -> powdr-asm translation, and SplitGL is used by the powdr `mul` instruction.
After that we're going to refactor coprocessors to be more like syscalls.

simplify coprocessors

---

ast/src/analyzed/mod.rs

The previous algorithm assumed that input IDs are contiguous in source order, the new one does not make any assumptions and creates IDs contiguous in source order.

Fix column removal.

---

ast/src/analyzed/mod.rs
executor/src/witgen/identity_processor.rs
pil-analyzer/src/condenser.rs
pil-analyzer/src/statement_processor.rs

This PR changes that `Identity` IDs are now globally unique, by doing to things:
1. When dispensing IDs, we now have only one ID counter, instead of one per type.
2. Fixed a bug in the condenser, where it would previously assign the same ID when evaluating a `|| -> constr[]`.

Make sure Identity IDs are unique

---

pipeline/tests/powdr_std.rs
std/memory.asm
std/mod.asm
test_data/std/memory_test.asm

With the recent changes by @pacheco, we can extract our [memory machine](https://github.com/powdr-labs/powdr/blob/main/riscv/src/compiler.rs#L687-L841) as a separate machine and add it to the standard library.
The result should be the same as calling the function linked above with `with_bootloader=false`, except that the memory alignment stuff is not inlined. For this reason, the machine is not yet used by the RISC-V machine, but it could be after #1077 is implemented.
[This](eb320dca0c65184483278f4837474bce76a8ad1f) shows the diff from what we have in `compiler.rs`.

Add read/write memory to standard library

---

executor/src/witgen/machines/write_once_memory.rs
pipeline/tests/asm.rs
pipeline/tests/powdr_std.rs
std/mod.asm
std/write_once_memory.asm
test_data/asm/mem_write_once.asm
test_data/asm/mem_write_once_external_write.asm
test_data/std/write_once_memory_test.asm

Fixes #844
This PR adds a new machine to the STD: `WriteOnceMemory`. This can be used in our RISC-V machine for bootloader inputs (#1203).
Most of the issues mentioned in the issue were fixed in the meantime or had a simple workaround (like defining `let LATCH = 1`). The only remaining issues were in the machine detection, which  I fixed here.
I also re-factor two existing tests.

Add Write-once memory to STD

---

pil-analyzer/src/lib.rs
pil-analyzer/src/statement_processor.rs
pil-analyzer/src/type_processor.rs
pil-analyzer/src/untyped_evaluator.rs

This PR extracts the type processor from the statement processor because we will also have to call it from the expression processor later on.

Extract type processor.

---

asm-to-pil/src/vm_to_constrained.rs

avoid confusion with airgen::ASMPILConverter

vm_to_constrained::ASMPILConverter => VMConverter

---

.github/workflows/pr-tests.yml

cargo clippy includes cargo check

---

executor/src/witgen/machines/double_sorted_witness_machine.rs

This is only needed for RISCV, but witgen is more general than RISCV and should allow memory accesses anywhere, especially since we have the std memory machine.
The RISCV executor also checks this so it won't go unchecked.

remove unaligned memory check in double sorted memory machine in witgen

---

ast/src/analyzed/mod.rs

Bug fix cherry-picked from #1203
When removing witness polynomials and updating their IDs, we did not replace references to them in the public declarations.

Bug fix in `Analyzed::remove_definitions`

---

backend/Cargo.toml
powdr/Cargo.toml
rust-toolchain.toml

Fix missing feature in starky

---

executor/src/witgen/block_processor.rs
executor/src/witgen/fixed_evaluator.rs
executor/src/witgen/generator.rs
executor/src/witgen/global_constraints.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/machines/double_sorted_witness_machine.rs
executor/src/witgen/machines/machine_extractor.rs
executor/src/witgen/machines/sorted_witness_machine.rs
executor/src/witgen/mod.rs
executor/src/witgen/rows.rs
executor/src/witgen/symbolic_witness_evaluator.rs
executor/src/witgen/vm_processor.rs

The global range constraints are now part of `FixedData`. Also, I got rid of the row factory, anyone with a reference to `FixedData` can now just call `Row::fresh(fixed_data, row_index)`. This simplifies things and should help with #1276.

Refactor: Make global range constraints part of FixedData

---

executor/src/witgen/eval_result.rs
executor/src/witgen/machines/block_machine.rs

@leonardoalt got a failing assertion in one of his tests because the rows in the Poseidon machine where exhausted. With this PR, this situation is detected earlier, leading to a better error message:
```
=> Error: Table rows exhausted for machine Secondary machine 3: main_poseidon_gl (BlockMachine)
```

Improve error message if the machine rows are exhausted

---

book/book.toml

mdbook offers to execute code blocks (since they are tagged as `rust`), which fails.
Remove the option to run code blocks.

Disable running book code blocks

---

backend/Cargo.toml

Depends on https://github.com/powdr-labs/pil-stark-prover/pull/9

Update pil-stark-prover to version that resuses consttree.bin.

---

riscv/src/continuations/bootloader.rs

Without this powdr-revme runs out of Poseidon rows sometimes.

increase continuations bootloader's page size

---

std/field.asm

Similar to what we have in Rust, this adds a function that detects "known" fields (Goldilocks and BN254 for now). Planning to use that in #1310 to assert that the field extension module is only used with compatible fields.

Add `std::field::known_field()`

---

pipeline/Cargo.toml
pipeline/benches/evaluator_benchmark.rs
riscv/Cargo.toml
riscv/benches/executor_benchmark.rs

This PR
- removes the riscv dev dependency from the pipeline crate
- splits the benchmark into riscv and pil benches
- fixes the query callback in the keccak bench

split benches and remove riscv dep from pipeline

---

cli-rs/Cargo.toml

Now `cargo run` is equivalent to `cargo run --bin powdr`. To run `powdr-rs`, you can do `cargo run --bin powdr-rs`.

Set `powdr` as the only default binary

---

backend/src/halo2/circuit_builder.rs

In Halo2, we need to simulate the "wrapping" behavior that we expect from the backend, by copying the first row of witness columns after the last. This was previously implemented by using copy constraints. Considering [how the argument works](https://zcash.github.io/halo2/design/proving-system/permutation.html), this leads to 1 additional fixed column during setup *per witness column*, and several additional witness columns (depending on the degree bound, but linear in the number of witness columns).
But because Halo2 offers rotations of arbitrary offsets, we can instead constrain this as:
`first_step * (witness_column - witness_column'degree)`
On the `simple_sum` example, this improved the proof time by ~15% (353.01825ms -> 302.067125ms). The benchmarks on Keccak are still running...

Halo2 backend: use fewer copy constraints

---

executor/src/witgen/machines/block_machine.rs
executor/src/witgen/machines/machine_extractor.rs
pipeline/src/verify.rs
pipeline/tests/asm.rs
test_data/pil/block_lookup_or_permutation.pil

Fixes an issue that @leonardoalt had on his `binary-mux2` branch.
There are two ways to have a block machine that is connected via a permutation:
1. Use permutations `<sel> { ... } is (sub.sel * sub.LATCH) { ... }`. This makes sure only rows where `sub.LATCH` is `1` can be selected. This is what we do when we compile from ASM to PIL.
2. Use permutations `<sel> { ... } is sub.sel { ... }`, but also a constraint `(1 - sub.LATCH) * sub.sel = 0`. This achieves something similar.
The problem is that in the second case, detecting the block size is harder, because the latch doesn't appear anywhere in the selector. So we used to look into *all* fixed columns to detect the period. But this includes fixed columns that might have a larger period (as is the case for the multiplexer machine).
This PR …

`BlockMachine`: Don't look into other fixed columns for period detection

---

std/protocols/permutation.asm

This fixes a soundness bug in the recently added permutation argument: To fingerprint a list $A = (a_1, ..., a_n)$ with selectors $S = (s_1, ..., s_n)$, we were computing:
$$
\prod_{i = 1}^n (X - s_i \cdot a_i)
$$
As a result, any element $a_i$ can be replaced with $0$, by setting the selector to $0$!
Now, an element $i$ with $s_i = 0$ does not contribute to the product anymore:
$$
\prod_{i = 1}^n (s_i \cdot (X - a_i - 1) + 1)
$$

Fix soundness bug in permutation argument

---

executor/src/witgen/eval_result.rs
executor/src/witgen/generator.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/machines/double_sorted_witness_machine.rs
executor/src/witgen/machines/sorted_witness_machine.rs
executor/src/witgen/machines/write_once_memory.rs
executor/src/witgen/processor.rs
pipeline/tests/asm.rs
test_data/asm/side_effects.asm

Cherry-picked ef6a72fcfab8a608f54b5e25cb173e51db953b69 from #1380.
With this PR, we track whether a call to a machine led to some side effect (e.g. added a block). In that case, the processed identity should count has having led to some progress, even if no values were returned to the calling machine. An example would be writing values to memory, which does not return any values and hence does not change the state of the caller.

Witgen: Handle machine calls with side effects

---

executor/src/witgen/affine_expression.rs
executor/src/witgen/block_processor.rs
executor/src/witgen/generator.rs
executor/src/witgen/global_constraints.rs
executor/src/witgen/identity_processor.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/machines/double_sorted_witness_machine.rs
executor/src/witgen/machines/machine_extractor.rs
executor/src/witgen/machines/mod.rs
executor/src/witgen/machines/sorted_witness_machine.rs
executor/src/witgen/machines/write_once_memory.rs
executor/src/witgen/mod.rs
executor/src/witgen/processor.rs
executor/src/witgen/vm_processor.rs
pipeline/tests/asm.rs
std/protocols/permutation.asm
test_data/asm/pass_range_constraints.asm

*Cherry-picked b1a07bd9a708e37deed42efe1be188d1682a84c2 from #1380, and extended on it.*
Fixes #1382.
With this PR, a lookup like `selector { byte_lower + 256 * byte_upper } in { <some other machine> }` works, even if the range constraints on `byte_lower` and `byte_upper` are not "global". For example, they could be implemented as `selector { byte_lower } in { BYTES }` (i.e., `byte_lower` is only range constrained when the machine call is active).
To make this work, I changed the `Machine::process_plookup` interface like this:
```diff
fn process_plookup<'b, Q: QueryCallback<T>>(
&mut self,
mutable_state: &'b mut MutableState<'a, 'b, T, Q>,
identity_id: u64,
-       args: &[AffineExpression<&'a AlgebraicReference, T>],
+       caller_rows: &'b RowPair<'b, 'a, T>,
) -> EvalResult<'a, T>; …
```

Witgen: Pass range constraints to callee

---

pipeline/tests/asm.rs
test_data/asm/multiple_signatures.asm

This tests that we can re-use operation IDs (if we want the same constraints), but switching around the inputs and outputs.

Add `multiple_signatures` test

---

pipeline/tests/powdr_std.rs
std/machines/memory.asm
test_data/std/memory_test_parallel_accesses.asm

This simulates one approach we could go for when moving registers to memory. The memory machine remains completely unchanged, but the step is increased by more than 1 in each step of the main machine. This way, from the point of view of memory, all the memory operations happen at different time steps, which allows for:
- Reading from the same address twice
- Writing to the same address that we read from (which from the point of view of memory should happen *after* the read)
The only downside I see with this approach is that this makes the differences of time steps between memory accesses bigger: Before it was at most the degree, now it is some small constant times the degree (in this example 3). The way the memory machine is currently built, the difference can be at most $2^{32} - 1$, so …

Add test for parallel memory accesses

---

riscv/src/code_gen.rs

`fence.i` is the instruction to flush the instructions cache on the processor, needed only when the executable code has been modified in memory.
But since we don't support dynamic code generation, it is better to fail at `fence.i` than treating it as `nop` and pretending there is nothing wrong.

Remove support to `fence.i`

---

book/src/pil/builtins.md
pil-analyzer/src/condenser.rs
pil-analyzer/tests/condenser.rs
std/prelude.asm

We mentioned this at the offsite so I had a go at it.
The stricter `Constr` which enforces left and right to have the same size:
```
enum Constr {
/// A polynomial identity.
Identity(expr, expr),
/// A lookup constraint with selectors.
Lookup((Option<expr>, Option<expr>), (expr, expr)[]),
/// A permutation constraint with selectors.
Permutation((Option<expr>, Option<expr>), (expr, expr)[]),
/// A connection constraint (copy constraint).
Connection((expr, expr)[])
}
```
This could eventually be made clearer with structs.

Make Constr prelude enum stricter

---

riscv/tests/riscv_data/keccak/src/lib.rs

Since witgen is getting faster and faster, we need to change this test so that it has more rows before it finds the loop, otherwise we are benchmarking mainly the loop.

Make keccak test a bit harder.

---

pipeline/tests/powdr_std.rs
std/machines/memory_with_bootloader_write.asm
std/machines/mod.asm
test_data/std/memory_with_bootloader_write_test.asm

This PR adds a new memory machine to the standard library that also supports a `mstore_bootloader` operation: It's like a normal `mstore`, but the first access to every memory cell *has to* come from this operation.
As a follow-up, we'll be able to use it in the RISC-V machine (#1462).
I think this is best reviewed by reviewing the diff to the normal memory machine and comparing it to [the code we have currently inlined in the RISC-V machine](https://github.com/powdr-labs/powdr/blob/abbe26618ff32c5afc39daf442255847a6640b5f/riscv/src/code_gen.rs#L500-L553):
```diff
3,5c3,7
< // A read/write memory, similar to that of Polygon:
< // https://github.com/0xPolygonHermez/zkevm-proverjs/blob/main/pil/mem.pil
< machine Memory with
---
> /// This machine is a slightly extended version of …
```

Add `MemoryWithBootloaderWrite` machine to std

---

backend/src/composite/mod.rs
backend/src/lib.rs
backend/src/vadcop_wrapper/mod.rs

Adds a `CompositeBackend` backend, that can evenatually be used to implement VadCop (#424) using any existing backend. The currently implementation just forwards everything to the wrapped backend; actually doing the proofs for each machine is future work.
To test:
`cargo run pil test_data/pil/fibonacci.pil -o output -f --prove-with halo2-mock-composite --field bn254`

Add `CompositeBackend` as a first step towards VadCop

---

backend/src/composite/mod.rs
backend/src/estark/mod.rs
backend/src/estark/polygon_wrapper.rs
backend/src/estark/starky_wrapper.rs
backend/src/halo2/circuit_builder.rs
backend/src/halo2/mock_prover.rs
backend/src/halo2/mod.rs
backend/src/halo2/prover.rs
backend/src/lib.rs
backend/src/plonky3/mod.rs
pipeline/src/pipeline.rs
plonky3/src/prover/mod.rs

Pulled out of #1470.
Receiving references, the `CompositeBackend` has no chance of changing the PIL or fixed columns before passing it to the wrapped backend. Using `Arc` fixed it, and is quite compatible with what is kept by `Pipeline` already.

`BackendFactory`: Use `Arc` instead of references

---

plonky3/src/circuit_builder.rs
plonky3/src/prover/mod.rs

(Replica of plonky3-secure-publics without commit bugs.) Securely implementing public inputs in Plonky3!
No longer requires the use of fixed columns by constraining every public value with 3 columns-- a decrementor starting from the row index of each exposed witness, an inverse to calculate the inverse of incrementor (0 if incrementor is 0), and a selector column constrained by a series of is_zero constraints to be 1 at the row index and 0 everywhere else.

Plonky3 secure publics2

---

pipeline/tests/powdr_std.rs
std/mod.asm
std/protocols/lookup.asm
std/protocols/permutation.asm
std/well_known.asm
test_data/asm/second_phase_hint.asm
test_data/std/lookup_via_challenges.asm
test_data/std/lookup_via_challenges_ext.asm
test_data/std/lookup_via_challenges_ext_simple.asm
test_data/std/permutation_via_challenges.asm
test_data/std/permutation_via_challenges_ext.asm

Includes #1511, but also removes the declarations of the challenges in the `permutation` and `lookup` modules.
With these changes, we never declare a column or challenge outside a machine namespace. This greatly simplifies #1470.

Remove all top level declarations

---

executor/src/witgen/block_processor.rs
executor/src/witgen/machines/block_machine.rs
pipeline/tests/asm.rs

Just like the `VmProcessor`, with this PR the `BlockProcessor` never processes an identity again that has been completed.
This should be a slight performance optimization (when the "default" sequence iterator is used), but more importantly it:
- Fixes #1385 
- Allows us to remove error-prone code (see below)
- Helps with witgen for stateful machines, like those who access memory

Block machines: Skip complete identities

---

riscv-executor/src/profiler.rs

use function id mapping in callgrind file to properly merge costs for each function

profiler fix for callgrind showing duplicate functions

---

book/src/architecture/linker.md
linker/src/lib.rs

Before: all machines must have the same degree, no degree gets replaced with the main degree
After: machines can have different degrees, no degree gets replaced with the main degree
We'll probably need another change to support dynamic degree but this should be enough for machines of different, static, degree.

Relax linker degree requirements

---

pipeline/tests/powdr_std.rs
std/machines/hash/mod.asm
std/machines/hash/poseidon_bn254.asm
std/machines/hash/poseidon_gl.asm
std/machines/hash/poseidon_gl_memory.asm
test_data/std/poseidon_gl_memory_test.asm

Implements #1055 for the Poseidon machines. Pulled out of #1508.
Specifically, this PR adds a new `PoseidonGLMemory` machine which receives 2 memory points and then:
- Reads 24 32-Bit words and packs them into 12 field elements
- Computes the Poseidon permutation (just like `PoseidonGL`)
- For each of the 4 output field elements, it:
- Invokes the `SplitGL` machine to get the canonical `u64` representation
- Writes the 8 32-Bit words to memory at the provided memory pointer
The read and write memory regions can even overlap! 🎉 
This should simplify our RISC-V machine, as the syscall already expects two memory pointers. We can simply pass it to the machine directly.
I started doing that in #1533, but I think it makes sense to wait until #1443 is merged.
To test:
```
cargo run -r pil …
```

Add `PoseidonGLMemory` machine

---

pil-analyzer/src/pil_analyzer.rs
pil-analyzer/src/type_builtins.rs
pil-analyzer/src/type_inference.rs

This small PR pulls the definition of the ExpectedType `constr_function_statement_type` from pil_analyzer and moves it into type builtins.

Constr functions expected type moved to builtins

---

pipeline/src/test_util.rs

Currently failing because there are proofs with no identities or witness columns.

[WIP] Composite backend add starks

---

pipeline/src/pipeline.rs
pipeline/src/test_util.rs
pipeline/tests/asm.rs
pipeline/tests/pil.rs
pipeline/tests/powdr_std.rs

Recent PRs (#1538, #1534) have significantly slowed down the CI, because they run every test twice, once with the "plain" backend and once with the `CompositeBackend`.
This PR makes sure that at least we only do the steps before (analyzing & optimizing PIL, fixed column computation, witness computation) only once, by making a "prepared" pipeline once and cloning it to test different backends.
This leads to a slight speed up in the tests.

Speed up tests

---

pipeline/tests/powdr_std.rs
std/math/fp2.asm
std/protocols/lookup.asm
std/protocols/permutation.asm

Some small refactorings of `lookup.asm` and `permutation.asm`.

Small refactoring of challenge-based protocols

---

backend/src/lib.rs
pipeline/src/test_util.rs
riscv/tests/riscv.rs

Needed for registers in memory. This will make some RISCV tests slower, but we won't use the normal EStarkDump backend anymore for such tests but rather composites backend only which should make them faster again.

fix riscv tests verification when using a composite backend

---

pipeline/src/test_util.rs

Fixes one of the tests that failed in the [last nightly run](https://github.com/powdr-labs/powdr/actions/runs/9949789019/job/27486609397).
To reproduce:
```
IS_NIGHTLY_TEST=true PILCOM=$(pwd)/pilcom/ cargo nextest run --all --features halo2 -E 'test(=vm_to_block_different_length)'
```

Fix vm_to_block_different_length test

---

pipeline/src/test_util.rs
riscv/src/continuations/bootloader.rs
riscv/tests/common/mod.rs
riscv/tests/instructions.rs
riscv/tests/riscv.rs

Also in preparation for registers in memory.
Removing the `public`s for continuations as discussed with @georgwiese , since those are not sound anyway and we might change it completely soon.

change riscv tests to use composite backends

---

backend/src/composite/mod.rs

This should help us to collect more data and get a better understanding of the factors that drive proof times and sizes.
Example:
```
$ cargo run pil test_data/asm/block_to_block.asm -o output -f --field bn254 --prove-with halo2-composite
...
Instantiating a composite backend with 2 machines:
* main:
* Number of witness columns: 3
* Number of fixed columns: 4
* Number of identities:
* Polynomial: 3
* main_arith:
* Number of witness columns: 4
* Number of fixed columns: 0
* Number of identities:
* Polynomial: 2
== Proving machine: main (size 8)
Starting proof generation...
Generating PK for snark...
Generating proof...
Time taken: 151.890834ms
Proof generation done.
==> Machine proof of 1753 bytes computed in 292.9045ms
== Proving machine: main_arith (size 8)
Starting proof generation... …
```

`CompositeBackend`: Improve logging

---

backend/src/lib.rs
pipeline/src/test_util.rs
pipeline/tests/asm.rs
pipeline/tests/pil.rs
pipeline/tests/powdr_std.rs
riscv/tests/common/mod.rs
riscv/tests/instructions.rs
riscv/tests/riscv.rs

This PR contains the following changes:
- I renamed a bunch of functions `verify_*` to `run_pilcom_*`, because I think it better describes what they do
- They all call `run_pilcom_with_backend_variant`, which works analogous to `gen_estark_proof_with_backend_variant` and `test_halo2_with_backend_variant`
- In functions like `run_pilcom_test_file` (previously `verify_test_file`), which are used for many tests, we now test both the monolithic and composite backend variant (but share the generated witness & constants). This is anlogous to `gen_estark_proof` and `test_halo2`
- In the RISC-V tests, we only test the composite variant, because with registers in memory (#1443) we don't expect the monolithic backend variant to work anymore.

Always test PILCOM + Composite

---

ast/src/analyzed/mod.rs
backend/src/composite/mod.rs

Computes & prints the maximum degree of any identity for every machine.
Example output for Keccak:
```
Instantiating a composite backend with 7 machines:
* main:
* Number of witness columns: 247
* Number of fixed columns: 195
* Maximum identity degree: 4
* Number of identities:
* Polynomial: 68
* Plookup: 16
* main_binary:
* Number of witness columns: 9
* Number of fixed columns: 2
* Maximum identity degree: 2
* Number of identities:
* Polynomial: 8
* main_binary_byte_binary:
* Number of witness columns: 1
* Number of fixed columns: 4
* Maximum identity degree: 1
* Number of identities:
* Polynomial: 1
* main_memory:
* Number of witness columns: 9
* Number of fixed columns: 2
* Maximum identity degree: 3
* Number of identities:
* Polynomial: 12
* Plookup: 2
* main_shift:
* Number of …
```

`CompositeBackend`: Print maximum degree per machine

---

pipeline/build.rs
pipeline/src/test_util.rs
pipeline/tests/asm.rs
pipeline/tests/pil.rs
pipeline/tests/powdr_std.rs

A new iteration of #1476.
These added tests demonstrate that #1488 is *mostly* solved (see [this comment](https://github.com/powdr-labs/powdr/issues/1488#issuecomment-2220759508) though): We parse, optimize, serialize, and re-parse all test files. A small number of test files need to be blacklisted for reasons explained in the comments.

Test re-parsing of all test files after optimization (with blacklist)

---

backend/src/composite/mod.rs
backend/src/composite/split.rs
executor/src/constant_evaluator/data_structures.rs
executor/src/constant_evaluator/mod.rs
executor/src/witgen/mod.rs
pipeline/tests/pil.rs
test_data/pil/vm_to_block_dynamic_length.pil

Fixes #1496
Also, a step towards #1572
This PR implements the steps needed in `CompositeBackend` to implement dynamic VADCOP.
In summary:
- If a machines size (a.k.a. "degree") is set to `None`, fixed columns are computed in all powers of too in some hard-coded range. This fixes #1572. As a result, machines with a size set to `None` are available in multiple sizes. If the size is explicitly set by the user, the machine is only available in that one size.
- Note that the ASM linker still sets the size of machines without a size. So, currently, this can only happen when coming from PIL directly.
- `CompositeBackend` instantiates a new backend for each machine *and size*:
- The verification key contains a key for each machine and size.
- When proving, it it uses the backend of whatever size …

Add dynamic VADCOP proving (no witgen yet)

---

pipeline/tests/asm.rs
test_data/asm/block_to_block_with_bus.asm

I started this in order to test #1603. However, due to #1604, currently only one machine has a bus so far. This should be fixed as part of #1604.
Then, what we would expect is that both machines have the same final accumulator values, assuming challenges are shared across machines.

Add test using a bus in each machine

---

plonky3/Cargo.toml

On my system, this brings proof time for Keccak with `plonky3-composite` on main from 180s -> 22s.

Activate `parallel` feature for Plonky3

---

backend/src/composite/mod.rs

Previously, arrays of columns were counted as 1.

`CompositeBackend`: Fix machine stats

---

book/src/architecture/linker.md
linker/src/lib.rs
pil-analyzer/src/condenser.rs
test_data/asm/dynamic_fixed_cols.asm

What we can have after this PR:
- only dynamic namespaces
- dynamic main, others dynamic or static
What we still cannot have:
- static main and another machines dynamic
The change to `_linker_first_step` can be reverted after #1565

Enable the linker to output dynamic namespaces

---

backend/src/halo2/mod.rs
plonky3/Cargo.toml
plonky3/src/stark.rs

This brings down proof and verification key sizes.
I didn't touch the eStark backends, because I think they need the JSON file and I also got some strange errors doing the same there (couldn't deserialize a serialized `StarkInfo`).

Plonky3 and Halo2: Use bincode for serialization

---

ast/src/analyzed/mod.rs
plonky3/src/circuit_builder.rs
plonky3/src/stark.rs

Addressing #1607 -- changing the implementation for constraining public values to reflect changes from #1543, as well as a slight refactoring of PowdrCircuit struct to include publics.

Plonky public values constrained by fixed columns

---

executor/src/witgen/mod.rs
pipeline/tests/asm.rs
test_data/asm/block_to_block_with_bus.asm

Fixes #1604
With this PR, we bypass machine detection during witness generation of stages > 0. See [this comment](https://github.com/powdr-labs/powdr/issues/1604#issuecomment-2257059636) for a motivation.
This currently needs to be tested manually, as follows:
```
$ RUST_LOG=trace cargo run pil test_data/asm/block_to_block_with_bus.asm -o output -f --field bn254 --prove-with halo2-mock
...
===== Summary for row 7:
main.acc1 = 20713437912485111384541749944547180564950035591542371144095269313127123163196
main.acc2 = 5162472027861336027760332823162682203738251621730423286600997430635718406729
main.z = 3
main.res = 9
main_arith.acc1 = 1174804959354163837704655800710094523598328808873663199602934873448685332421
main_arith.acc2 = 167257708439779391944860729220945928848101127786856110570972067559 …
```

Fix witgen for bus accumulators

---

riscv-executor/src/lib.rs
riscv/src/continuations.rs
riscv/tests/riscv_data/many_chunks/src/main.rs

Fixes https://github.com/powdr-labs/powdr/pull/1652
In continuations mode, a chunk_i's first row duplicates the last row of the previous chunk_j (if applicable). For many instructions that's fine, but for things like `x10 <== x10 - 1;` it's not, because the instruction ends up being executed twice and the values are just wrong in the new chunk. Therefore when creating the bootloader inputs for chunk_i (the later one) we need to use the second last state of the registers memory from chunk_j, which is done in this PR.

Fix registers memory used by bootloader inputs

---

riscv/src/code_gen.rs
riscv/tests/riscv.rs

Also adds a single test for bn254 in riscv, as a sanity check to catch these errors

wrong semicolon in bn254 codegen

---

executor/src/witgen/block_processor.rs
executor/src/witgen/generator.rs
executor/src/witgen/identity_processor.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/machines/double_sorted_witness_machine.rs
executor/src/witgen/machines/fixed_lookup_machine.rs
executor/src/witgen/machines/machine_extractor.rs
executor/src/witgen/machines/mod.rs
executor/src/witgen/machines/sorted_witness_machine.rs
executor/src/witgen/machines/write_once_memory.rs
executor/src/witgen/mod.rs
executor/src/witgen/processor.rs
test_data/asm/block_to_block_with_bus.asm

This PR turns the `FixedLookup` into a "normal" machine, i.e., it implements the `Machine` trait. This removes special handling of the fixed lookup in various places.
Changes:
- `Machine::take_witness_col_values` now takes a reference to `MutableState`, similar to `Machine::process_plookup`. With this, machines can still call other machines machines while finalizing. This is needed because some machines appear to call the fixed lookup when finalizing.
- To handle this correctly, I changed the code such that:
- Machines are finalized in the order in which they appear in the machines list (`FixedLookup` is the last machine)
- When finalizing, machines can access all *following* machines, but not the once before, as they are already finalized.
`FixedLookup` is still a weird machine, which is …

Turn `FixedLookup` into proper Machine

---

pipeline/src/lib.rs
pipeline/src/pipeline.rs

Remove the requirement for `Sync + Send` for serde data objects added to the pipeline

add non Send+Sync data to pipeline

---

.github/workflows/pr-tests.yml
backend/src/composite/split.rs
executor/src/constant_evaluator/mod.rs
executor/src/witgen/mod.rs

Pulled out of #1676, where it helps making the tests run faster.
I think this could possibly be removed by #1667 again.

Make `MAX_DEGREE_LOG` configurable

---

asm-to-pil/src/vm_to_constrained.rs
importer/src/path_canonicalizer.rs
importer/test_data/degree_not_found.asm
linker/src/lib.rs
pipeline/tests/asm.rs
test_data/asm/vm_args.asm
test_data/asm/vm_args_memory.asm
test_data/asm/vm_args_relative_path.asm
test_data/asm/vm_args_two_levels.asm
test_data/asm/vm_instr_param_mapping.asm
test_data/asm/vm_to_vm.asm
test_data/asm/vm_to_vm_to_block.asm
test_data/asm/vm_to_vm_to_vm.asm

When creating the ROM machine, give it a degree:
- if the VM has a degree, pass the same degree to its ROM machine (this is required to support the monolithic case where all degrees must match)
- otherwise, pass the length of the ROM

Set ROM degree

---

.github/workflows/nightly-tests.yml
pipeline/src/test_util.rs

This is similar to how we always run PILCOM in the Goldilocks setting, and shouldn't be expensive!

Run Halo2 MockProver even when `POWDR_GENERATE_PROOFS=false`

---

executor/src/witgen/generator.rs
executor/src/witgen/processor.rs
executor/src/witgen/vm_processor.rs
test_data/asm/vm_to_block_different_length.asm

Builds on #1666
With this PR, Witgen choses the minimum possible size of VMs (rounding to the next power of two after first detecting a loop):
```
$ MAX_DEGREE_LOG=10 cargo run -r pil test_data/asm/vm_to_block_different_length.asm -o output -f --field bn254 --prove-with halo2-composite
...
== Proving machine: main (size 128), stage 0
Starting proof generation...
Generating PK for snark...
Generating proof...
Time taken: 59.970083ms
Proof generation done.
==> Proof stage computed in 81.618417ms
== Proving machine: main__rom (size 8), stage 0
Starting proof generation...
Generating PK for snark...
Generating proof...
Time taken: 12.319334ms
Proof generation done.
==> Proof stage computed in 29.754417ms
== Proving machine: main_arith (size 32), stage 0
Starting proof generation...
Generating …
```

Downsize VMs when they reach a loop

---

executor/src/witgen/machines/double_sorted_witness_machine.rs
pipeline/tests/asm.rs
test_data/asm/dynamic_vadcop.asm

Builds on #1666 
Now, the memory machine is downsized to the smallest possible size:
```
$ MAX_DEGREE_LOG=10 cargo run -r pil test_data/asm/dynamic_vadcop.asm -o output -f --field bn254 --prove-with halo2-mock-composite
...
Running main machine for 1024 rows
[00:00:00 (ETA: 00:00:00)] ░░░░░░░░░░░░░░░░░░░░ 0% - Starting...                         Found loop with period 1 starting at row 100
[00:00:00 (ETA: 00:00:00)] ████████████████████ 100% - 280269 rows/s, 4205k identities/s, 94% progress
Resizing variable length machine 'Secondary machine 0: main_arith (BlockMachine)': 1024 -> 32 (rounded up from 3)
Resizing variable length machine 'Secondary machine 1: main_memory (DoubleSortedWitnesses)': 1024 -> 32 (rounded up from 4)
Witness generation took 0.005317875s
Writing output/commits.bin. …
```

Memory machine: Only use the necessary size

---

executor/src/witgen/global_constraints.rs

When making fixed lookup machines smaller in the RISC-V VM (#1683), I came across the issue that range-constraint lookups (e.g. `[two_bits] in [TWO_BITS]` where `TWO_BITS = [0, 1, 2, 3]`) where not recognized as such if the fixed column was *just* the right size (in the above example, `TWO_BITS = [0, 1, 2, 3, 0]` would have worked).

Witgen: Recognize range constraints in more cases

---

pil-analyzer/src/type_inference.rs
pil-analyzer/src/type_unifier.rs

Shifts the typevars counting and schema instantiation logic from TypeChecker to Unifier. 
This change simplifies schema instantiation so that the implementation of traits is cleaner.

Typevar count & schema instantiation to Unifier

---

std/machines/hash/poseidon_gl.asm
std/machines/hash/poseidon_gl_memory.asm

We recently decreased the degree of constraints in the Poseidon machine by introducing more witness columns, so that we make proofs with Plonky3.
But they don't need to be degree 2, degree 3 is low enough. In fact, the maximum degree in the machines is 3 anyway.
With this PR, the number of witness columns reduces significantly for `PoseidonGL` and `PoseidonGLMemory` (67 -> 43; 85 -> 61). We also save 24 polynomial identities.
To test:
```bash
cargo run -r pil test_data/std/poseidon_gl_memory_test.asm -o output -f --prove-with plonky3-composite
cargo run -r pil test_data/std/poseidon_gl_test.asm -o output -f --prove-with plonky3-composite
```

Reduce witness columns in Poseidon machine by slightly increasing the constraint degree

---

pipeline/src/pipeline.rs

Allow the pipeline to setup and cache the backend before calls to prove/verify.
`Backend` objects are not cloneable, so upon cloning the pipeline, the instance is cleared (but will be regenerated when needed).

Backend artifact

---

importer/test_data/instruction.asm
importer/test_data/instruction.expected.asm
test_data/asm/vm_args_relative_path.asm

Now that #1694 is merged we don't need convoluted module trees.

Simplify test files after #1694

---

number/Cargo.toml

point `p3-baby-bear` to our `p3` fork  (like the other `p3` dependencies in the project)

point baby-bear to our p3 fork

---

cli-rs/src/main.rs
riscv/src/continuations.rs

this way we can get more information back (total trace length for now)

`rust_continuations_dry_run` return type

---

riscv-runtime/Cargo.toml
riscv-runtime/src/entropy_source.rs
riscv-runtime/src/getrandom.rs
riscv-runtime/src/io.rs
riscv-runtime/src/lib.rs
riscv-runtime/src/std_support.rs

There are two interfaces we must provide: the one from `getrandom` crate and the one used internally by `std`.

Unifying implementation of fake random number generator.

---

ast/src/parsed/asm.rs
ast/src/parsed/types.rs

Small PR that adds the `Hash` trait to `Type` and some of its internal types.
Needed to be able to store `Vec<type>` in order to solve trait implementations based on its `type_args`.

Add Hash trait for Type

---

.github/workflows/pr-tests.yml

when a new commit to branch triggers a build and tests, cancel any currently running (now obsolete) workflows for the same branch

cancel old workflows for the same branch

---

ast/src/parsed/display.rs
ast/src/parsed/mod.rs
importer/test_data/instruction.expected.asm
linker/src/lib.rs
parser/src/lib.rs
pil-analyzer/tests/condenser.rs
pil-analyzer/tests/parse_display.rs
pil-analyzer/tests/side_effects.rs
pilopt/src/lib.rs

This PR fixes issue #1728.
1) Removes the blank space that was printed even if the body of the blocks was empty.
2) Adds the Precedence trait to LambdaExpressions to correctly handle the use of parentheses.

LambdaExpression formatting

---

plonky3/src/params.rs

We're using a Poseidon transcript, so it seems like this comment is wrong.

Correct source for Plonky3 parameters

---

plonky3/src/circuit_builder.rs

On the Keccak test (and with the `RUSTFLAGS='-Ctarget-cpu=native'` flag), this brings down the proof time from 7.2 to 4.4s. The share for computing the quotient polynomial drops from > 50% for some machines to < 10% for all machines.

Plonky3 circuit builder: Cache computations on Analyzed PIL

---

book/src/installation.md

This makes sure that we use AVX instructions when available. Seems to speed up Plonky3 proofs (slightly for Goldilocks and 30-50% for BabyBear).

Update docs to mention `RUSTFLAGS`

---

backend/src/plonky3/mod.rs
plonky3/Cargo.toml
plonky3/src/lib.rs
plonky3/src/mersenne_31.rs

Analogously to our Plonky3 BabyBear support, I added support for M31 by using the parameters they use in [their Keccak example](https://github.com/Plonky3/Plonky3/blob/7c5deb0eab7191a97f7bb088637c1a68b2e6eb68/keccak-air/examples/prove_m31_poseidon2.rs).
To test:
```bash
cargo run pil test_data/pil/fibonacci.pil -o output -f --field m31 --prove-with plonky3
```

Add M31 support for Plonky3 backend

---

std/protocols/lookup.asm
test_data/std/lookup_via_challenges.asm
test_data/std/lookup_via_challenges_ext.asm
test_data/std/lookup_via_challenges_ext_simple.asm

Since we can now create constant columns inside `constr` functions, we don't need to pass `is_first` any more.

Create is_first inside the lookup.

---

test_data/asm/bit_access.asm
test_data/asm/functional_instructions.asm
test_data/std/bus_lookup_via_challenges.asm
test_data/std/bus_lookup_via_challenges_ext.asm
test_data/std/bus_permutation_via_challenges.asm
test_data/std/bus_permutation_via_challenges_ext.asm
test_data/std/lookup_via_challenges.asm
test_data/std/lookup_via_challenges_ext.asm
test_data/std/lookup_via_challenges_ext_simple.asm
test_data/std/permutation_via_challenges.asm
test_data/std/permutation_via_challenges_ext.asm

We can now use the `$`, `in`, `is` and `connect` operators in any expression. Remember that `$` needs to be used when you want to have a selector.

Use operators for lookups.

---

pil-analyzer/src/statement_processor.rs

`handle_symbol_definition` in `pil-analyzer/src/statement_processor.rs` is becoming to long and it will get worst after we add structs. 
This PR separate every case inside its own function to simplify and improve readability.

Cleaner handle_symbol_definition

---

.gitignore

This way, one can add a `.cargo/config.toml` with the content:
```toml
[build]
rustflags = ["-C", "target-cpu=native"]
```
and doesn't have to think of setting it manually.

Git ignore `.cargo`

---

pil-analyzer/src/condenser.rs
pil-analyzer/src/evaluator.rs
pil-analyzer/tests/condenser.rs
pipeline/src/lib.rs
test_data/std/lookup_via_challenges.asm

After this, we can process prover functions that capture enum values and challenges. This is needed to improve the lookup transformation functions.

Support capturing enum values and challenges

---

ast/src/analyzed/display.rs
ast/src/analyzed/mod.rs
backend/src/composite/split.rs
backend/src/estark/json_exporter/expression_counter.rs
backend/src/estark/json_exporter/mod.rs
executor/src/constant_evaluator/mod.rs
pil-analyzer/src/condenser.rs
pil-analyzer/src/evaluator.rs
pil-analyzer/src/pil_analyzer.rs
pil-analyzer/src/statement_processor.rs

At the on-site, we introduced operators for all lookup-like constraints. This means that `[x, y] in s $ [a, b];` is not parsed as a lookup identity any more, but just as a regular expression with binary operators. The whole concept of a lookup or identity as a rust type is now only present after the condenser has run. Because of that, we can remove a lot of code that was concerned with parsed identities.
Since prover functions were introduced, we can have both constraints and prover functions at statement level. Because of that I extended the concept of "identity" (which we partly renamed to "constraint" already) to "proof item". A proof item is either a constraint or a prover function. Later on, we might also include fixed columns, challenges, etc.

Simplify parsed identities and introduce the concept of proof item.

---

ast/src/analyzed/mod.rs
ast/src/parsed/display.rs
ast/src/parsed/mod.rs
importer/src/path_canonicalizer.rs
parser/src/powdr.lalrpop
pil-analyzer/src/statement_processor.rs

Since we also need name and type pairs for structs, it makes sense to rename `TraitFunction` to something more general (`NamedType` in this case).
There are also `NamedExpressions` and everything could be combined into a `NamedElement` or something similar that covers both cases. Personally I prefer this option, but the discussion is open.

Rename trait functions

---

number/Cargo.toml
plonky3/Cargo.toml

We merged plonky3 challenges in our fork.
This breaks main.
Point plonky3 to the commit before the merge.
This will be removed by #1737

Point plonky3 to previous version

---

.github/workflows/build-cache.yml
.github/workflows/nightly-tests.yml
.github/workflows/pr-tests.yml
airgen/src/lib.rs
backend/src/field_filter.rs
executor/src/witgen/identity_processor.rs
executor/src/witgen/machines/fixed_lookup_machine.rs
executor/src/witgen/util.rs
executor/src/witgen/vm_processor.rs
riscv-executor/src/poseidon_gl.rs
riscv/Cargo.toml
riscv/src/asm/mod.rs
riscv/src/asm/parser.rs
riscv/src/elf/mod.rs
rust-toolchain.toml

This is a prerequisite for #1845 
TODO:

Upgrade Rust to 1.81

---

riscv-executor/src/lib.rs
riscv/benches/executor_benchmark.rs
riscv/src/continuations.rs
riscv/src/continuations/bootloader.rs

Bootloader/continuations now handle field elements directly instead of `Elem`. 
The bootloader can't use u32 directly because it uses register memory from the previous chunk, which may be holding values larger than 32-bit depending where the execution stops (i.e., negative Elem::Binaries or Elem::Field).

make `Elem` private to the RISCV executor

---

number/Cargo.toml
plonky3/Cargo.toml
plonky3/src/check_constraints.rs
plonky3/src/circuit_builder.rs
plonky3/src/folder.rs
plonky3/src/lib.rs
plonky3/src/params/baby_bear.rs
plonky3/src/params/goldilocks.rs
plonky3/src/params/mersenne_31.rs
plonky3/src/proof.rs
plonky3/src/prover.rs
plonky3/src/stark.rs
plonky3/src/symbolic_builder.rs
plonky3/src/traits.rs
plonky3/src/verifier.rs

This PR is only a copy paste from https://github.com/powdr-labs/plonky3 with the following exceptions:
- only the files that differ from uni-stark are copied over. Any references to other modules are targeting upstream uni-stark
- the `preprocessed_width` function is moved to the `MultiStageAir` trait from `BaseAir` to avoid changes to `p3-air`
- upstream uni-stark is nostd. Our wrapper uses things like hashmaps and mutexes, so for now I commented out `nostd`
- `lib.rs` is a merge of the existing lib.rs and that of our uni-stark fork
- the `prove` function is removed, as it is only there for compatibility with uni-stark tests
- `FieldMerkleTreeMmcs` was [renamed](https://github.com/Plonky3/Plonky3/commit/84a13454ea9a9ea82489551f081e24072e1f3e98) to `MerkleTreeMmcs` in plonky3 since we …

Import p3 implementation

---

ast/src/analyzed/mod.rs
backend/src/composite/split.rs
backend/src/halo2/circuit_builder.rs
backend/src/plonky3/mod.rs
executor/src/witgen/mod.rs
pilopt/src/lib.rs
pipeline/src/util.rs
plonky3/src/circuit_builder.rs

Instead of returning a vector and turning it into an iterator, return an iterator right away.

Return iterator instead.

---

executor/src/witgen/global_constraints.rs

when run this command: 
`cargo run pil test_data/asm/book/hello_world.asm --inputs 0 -o output --field m31 --prove-with plonky3 -f`
it gets error: 
```
thread 'main' panicked at 
powdr/executor/src/witgen/global_constraints.rs:195:37:
attempt to subtract with overflow
```
The problem is in function
```
fn smallest_period_candidate<T: FieldElement>(fixed: &[T]) -> Option<u64> {
if fixed.first() != Some(&0.into()) {
return None;
}
(1..63).find(|bit| fixed.last() == Some(&((1u64 << bit) - 1).into()))
}
```
when using Mersenne31 field (prime: 2^31 -1) and the last element of fixed is 0, it is equivalent to 2^31-1, then the function return bit=31 
and bit=31 overflow at this line:
`let mask = T::Integer::from(((1 << bit) - 1) as u64);`
in function process_fixed_column, as 1 is by default to be …

fix mersenne31 overflow

---

.github/workflows/pr-tests.yml
backend/src/halo2/prover.rs
book/src/powdr_crate.md
book/src/publics.md
powdr-test/examples/sqrt_with_publics.rs
powdr-test/src/lib.rs

Fixes a bug where circuits with publics can't be verified properly. This was caused by a difference in the circuit when the verification key is generated (without witnesses) vs when the user requests a proof (with).

fix publics bug halo2

---

plonky3/src/params/baby_bear.rs

This is just so that the constants of external rounds doesn't repeat in the internal rounds.

Use a different RNG seed for Poseidon2 constants.

---

jit-compiler/src/compiler.rs
jit-compiler/src/lib.rs

The JIT compiler errors were spamming the log. This reduces the verbosity in the default log level, but also prints all symbols that failed to compile.

Change jit error level to debug.

---

jit-compiler/src/codegen.rs
jit-compiler/tests/execution.rs

This fixes the type of the panic builtin implementation in rust.
It does not have a test that actually executes panic, because we cannot carry the panic across the `extern "C"` boundary - this has to be implemented at some point in a different PR.

Fix panic builtin.

---

jit-compiler/src/codegen.rs
jit-compiler/tests/execution.rs

The pattern matching code for enums used comma-separated variables instead of proper tuples.
Also type constructors can only be `Callable::Fn` when they take a single tuple of field values instead of multiple parameters.

JIT: Fix pattern matching for enums.

---

ast/src/object/mod.rs

After the last refactor, it seems to me that `TypeOrExpression` is no longer needed. This PR deletes the enum.

Remove unused enum (TypeOrExpression)

---

.github/workflows/build-cache.yml
.github/workflows/pr-tests.yml

Working on the assumption that there is a race condition between the delete command and the push new cache command, that is why some days we have no cache.

Replacing the old cache without deleting it first.

---

README.md

Judging from the build failures of https://github.com/powdr-labs/powdr/pull/1686 our requests to https://opensource.org/license/MIT are being blocked.
Ignore the license URLs when checking the links.

Ignore licenses in link check

---

backend/src/plonky3/mod.rs
book/src/backends/plonky3.md
cli-rs/src/main.rs
cli-rs/src/util.rs
cli/src/main.rs
cli/src/util.rs
number/Cargo.toml
number/src/koala_bear.rs
number/src/lib.rs
number/src/traits.rs
pipeline/src/test_util.rs
pipeline/tests/asm.rs
pipeline/tests/powdr_std.rs
plonky3/Cargo.toml
plonky3/src/params/koala_bear.rs
plonky3/src/params/mod.rs
riscv/src/code_gen.rs
riscv/src/continuations/bootloader.rs
riscv/src/large_field/code_gen.rs
riscv/src/lib.rs
riscv/tests/common/mod.rs

The KoalaBear prime ($2^{31} - 2^{24} + 1$) is very similar to the BabyBear prime ($2^{31} - 2^{27} + 1$), but allows for a more efficient S-Box in Poseidon2 ($x^3$ instead of $x^7$). It should be slightly faster to evaluate and significantly faster to prove recursively. For some reason, I [saw a much more significant advantage](https://gist.github.com/georgwiese/211d14c860c16cc4e1fbde7dc374af35) when running the Plonky3 examples.
One downside of BabyBear is that it supports smaller traces, e.g. up to $2^{23}$ rows with a degree bound of 3. For example, `test_data/pil/fibonacci.pil` fails for larger instances.
This PR supports KoalaBear end-to-end:
```bash
cargo run -r --bin powdr-rs compile riscv/tests/riscv_data/keccak -o output --field kb
cargo run -r --features plonky3,halo2 pil …
```

Add KoalaBear field 

---

ast/src/parsed/display.rs
parser/src/lib.rs
pil-analyzer/tests/parse_display.rs

If we re-format `impl X<(int -> int)> { ... }`, the parentheses are removed without this change and it does not parse.

Fix type arg formatting for trait impl.

---

ast/src/parsed/asm.rs
importer/src/path_canonicalizer.rs
importer/test_data/trait_ref.asm
importer/test_data/trait_ref.expected.asm

Lookup of functions in traits was not implemented for asm, only for pil.

Fix trait function lookup in asm.

---

std/constraints.asm
std/prelude.asm
std/protocols/lookup.asm

A miniature version of #1378, adding only annotations for a generic lookup & permutation. This should be enough to get us to a sound version of VADCOP.
I added the annotation to the `std::protocols::lookup::lookup` function. We would need it to other functions in the same module as well, but I think we can get this example working end-to-end first (in case we decide that the annotation type needs to change for some reason).

Add PhantomLookup and PhantomPermutation to Constr

---

riscv-executor/src/lib.rs
riscv/src/lib.rs
riscv/tests/riscv.rs

- fix calls from the riscv executor into the profiler
- build guest programs with debug info.
- adds a sanity check test to catch when it trivially breaks again

Profiler fix

---

riscv/src/continuations.rs

I ran into this unwrapping a None when using continuations with a very low max degree. It's kinda hard to trigger without triggering a bunch of other issues, but I think this fix is enough for now: if a register is never used it is not contained in the snapshot, so it should be 0.

Fix small continuations issue

---

powdr/src/lib.rs
riscv-executor/src/lib.rs
riscv/benches/executor_benchmark.rs
riscv/src/large_field/code_gen.rs
riscv/src/lib.rs
riscv/tests/common/mod.rs
riscv/tests/riscv.rs

Depends on https://github.com/powdr-labs/powdr/pull/1946

Use lower max degree by default and let user change it

---

backend/Cargo.toml
backend/src/lib.rs
cli-rs/Cargo.toml
cli/Cargo.toml
pipeline/Cargo.toml
pipeline/src/test_util.rs
pipeline/tests/asm.rs
pipeline/tests/powdr_std.rs

Currently the users end up always compiling starky as well. This removes that.
I think the CI tests should not change here because we run it with `--all-features`.
I also made p3 default in the cli and cli-rs crates.

make starky optional

---

.github/workflows/build-cache.yml
.github/workflows/pr-tests.yml

The same build steps is now performed in both cache build and PR build.

Attempt to make cache more useful for PR builds.

---

ast/src/analyzed/display.rs
ast/src/analyzed/mod.rs
ast/src/parsed/display.rs
backend-utils/src/lib.rs
backend/src/estark/json_exporter/expression_counter.rs
backend/src/estark/json_exporter/mod.rs
pil-analyzer/src/condenser.rs
pil-analyzer/src/pil_analyzer.rs
pil-analyzer/src/traits_resolver.rs
pil-analyzer/tests/parse_display.rs
pil-analyzer/tests/types.rs

Before this PR, the list of trait implementations was not present in Analyzed, but we need them for re-printing the PIL (and other things).
This PR also contains a simplification in that it only keeps a list of all trait impls, not sorted into which trait they implement. This information is only relevant during trait impl solving, where we re-build that data structure. Keeping the pre-sorted layout would make re-printing in source order much more difficult.
And now it also formats paths to the current namespace properly.

Properly re-print trait impls.

---

ast/src/analyzed/display.rs
ast/src/analyzed/mod.rs
backend/src/estark/json_exporter/expression_counter.rs
backend/src/estark/json_exporter/mod.rs
backend/src/halo2/circuit_builder.rs
executor/src/witgen/global_constraints.rs
executor/src/witgen/identity_processor.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/machines/double_sorted_witness_machine_16.rs
executor/src/witgen/machines/double_sorted_witness_machine_32.rs
executor/src/witgen/machines/fixed_lookup_machine.rs
executor/src/witgen/machines/machine_extractor.rs
executor/src/witgen/machines/sorted_witness_machine.rs
executor/src/witgen/machines/write_once_memory.rs
executor/src/witgen/processor.rs
pil-analyzer/src/condenser.rs
pil-analyzer/tests/condenser.rs
pilopt/src/lib.rs

We represent lookup and permutation selectors as `Option<AlgebraicExpression<T>>`.
The issue with this is that there are two ways to represent 1: `Some(1)` and `None`.
This leads to issues in witgen where we check `is_none` but not against `Some(1)`.
This already led to an awkward optimizer step which reduces one to the other so that witgen only sees one of the two options.
This PR makes the selector non-optional. Therefore, 1 is only 1. Display is adjusted to not print the selector if it prints to "1". This str-level comparison is there to avoid introducing invasive bounds on T which would contaminate everything.

Make selector non-optional in analyzed

---

pipeline/tests/powdr_std.rs
plonky3/src/circuit_builder.rs
std/protocols/fingerprint.asm

When building the `ConstraintSystem` struct which caches `Analyzed`, we incorrectly count usage of the same challenge many times. Use a set to deduplicate.
Enable the relevant tests to trigger phase 2 witgen.

Fix p3 challenge collection

---

cli/src/main.rs
number/src/serialize.rs
pipeline/src/pipeline.rs
riscv/tests/riscv.rs
test_data/pil/external_witgen.pil

This PR does two things:
- make `--export-csv` not export fixed columns, so it can be directly used as external witness
- skip witness generation when all witness columns are provided externally

fix `--export-csv` and skip witgen when full witness is provided

---

pipeline/tests/powdr_std.rs
std/math/fp2.asm

This should lead to performance improvements in the new implementation of `fingerprint`.
From the chat:
> Currently we have:
> `mult_ext = (Fp2::Fp2(a0, a1), Fp2::Fp2(b0, b1)) => Fp2::Fp2(a0 * b0 + 11 * a1 * b1, a1 * b0 + a0 * b1)`
> 
> So implementing squaring as:
> `square_ext1 = (Fp2::Fp2(a0, a1)) => mult_ext(Fp2::Fp2(a0, a1), Fp2::Fp2(a0, a1))`
> 
> Evaluates to `Fp2::Fp2(a0 * a0 + 11 * a1 * a1, a1 * a0 + a0 * a1)`.
> 
> But we can implement it directly do return a shorter equivalent expression:
> `square_ext2 = (Fp2::Fp2(a0, a1)) => Fp2::Fp2(a0 * a0 + 11 * a1 * a1, 2 * a1 * a0)`
>
> Each application of square_ext1 will 4x the expression (because both a0 and a1 are repeated 4 times), so after squaring log(n) times, we'll have an expression of size $4^{log2(n)} =n^2$!
In contrast, …

Add `std::math::fp2::square_ext`

---

.github/workflows/build-cache.yml
.github/workflows/dead-links.yml
.github/workflows/deploy-book.yml
.github/workflows/nightly-tests.yml
.github/workflows/pr-tests.yml
cargo-powdr/template/Cargo.toml.template
cargo-powdr/template/README.md
cargo-powdr/template/guest/Cargo.toml.template
cargo-powdr/template/src/main.rs
examples/keccak/README.md

This PR fixes line breaks for some md files and adjusts the code and README of cargo-powdr to not talk about the MAX_DEGREE_LOG stuff

remove MAX_DEGREE stuff from cargo-powdr

---

plonky3/src/circuit_builder.rs

Following discussions about large expressions with a lot of common subexpressions, support intermediate polynomials in plonky3 so that these subexpressions can be explicitly declared as intermediate polynomials and cached.
With the following program:
```rust
let N: int = 2**15;
machine Main with degree: N {
col witness a;
let i0: inter = a + a;
let i1: inter = i0 + i0;
let i2: inter = i1 + i1;
let i3: inter = i2 + i2;
let i4: inter = i3 + i3;
let i5: inter = i4 + i4;
let i6: inter = i5 + i5;
let i7: inter = i6 + i6;
let i8: inter = i7 + i7;
let i9: inter = i8 + i8;
let i10: inter = i9 + i9;
let i11: inter = i10 + i10;
let i12: inter = i11 + i11;
let i13: inter = i12 + i12;
let i14: inter = i13 + i13;
let i15: inter = i14 + i14;
i15 = 78;
}
```
On main, 3s on quotient polynomial: …

Support intermediate polynomials in p3

---

pil-analyzer/src/expression_processor.rs

I was about to add `Results` to the expression processor and realized that these two functions are never called and useless.

Expression Processor: Unused functions

---

book/src/frontends/zk-continuations.md
book/src/hello_world_cli.md
book/src/pil/builtins.md

**Changes include:**
- Corrected typos in `zk-continuations.md`
- Removed duplicate `<: T, T ->` in `builtins.md`
- Fixed minor typo in `hello_world_cli.md`

chore: typo corrections

---

pipeline/tests/asm.rs

This test expects a panic, but when halo2 is off, verification is a noop, so it doesn't panic, so the test fails. I run into this locally and it's confusing me every time.
Only run the test when halo2 is on.

Only run test when halo2 is active

---

executor/src/witgen/machines/fixed_lookup_machine.rs
executor/src/witgen/mod.rs
pipeline/tests/powdr_std.rs
std/protocols/lookup.asm
test_data/std/lookup_via_challenges.asm
test_data/std/lookup_via_challenges_range_constraint.asm

No need to have the user create the multiplicity column anymore.

PIL LogUp implementation: Generate multiplicity column

---

ast/src/analyzed/display.rs
ast/src/parsed/asm.rs
pil-analyzer/src/pil_analyzer.rs
pil-analyzer/src/statement_processor.rs
pil-analyzer/tests/parse_display.rs

We inherited from polygon the speciality that publics are always global even if declared inside a namespace. This PR changes that and treats publics just as any other definition. It also does some clean-up in that the degrees of the namespaces are first determined in the Display function and not only while printing. This allows declarations without degree to be used as a first declaration in a namespace.

Put publics inside namespace.

---

ast/src/analyzed/mod.rs
backend/src/plonky3/stark.rs
plonky3/src/circuit_builder.rs
plonky3/src/prover.rs

p3 publics currently incorrectly use the column name as a key. This explains why this was working as long as all public inputs were the same column and value, even with different rows.

Fix p3 publics

---

executor/src/witgen/machines/fixed_lookup_machine.rs
executor/src/witgen/mod.rs

The change from storing just the row to storing the row values changes the time reported for the fixed machine on the keccak example from 1.5s to 1.2 seconds.
The pc lookup plus copying the values from the columns took 3700 ns, now the lookup takes 500 ns.
Using a hash map takes it down to 1 second.
Current numbers:
```
460 ns: Evaluating LHS
621 ns: Splitting into known and unknown values
201 ns: Actual index lookup
1182 ns: creating the EvalValue result
```
Note that the "1.5 to 1.0 seconds" overall speed improvement includes the time it takes to build the lookup table.

Improve fixed lookup

---

executor/src/witgen/global_constraints.rs
executor/src/witgen/mod.rs
pipeline/tests/powdr_std.rs

Generates multiplicity columns for global range constraints, by doing a pass over the data at the very and of witness generation.
```
$ RUST_LOG=debug cargo run pil test_data/std/lookup_via_challenges_range_constraint.asm -o output -f --prove-with plonky3
...
Determined the following global range constraints:
main::x_low: [0, 7] & 0x7
main::x_high: [0, 7] & 0x7
Determined the following identities to be purely bit/range constraints:
Constr::PhantomLookup((Option::None, Option::None), [(main::x_low, main::BIT3)], main::multiplicities);
Constr::PhantomLookup((Option::None, Option::None), [(main::x_high, main::BIT3)], main::multiplicities_1);
Recorded the following range constraint multiplicity columns:
main::x_low -> main::multiplicities
main::x_high -> main::multiplicities_1
Running main …
```

Multiplicity witgen for range constraints

---

executor/src/witgen/eval_result.rs
executor/src/witgen/machines/fixed_lookup_machine.rs
executor/src/witgen/machines/mod.rs

This PR introduces a more "direct" way to perform a lookup during witness generation. It removes the concept of `EvalValue`, which is a list of "updates", and instead requests the called machine to directly fill in mutable pointers to field elements.
The goal is to use this (hopefully) faster interface if
- the lookup can be fully solved in a single call
- no cell-based range constraints are needed
If the LHS of the lookup consists of direct polynomial references (or next references), the caller can pass a pointer to the final table and does not need to move data around any further.
Some numbers:
For the "keccak test", and only looking at the PC lookup, we get:
Inside `process_plookup_internal`:
40 ns: preparing the `data` and `values` arrays
290 ns: call to process_lookup_direct
1300 ns: …

Introduce direct lookup.

---

executor/src/constant_evaluator/mod.rs

I noticed that constant evaluation takes a very long time. With this logging, it is easier to see why, e.g. for the Rust Keccak example:
```
Generated values for main_poseidon_gl::CLK[0] (32..4194304) in 5.11s
Generated values for main_poseidon_gl::CLK[1] (32..4194304) in 5.77s
Generated values for main_poseidon_gl::CLK[2] (32..4194304) in 5.39s
Generated values for main_poseidon_gl::CLK[3] (32..4194304) in 5.12s
Generated values for main_poseidon_gl::CLK[4] (32..4194304) in 6.32s
Generated values for main_poseidon_gl::CLK[5] (32..4194304) in 6.25s
Generated values for main_poseidon_gl::CLK[6] (32..4194304) in 4.92s
Generated values for main_poseidon_gl::CLK[7] (32..4194304) in 5.48s
Generated values for main_poseidon_gl::CLK[8] (32..4194304) in 5.39s
Generated values for …
```

Improve constant evaluation logging

---

plonky3/src/params/baby_bear.rs
plonky3/src/params/goldilocks.rs
plonky3/src/params/koala_bear.rs
plonky3/src/params/mersenne_31.rs
plonky3/src/params/mod.rs
plonky3/src/prover.rs

To test, change [this line](https://github.com/powdr-labs/powdr/blob/3f74b7e0ec36b71a88ff3db6f64af5a6482e9903/std/machines/hash/poseidon_gl.asm#L73) to:
`array::zip(x7, array::map(a, |a| a * a * a * a * a * a * a), |x7, expected| x7 = expected);`
and try to prove:
```
$ cargo run pil test_data/std/poseidon_gl_test.asm -o output -f --prove-with plonky3
...
Backend setup for plonky3...
Setup took 0.15889554s
thread 'main' panicked at /Users/georg/coding/powdr/plonky3/src/prover.rs:425:17:
Table main_poseidon has a constraint of degree 7 which exceeds the degree bound of 3.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
whereas on `main`, you'd get:
```
Backend setup for plonky3...
Setup took 0.15057254s
thread 'main' panicked at …
```

Improve Plonky3 error when degree bound is exceeded

---

backend/Cargo.toml
backend/src/lib.rs

Build with feature `estark-polygon` was broken without `estark-starky`.
Now each work independently of the other.

Fix build of eStark related features.

---

executor/src/witgen/data_structures/finalizable_data.rs
executor/src/witgen/generator.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/processor.rs
executor/src/witgen/rows.rs

Change FinalizableData so that finalized rows are stored as one contiguous array instead of an array of arrays. Furthermore, if the column IDs are a contiguous sequence, the row will only have as many field elements as there are columns.
I don't expect this PR to improve performance, but we can directly re-use this data structure for JIT-compiled executors (which need contiguous cell data, it was one of the main performance boosts). This means we can decide at runtime if we want to use a JIT-compiled executor or the interpreted one.
And this in turn allows us to delay the actual JIT-compiling until we get a request to the machine in the form of a bit field of known columns in the lookup. And once we know which columns are known, we can try to JIT-compile. If it fails, we store that this …

Use contiguous data for finalized rows.

---

std/machines/small_field/binary.asm
std/well_known.asm

A latch can be any expression, including `1`, which is so well known, it's even a built-in.

Remove `std::well_known::one`

---

ast/src/analyzed/mod.rs

I checked who uses `Analyzed::identities_with_inlined_intermediate_polynomials` and why. I found [this use](https://github.com/powdr-labs/powdr/blob/016fb2a9fdbe1d3dc2c7e2682cea437c0a48d884/backend/src/composite/mod.rs#L175) in `CompositeBackend` to print the maximal constraint degree.
The usage is correct, but doing the same on the non-inlined identities would not. So I think we should have an assertion here.

Add assertion in `AlgebraicExpression::degree`

---

executor/src/witgen/machines/block_machine.rs
executor/src/witgen/machines/double_sorted_witness_machine_16.rs
executor/src/witgen/machines/double_sorted_witness_machine_32.rs
parser/src/lib.rs
pipeline/tests/asm.rs
test_data/asm/block_machine_exact_number_of_rows.asm

Before this PR, we used to panic if the number of rows in a block machine was just enough to fit the needed number of blocks. This PR fixes it.

Block Machine: Handle case where number of rows is just enough

---

executor/src/witgen/eval_result.rs
executor/src/witgen/expression_evaluator.rs
executor/src/witgen/global_constraints.rs
executor/src/witgen/identity_processor.rs
executor/src/witgen/machines/fixed_lookup_machine.rs
executor/src/witgen/machines/machine_extractor.rs
executor/src/witgen/machines/sorted_witness_machine.rs
executor/src/witgen/mod.rs
executor/src/witgen/query_processor.rs
executor/src/witgen/rows.rs
executor/src/witgen/symbolic_witness_evaluator.rs

Completes a task in #2009.
With this PR, we no longer rely on `Analyzed::identities_with_inlined_intermediate_polynomials()`, which can produce exponentially large expressions in some cases. Instead, intermediate polynomials are evaluated on demand and cached. Thibaut's example from #1995 speeds up massively with this PR.

Witgen: Handle intermediate polynomials

---

backend/Cargo.toml
backend/src/lib.rs
backend/src/mock/constraint_checker.rs
backend/src/mock/evaluator.rs
backend/src/mock/mod.rs
executor/src/witgen/affine_expression.rs
executor/src/witgen/mod.rs
pipeline/src/test_util.rs

Adds a basic mock prover that simply asserts that all constraints are satisfied.
This first version has the following features:
- Polynomial constraints are verified.
- Speed is reasonable. For example, the RISC-V Keccak example is verified in 0.087s.
- Error messages are good: It prints the relevant constraint and row, and all relevant assignments.
Missing features:
- Machine connections (i.e., any lookups or permutations) are not yet validated.
- Later-stage witnesses are not yet validated.
Caveats:
- We rely on `powdr_backend_utils::split_pil`, so lookups / permutations *within* a namespace are ignored.
Example:
```
$ cargo run pil test_data/pil/fibonacci.pil -o output -f --prove-with mock
```

Add `MockBackend`

---

executor/src/witgen/global_constraints.rs

When writing #2119, I came across another issue in witgen. When running this file on `main`:
```rs
namespace main(4);
// Two bit-constrained witness columns
// In practice, bit1 is always one (but this is not constrained)
col witness bit1(i) query Query::Hint(1);
col witness bit2;
bit1 * (bit1 - 1) = 0;
bit2 * (bit2 - 1) = 0;
// Constrain their sum to be binary as well.
// This ensures that at most one of the two bits is set.
// Therefore, bit2 is always zero.
let bit_sum;
bit_sum = bit1 + bit2;
bit_sum * (bit_sum - 1) = 0;
// Some witness that depends on bit2.
col witness foo;
foo = bit2 * 42 + (1 - bit2) * 43;
```
I'm getting
```
thread 'main' panicked at /Users/georg/coding/powdr/executor/src/witgen/global_constraints.rs:258:17:
assertion failed: known_constraints.insert(p, …
```

Fix failing assertion in witgen

---

Cargo.toml
backend-utils/Cargo.toml
backend-utils/src/lib.rs
executor-utils/Cargo.toml
executor-utils/src/lib.rs
executor/Cargo.toml
executor/src/constant_evaluator/data_structures.rs
executor/src/witgen/mod.rs
plonky3/Cargo.toml
plonky3/src/circuit_builder.rs

To make the plonky3 verifier module simpler for recursion

remove powdr-executor dependency from backend-utils and plonky3

---

pipeline/src/test_util.rs
pipeline/tests/pil.rs

```console
cargo test -p powdr-pipeline
```
currently fails because it expects panics which cannot happen if the features are off.
This PR fixes it.

Fix pipeline tests when no features are passed

---

backend-utils/src/lib.rs

With this PR, the `split_pil()` function no longer filters out prover functions. Instead, it assigns it to the unique machine who's columns are referenced.

`split_pil()`: Include prover functions

---

executor/src/witgen/block_processor.rs
executor/src/witgen/data_structures/mod.rs
executor/src/witgen/data_structures/mutable_state.rs
executor/src/witgen/eval_result.rs
executor/src/witgen/generator.rs
executor/src/witgen/identity_processor.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/machines/double_sorted_witness_machine_16.rs
executor/src/witgen/machines/double_sorted_witness_machine_32.rs
executor/src/witgen/machines/fixed_lookup_machine.rs
executor/src/witgen/machines/mod.rs
executor/src/witgen/machines/sorted_witness_machine.rs
executor/src/witgen/machines/write_once_memory.rs
executor/src/witgen/mod.rs
executor/src/witgen/processor.rs
executor/src/witgen/query_processor.rs
executor/src/witgen/vm_processor.rs

MutableState is the main way to get access to sub-machines during witness generation. We used to create copies of MutableState for each lookup, extracting the "current machine" where we need mutable access and creating copies of references to the other machines. This causes an allocation for each lookup (including fixed lookups, I think) which is bad for performance.
This PR changes the approach to use RefCell instead: MutableState now owns the machines and for each call to a machine, we mutably borrow that machine. The RefCell mechanism ensures that there are no recursive calls to machines and also avoids allocations.
I also changed the query callback to use non-mut references.
The first and third commits only move code around.

Improve MutableState / Machines

---

executor/src/witgen/machines/machine_extractor.rs
executor/src/witgen/mod.rs

Prepares #2129
With this PR, later-stage witness columns & identities referencing them (or later-stage challenges) are completely ignored. The columns are not assigned to any machine. Previously, they would end up in the main machine and never receive any updates. That doesn't work if machines have different sized though.

Filter later-stage witnesses and identities

---

riscv/tests/common/mod.rs

This PR brings back the riscv-executor tests that were accidentally removed.

bring riscv executor tests back to life

---

executor/src/witgen/machines/machine_extractor.rs

Multiplicity columns of *global* range constraints used to end up in the main machine, which is a problem if it has a length different from the range check machine.

Remove range constraint multiplicity columns from main machine

---

ast/src/analyzed/mod.rs
backend-utils/src/lib.rs
backend/src/mock/connection_constraint_checker.rs
backend/src/mock/evaluator.rs
backend/src/mock/machine.rs
backend/src/mock/mod.rs
backend/src/mock/polynomial_constraint_checker.rs

This PR adds that the `MockBackend` also checks machine connections. Probably the error messages could be better (for now, it just panics if there is an error), but I think that can be fixed in a follow-up PR.

`MockBackend`: Check machine connections

---

backend/src/composite/mod.rs
backend/src/composite/sub_prover.rs
backend/src/halo2/circuit_builder.rs
backend/src/plonky3/stark.rs
executor-utils/Cargo.toml
executor-utils/src/lib.rs
executor/src/witgen/mod.rs
pipeline/src/pipeline.rs
pipeline/tests/asm.rs
plonky3/Cargo.toml
plonky3/src/circuit_builder.rs
plonky3/src/prover.rs
test_data/asm/block_to_block_with_bus_different_sizes.asm

With this PR, we compute the later-stage witnesses per machine instead of globally. This has two advantages:
- We're able to handle machines of different sizes
- We can parallelize later-stage witness generation
This affects the two backend that can deal with multiple machines in the first place: `Plonky3Backend` and `CompositeBackend`

Compute later-stage witness by machine

---

ast/src/analyzed/mod.rs
backend/src/mock/constraint_checker.rs
executor/src/witgen/expression_evaluator.rs
executor/src/witgen/global_constraints.rs
executor/src/witgen/mod.rs
plonky3/src/circuit_builder.rs

Fixes a bug in witgen & the Plonky3 backend regarding caching of values of intermediate columns: We ignored the next operator.

Bug fix: Fix intermediates cache for next references

---

backend/src/plonky3/mod.rs
backend/src/plonky3/stark.rs

lower memory usage by avoiding having the whole serialized key in memory before writing to disk

directly serialize the plonky3 pk

---

ast/src/analyzed/mod.rs
pilopt/src/lib.rs
pilopt/tests/optimizer.rs

When removing constant columns with a single value, prover functions are not visited. Change that.
Tested with the riscv keccak
```
pil keccak.asm --force --linker-mode bus --field gl
```
Before
```
Removed 3 witness and 9 fixed columns. Total count now: 585 witness and 231 fixed columns.
```
After
```
Removed 30 witness and 114 fixed columns. Total count now: 558 witness and 126 fixed columns.
```
Note that after this change, the native and bus number of fixed columns for keccak differ by 17, which is the number of `is_first` fixed columns in the bus output.

Visit prover functions in pilopt

---

backend/src/mock/mod.rs
backend/src/mock/polynomial_constraint_checker.rs
pipeline/src/test_util.rs

As mentioned in the comment, these identities are checked, so there is no need to display a warning.

`MockBackend`: Remove unnecessary warnings

---

backend/Cargo.toml
backend/src/mock/connection_constraint_checker.rs
backend/src/mock/mod.rs
backend/src/mock/polynomial_constraint_checker.rs
executor/src/witgen/machines/mod.rs

With this PR, we get much better error messages for connection errors.
This is an example of an issue we're currently debugging:
```
$ cargo run -r pil test_data/std/keccakf16_memory_test.asm -o output -f --prove-with mock --export-witness-csv
...
Errors in 50 / 213 connections:
Connection failed between main_keccakf16_memory and main_memory:
main_keccakf16_memory::sel[0] * main_keccakf16_memory::step_flags[0] $ [0, main_keccakf16_memory::input_addr_h, main_keccakf16_memory::input_addr_l, main_keccakf16_memory::time_step, main_keccakf16_memory::preimage[3], main_keccakf16_memory::preimage[2]] is main_memory::selectors[2] $ [main_memory::m_is_write, main_memory::m_addr_high, main_memory::m_addr_low, main_memory::m_step_high * 65536 + main_memory::m_step_low, main_memory::m_value1, …
```

Improve error messages for connection errors in MockBackend

---

pipeline/tests/powdr_std.rs
std/array.asm
std/protocols/bus.asm
std/protocols/fingerprint.asm
std/protocols/lookup.asm
std/protocols/permutation.asm
test_data/std/fingerprint_test.asm

Depends on #2151.
This PR solves all performance issues with `std::fingerprint`. It now has two functions:
- `fingerprint()`: Is similar to a pre-#1985 version of `fingerprint()`. It computes the fingerprint in a recursive way. It should *not* be used to generate expressions, because they would be exponentially large. To prevent that, I changed the type so that it can only be applied to `fe`.
- `fingerprint_inter()`: Is the analog for expressions. It stores intermediate results in intermediate columns. Because of that, it needs to be a `constr` function. It generates $O(n)$ intermediate columns of constant size.
I also added a test for the `fingerprint_inter` function and changed all protocols (bus, permutation, lookup) to use `fingerprint_inter` to generate constraints.

Add variant of `fingerprint()` that yields intermediate columns

---

backend/src/mock/connection_constraint_checker.rs
backend/src/mock/machine.rs
backend/src/mock/mod.rs

Depends on #2153 (in merge queue), likely needs a rebase after it's merged.
To test:
```
$ cargo run pil test_data/asm/block_to_block_empty_submachine.asm -o output -f --prove-with mock
```

`MockBackend`: Fix removed sub-machines

---

backend/src/mock/connection_constraint_checker.rs
backend/src/mock/evaluator.rs
backend/src/mock/machine.rs
backend/src/mock/mod.rs
backend/src/mock/polynomial_constraint_checker.rs
pipeline/tests/asm.rs
pipeline/tests/powdr_std.rs

Ticks the third item off #2152
This should make the mock prover feature-complete!

`MockBackend`: Implement later-stage witness generation

---

backend/src/mock/connection_constraint_checker.rs
backend/src/mock/evaluator.rs

With this PR, the `MockBackend` should work also for *some* lookups / permutations that don't reference any column on the LHS and RHS.
While these constraints could always be removed by the optimizer, it is not always the case in practice.

Mock Backend: Handle constant LHS / RHS in connections

---

riscv/src/large_field/code_gen.rs
riscv/src/small_field/code_gen.rs

While the `srai` instruction has been implemented, the `sra` (same thing with shift passed via a register) was not. This PR implements it.

riscv: add support for sra instruction

---

executor/src/witgen/processor.rs
executor/src/witgen/query_processor.rs

Cherry-picked from #2174
With this PR, we run all prover functions in parallel when solving for the witness in `VmProcessor`. Interestingly, this didn't require any changes to the order in which things are done: We already ran the functions independently and applied the combined updates. So, this is a classic map-reduce.
I think this change always makes sense, but is especially useful for the prover functions we have to set bus accumulator values. For example, in our RISC-V machine, the main machine has ~30 bus interactions, with a fairly expensive prover function for each.
When used on top of #2173 and #2175, this accelerates second-stage witness generation for the main machine from ~10s to ~6s for the example mentioned in #2173.

Parallelize calls to prover functions

---

std/protocols/bus.asm
std/protocols/fingerprint.asm

Cherry-picked from #2174
When used on top of #2173, this accelerates second-stage witness generation for the main machine from ~35s to ~10s for the example mentioned in #2173.

`fingerprint()` performance improvements

---

riscv/tests/common/mod.rs

The nightly test passes on the server now in 1h42m, using the same exact command. However, when run on CI, it fails with the error below.
```console
System.IO.IOException: No space left on device : '/home/runner/runners/2.321.0/_diag/Worker_20241130-025215-utc.log' ...
```
This is potentially caused by the `.release()` function which keeps the tmp files alive.

do not keep temp test files

---

book/src/pil/patterns.md

1. Fixed array pattern syntax:
- Old: `[a, b, c`]
- New: `[a, b, c]`
Removed extra backtick that was causing incorrect code formatting.
- Ensuring proper Markdown rendering
The fixes help prevent confusion for readers learning about PIL patterns and maintain documentation quality standards.

Fix syntax errors in patterns.md documentation

---

.github/workflows/build-cache.yml

The new Ubuntu used in CI now requires new packages for estark. This is already in nightly but broke the normal cache last night

Fix ci again

---

.github/workflows/nightly-tests.yml

This PR moves nightly back to GH with Ubuntu 24.04 and the old settings. The nightly test passed for this branch in here: https://github.com/powdr-labs/powdr/actions/runs/12154934614

fix nightly again

---

riscv-executor/src/lib.rs

these calls were missing the `ExecMode::Trace` check

don't generate memory machine traces executing in `Fast` mode

---

.github/workflows/pr-tests.yml
examples/fibonacci/Cargo.toml
examples/fibonacci/guest/src/main.rs
pipeline/src/lib.rs
pipeline/src/pipeline.rs
powdr-test/examples/fibonacci.rs
powdr/src/lib.rs
riscv-executor/src/lib.rs
riscv-runtime/src/fmt.rs
riscv/src/continuations.rs
std/prelude.asm

This PR:
- Makes explicit the notion that 0=stdin, 1=stdout, 2=stdout in the QueryCallback's "FS"
- Exposes the outputs in Session
- Removes printing to stdout and stderr in the callback itself. This is now the responsibility of the host if needed.
- Adds the Fibonacci test with stdout to CI using the write mechanism
The idea is that after this we should also expose the proof's publics and make a stream mechanism for inputs and outputs

Expose stdout/stderr in Session

---

examples/fibonacci/guest/src/main.rs
powdr-test/examples/fibonacci.rs
powdr/src/lib.rs

Depends on https://github.com/powdr-labs/powdr/pull/2189
This PR exposes the publics of a proof in Session and uses it to commit the result of Fibonacci in the example.

expose publics in session

---

ast/src/asm_analysis/display.rs

Small PR to fix the fact that SubmachineDeclaration arguments were being omitted during display.

Display: SubmachineDeclaration args are not beign printed

---

ast/src/analyzed/display.rs
ast/src/analyzed/mod.rs
backend/src/estark/json_exporter/expression_counter.rs
backend/src/estark/json_exporter/mod.rs
backend/src/halo2/circuit_builder.rs
backend/src/mock/connection_constraint_checker.rs
backend/src/stwo/circuit_builder.rs
executor/src/witgen/global_constraints.rs
executor/src/witgen/identity_processor.rs
executor/src/witgen/machines/machine_extractor.rs
executor/src/witgen/machines/write_once_memory.rs
pil-analyzer/src/condenser.rs
pilopt/src/lib.rs
plonky3/src/circuit_builder.rs
std/prelude.asm
std/protocols/bus.asm

This PR adds a `Constr:: PhantomBusInteraction` variant. For now, it is ignored - if users want to use a bus, they need to express this in terms of phantom lookups / permutations as before this PR.
I added a few `TODO(bus_interaction)` and opened #2184 to track support for phantom bus interactions.
One use-case this could have before though is to trigger a "hand-written" witness generation for the bus, as discussed in the chat.

Add `PhantomBusInteraction`

---

riscv-executor/src/submachines.rs
std/machines/binary.asm
std/machines/hash/keccakf16_memory.asm
std/machines/hash/keccakf32_memory.asm
std/machines/hash/poseidon2_bb.asm
std/machines/hash/poseidon2_gl.asm
std/machines/hash/poseidon_bb.asm
std/machines/hash/poseidon_bn254.asm
std/machines/hash/poseidon_gl.asm
std/machines/hash/poseidon_gl_memory.asm
std/machines/large_field/rotate.asm
std/machines/large_field/shift.asm
std/machines/range.asm
std/machines/small_field/keccakf16.asm
std/machines/small_field/rotate.asm
std/machines/small_field/shift.asm
std/machines/split/mod.asm

In cases where the operation id was defined as a witness column, it seems the optimizer didn't remove them. So this can save a witness column (and lookup parameter) in some cases (e.g., poseidon machines)

remove poseidon operation id

---

executor/src/witgen/bus_accumulator/mod.rs
std/protocols/bus.asm

This PR:
- Removes the `acc_next` columns, which were only needed because of a limitation of prover functions. The prover function that existed is now removed entirely, because we use the hand written witgen anyway, see #2191.
- Also this PR materializes the folded tuple. This lowers the degree of the constraints if the tuples being sent have a degree > 1. It also enables next references in the tuple being sent.
As a result, we can now generate Plonky3 proofs with a bus!
```bash
cargo run -r --features plonky3 --bin powdr-rs compile riscv/tests/riscv_data/keccak -o output --max-degree-log 18 --field gl
cargo run -r --features plonky3 pil output/keccak.asm -o output -f --field gl --prove-with plonky3 --linker-mode bus
```
The proof generation takes 8.32s (of which 394ms are spent on …

Bus: Remove `acc_next` + materialize folded tuple

---

asmopt/Cargo.toml

All cargo.toml must have this `bench = false`. This will be caught in pr tests in the future.

Fix CI bench

---

.github/workflows/pr-tests.yml

These runs make no use of the artefacts created in build and do a full re-build, so we might as well run them from the start.

Remove dependencies on build

---

.github/workflows/deploy-book.yml

Turns out `git worktree` does not track the remote branch, so the benchmarks are not there.
Revert to what we did before, and explicitly restore the benchmarks from the remote `gh-pages` branch.

Fix book deploy again

---

executor/src/witgen/data_structures/caller_data.rs
executor/src/witgen/data_structures/mod.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/machines/double_sorted_witness_machine_16.rs
executor/src/witgen/machines/double_sorted_witness_machine_32.rs
executor/src/witgen/machines/dynamic_machine.rs
executor/src/witgen/machines/fixed_lookup_machine.rs
executor/src/witgen/machines/mod.rs
executor/src/witgen/machines/second_stage_machine.rs
executor/src/witgen/machines/sorted_witness_machine.rs
executor/src/witgen/machines/write_once_memory.rs
executor/src/witgen/processor.rs

This PR refactors a few things:
- `process_lookup_direct` no longer has a default implementation. Eventually, we want all machines to implement it, so I figured it would be better to explicitly panic in each machine.
- Refactored the implementation of `FixedLookupMachine::process_plookup`, pulling some stuff out into a new `CallerData` struct. This is similar to what @chriseth has done on [`call_jit_from_block`](https://github.com/powdr-labs/powdr/compare/main...call_jit_from_block), see the comment below.
- As a first test, I implemented `process_lookup_direct` for the "large"-field memory machine (and `process_plookup` by wrapping `process_lookup_direct`)

Refactorings around `process_lookup_direct`

---

pipeline/tests/executor.rs
pipeline/tests/mock_backend.rs

I was not aware of this crate and introduced some ugly logging initialization in earlier PRs.

Use `test_log::test`

---

executor/src/witgen/range_constraints.rs

This adds a function to range constraints that splits a range constraint into two disjoint range constraints of roughly the same size that equal the initial range constraint when combined.
This function is planned to be used for branching in autowitjitgen.

Bisect range constraints.

---

executor/src/witgen/jit/includes/field_goldilocks.rs

Pulled out of #2276. Needed to make the code generated for the Binary machine compile.

Fixes in Goldilocks field implementation

---

ast/src/analyzed/mod.rs
backend/src/composite/mod.rs

This removes a call to `Analyzed::identities_with_inlined_intermediate_polynomials()`. Instead, when computing the constraint degree, intermediate polynomials are looked up on the fly, and any results are cached.

Handle intermediates when computing the constraint degree

---

.github/workflows/pr-tests.yml

This should speed up the test. If I remember correctly, with this compilation is only 2-3s for Poseidon (instead of ~10min). At runtime, it is about as "fast" as runtime witgen.

Reduce `POWDR_JIT_OPT_LEVEL` in CI

---

executor/src/witgen/jit/includes/field_goldilocks.rs

Field elements should only be ANDed with integers. I added `BitAnd<u64> for GoldilocksField` in #2277, this removes the possibility to XOR two field elements.

Remove `BitAnd<GoldilocksField> for GoldilocksField`

---

executor/src/witgen/data_structures/mutable_state.rs
executor/src/witgen/jit/block_machine_processor.rs
executor/src/witgen/jit/test_util.rs
executor/src/witgen/jit/witgen_inference.rs
executor/src/witgen/machines/block_machine.rs
test_data/pil/binary.pil
test_data/pil/poseidon_gl.pil

With this PR, we expect a "main" machine with a connecting identity to the block machine, and run the "normal" machine extractor on the entire PIL.
Besides reducing the amount of code, this gives us more objects, like `MutableState`.

Refactor tests of `BlockMachineProcessor`

---

ast/src/parsed/asm.rs
executor/src/witgen/jit/witgen_inference.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/machines/dynamic_machine.rs
linker/src/lib.rs
pipeline/src/test_util.rs
pipeline/tests/asm.rs
pipeline/tests/mock_backend.rs
pipeline/tests/pil.rs
pipeline/tests/powdr_std.rs
riscv/tests/common/mod.rs
test_data/asm/single_operation.asm

This PR uses `LinkerMode::Bus` in all tests which:
- Are on Goldilocks or BN254 (the bus is not implemented for smaller fields), AND
- Are tested with the mock prover or Plonky3 (while Halo2 does support the bus in principle, its runtime is exponential, because it inlines intermediate polynomials)
This is true for most tests.
Doing so, I came across a few bugs. I added comments for them below.

Enable Bus in tests

---

executor/src/witgen/data_structures/mutable_state.rs
executor/src/witgen/jit/block_machine_processor.rs

Removes `MutableState::get_machine` since we already have the machine before we construct the MutableState.

Remove test function.

---

executor/src/witgen/jit/block_machine_processor.rs
executor/src/witgen/jit/function_cache.rs
executor/src/witgen/jit/witgen_inference.rs
executor/src/witgen/machines/block_machine.rs
test_data/asm/block_machine_exact_number_of_rows.asm
test_data/pil/binary.pil

Depends on #2279
This PR implements JIT code generation for block machines with irregular block shape, such as `std::machines::large_field::binary::Binary`. This is achieved as follows:
- Instead of solving rows `0..block_size`, we run the solver for rows `-1..(block_size + 1)`. This way, the solver is able to generate code that writes to the previous row of the last block or the first row of the next block.
- At the end, we check whether the generated code is actually consistent: For example, if the code writes to the last row of the previous block, it can't have a unknown value in the same cell of the current block (unless it's known to be the same).
Note that the generated code is still not used in practice, because we don't call the JIT with the right amount of context. I started …

JIT for block machines with non-rectangular shapes

---

backend/src/halo2/circuit_builder.rs
backend/src/mock/connection_constraint_checker.rs
backend/src/mock/machine.rs
backend/src/mock/mod.rs
backend/src/mock/polynomial_constraint_checker.rs
backend/src/stwo/circuit_builder.rs
executor-utils/src/expression_evaluator.rs
executor/src/witgen/bus_accumulator/mod.rs
plonky3/src/circuit_builder.rs

This is a first step to generalize the expression evaluator. Currently just merging the `TraceValues` and `GlobalValues` traits, as it seemed a bit unnecessary to have two of them.
Eventually, I want to have a more generic `ExpressionWalker`, of which `ExpressionEvaluator` would be a special case. That walker could also be used to do things like:
- Degree computation
- check if the expression (or any referenced intermediate) has a next reference
While still preserving the caching behavior, so that we don't run exponentially long on these operations either!

Refactor `ExpressionEvaluator`

---

executor/src/witgen/jit/block_machine_processor.rs
executor/src/witgen/jit/single_step_processor.rs
executor/src/witgen/jit/symbolic_expression.rs
executor/src/witgen/jit/witgen_inference.rs

Fixes a TODO that makes block machine fail hard if a block machine is not stackable. This way, we'll know when this happens, instead of silently resorting to run-time solving.

Assert that block machines are stackable

---

executor/src/witgen/jit/block_machine_processor.rs
executor/src/witgen/jit/function_cache.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/mod.rs
executor/src/witgen/processor.rs

Cleans up the log a little bit, moving some logs to trace level. Especially related to JIT, which fails quite frequently still.
For example, this exposes the issue fixed by #2322:
```
$ RUST_LOG=debug cargo run pil test_data/std/binary_large_test.asm -o output -f --linker-mode bus
...
[00:00:00 (ETA: 00:00:00)] ░░░░░░░░░░░░░░░░░░░░ 0% - Starting...                                                                                                                           Compiling JIT function for 
Machine: Secondary machine 0: main_binary (BlockMachine)
Identity: main::instr_and $ [0, main::X0, main::X1, main::X2] is main_binary::latch * main_binary::sel[0] $ [main_binary::operation_id, main_binary::A, main_binary::B, main_binary::C]
Known args: 1110
=> Error generating JIT code: Code …
```

Improve logging

---

pipeline/tests/powdr_std.rs
std/math/extension_field.asm
std/math/fp2.asm
std/math/mod.asm
std/protocols/bus.asm
std/protocols/fingerprint.asm
std/protocols/lookup.asm
std/protocols/permutation.asm
test_data/asm/block_to_block_with_bus.asm
test_data/asm/block_to_block_with_bus_different_sizes.asm
test_data/std/fingerprint_test.asm

This PR adds a `std::math::extension_field` module to our PIL standard library, which abstracts over which extension field is used. I changed all protocols - most importantly the bus - to use the new abstraction. As a result, we can now have bus constraints on smaller fields like BabyBear, e.g.:
```
$ cargo run pil test_data/asm/block_to_block_with_bus.asm -o output -f --field bb
```
TODOs left to future PRs:
- Add M31 to `std::field::KnownField`
- Implement witness generation for Bus with Fp4

Implement bus constraints for small fields

---

executor/src/witgen/machines/block_machine.rs
executor/src/witgen/machines/double_sorted_witness_machine_32.rs
executor/src/witgen/machines/dynamic_machine.rs
executor/src/witgen/machines/fixed_lookup_machine.rs
executor/src/witgen/processor.rs

This came up in Leo's pre-compile experiments, in combination with my changes in #2323. I think we should merge it to `main` though.

Handle incomplete evaluation gracefully

---

executor/src/witgen/bus_accumulator/extension_field.rs
executor/src/witgen/bus_accumulator/fp2.rs
executor/src/witgen/bus_accumulator/fp4.rs
executor/src/witgen/bus_accumulator/mod.rs
executor/src/witgen/mod.rs
pipeline/tests/asm.rs

Builds on #2334
This PR adds witness generation for the bus if the Fp4 extension field is used.
RISC-V doesn't run yet, because we need to do something similar to #2297 in the small field arith machine.

Small field bus witgen

---

pipeline/tests/asm.rs
std/field.asm
std/math/extension_field.asm
std/protocols/bus.asm

If rebased on top of #2051, this enables M31 RISC-V proofs with the bus enabled:
```sh
cargo run -r --features plonky3 --bin powdr-rs compile riscv/tests/riscv_data/keccak-o output --field bb
cargo run -r --features plonky3 pil output/keccak.asm -o output -f --field m31 --prove-with plonky3 --linker-mode bus
```

Add M31 as known field

---

executor/src/witgen/jit/witgen_inference.rs

Machine calls sometimes re-generate the same assignments (especially when they are already "complete").

Use BTreeSet for assignments.

---

executor/src/witgen/global_constraints.rs
executor/src/witgen/machines/machine_extractor.rs
executor/src/witgen/mod.rs

This is not necessary anymore since #2319: We previously had a multiplicity witgen pass only for range constraints via lookups. Now we have it for all phantom lookups, which includes range constraints via lookups.

Remove tracking of range constraint multiplicities

---

linker/src/lib.rs
std/prelude.asm
std/protocols/bus.asm
std/protocols/permutation_via_bus.asm
test_data/std/bus_permutation.asm

Depends on #2360
Changes the semantics of the `PhantomBusInteraction.latch` field slightly, to make my life easier with #2351. Basically, we want it to be exactly what the RHS selector would have been in a lookup / permutation: A fixed column latch for a lookup, and equal to the multiplicity for the permutation. This way, witgen can treat it just like it treats selectors now.
Eventually, I think we should remove the latch again. The permutation latch is equal to the multiplicity anyway, and the lookup latch should be detectable by looking for a constraint like `(1 - latch) * multiplicity = 0;`.

Make latch semantic clearer

---

executor/src/witgen/data_structures/finalizable_data.rs
executor/src/witgen/jit/interpreter.rs

This is done so it can be used without needing to construct a CompactData or re-implement the computation.

Put column layout computation into constructor of ColumnLayout.

---

executor/src/witgen/jit/block_machine_processor.rs
executor/src/witgen/jit/function_cache.rs
executor/src/witgen/jit/processor.rs
executor/src/witgen/jit/single_step_processor.rs
executor/src/witgen/jit/witgen_inference.rs

Uses the `CanProcess` trait instead of the full `MutableState` struct in some function and also some grammatical simplifications (use `: impl CanProcess`).

Simplify interface.

---

executor/src/witgen/jit/block_machine_processor.rs
executor/src/witgen/jit/debug_formatter.rs
executor/src/witgen/jit/mod.rs
executor/src/witgen/jit/processor.rs
executor/src/witgen/jit/single_step_processor.rs

This formats the incomplete identities in the following way:
For each identity, the first half is the full form, the second half is a simplified form that takes known values into account (but it does not have to be affine).
For each half, the first line is the expression, the second contains known values and the third contains known range constraints.
```
--------------[ identity on row on row -1: ]--------------
main::add_two_state' = (((1 - main::RESET) * (main::add_two_state + 1)) + (main::RESET * main::add_two_input'))
??? =                  1                     ???                    1                    ???  
=                                                                                         
main::add_two_state' = main::add_two_input'
??? =                  ???
= …
```

Human-readable formatting of JIT witgen (error) state.

---

riscv/src/elf/mod.rs

Apparently this is needed by newer versions of LLVM.

Using JAL instead of CALL, allowing any link register.

---

executor/src/witgen/jit/block_machine_processor.rs
executor/src/witgen/jit/processor.rs
executor/src/witgen/jit/single_step_processor.rs

Removes optional parameters from the constructor of Processor and introduces builder functions for them.

Simplify constructor of Processor.

---

executor/src/witgen/jit/block_machine_processor.rs
executor/src/witgen/jit/compiler.rs
executor/src/witgen/jit/function_cache.rs
executor/src/witgen/jit/includes/interface.rs
executor/src/witgen/jit/interpreter.rs
executor/src/witgen/jit/processor.rs
executor/src/witgen/jit/single_step_processor.rs
executor/src/witgen/jit/variable.rs
executor/src/witgen/jit/witgen_inference.rs

Some machines need non-constant fixed column values even outside of fixed lookups. An example for that is the `STEP` column in a riscv VM.
This PR introduces variables for those columns and implements access in the compiled code.

Access to nonconstant fixed columns.

---

executor/src/witgen/jit/debug_formatter.rs
executor/src/witgen/jit/single_step_processor.rs

The debug formatter prints, for each identity, three lines of unsimplified expressions (i.e. `x * 0` explicitly printed):
The first line contains just the identity, the second known values and the third known range constraints.
Then it prints three more lines, with `x * 0` simplified as `0`. Again, the first line with the simplified expression, the second with known values, the third with known range constraints, but of course just for the remaining variables.
For the second triple, it did not print the separators in the first line (it did it properly for binary operators, though). Furthermore, it added spacing to align the second triple with the first, even though the idea is that this is not needed because the un-simplified version is often not readable since it spans multpile lines.

Fix debug formatter.

---

pil-analyzer/src/pil_analyzer.rs

This restores `self.symbol_counters` before the error is propagated upwards. Without this, we get a panic at the `unwrap()` because the same thing is probably done further up in the call chain.

Restore counters before returning the error.

---

pipeline/tests/asm.rs
test_data/asm/block_to_block_with_bus.asm
test_data/asm/dynamic_bus.asm
test_data/asm/static_bus.asm

Adds two tests, illustrating the difference between a "static" and "dynamic" bus.
The dynamic case is still failing, because witgen does not support it yet. Hopefully, we can fix it soon :)

Add tests for static & dynamic bus

---

ast/src/analyzed/display.rs
ast/src/analyzed/mod.rs
executor/src/witgen/bus_accumulator/mod.rs
executor/src/witgen/data_structures/identity.rs
pil-analyzer/src/condenser.rs
pilopt/src/lib.rs
std/prelude.asm
std/protocols/bus.asm

We so far assumed that the first entry of the payload of a `PhantomBusInteraction` is the bus ID. Now, it has an extra field in the annotation. For example, if we decided to fingerprint it differently, we wouldn't have to change any (automatic) witgen code.

Make `bus_id` field explicit

---

executor/src/witgen/data_structures/identity.rs
executor/src/witgen/global_constraints.rs
executor/src/witgen/identity_processor.rs
executor/src/witgen/jit/debug_formatter.rs
executor/src/witgen/jit/witgen_inference.rs
executor/src/witgen/machines/machine_extractor.rs
executor/src/witgen/machines/sorted_witness_machine.rs
executor/src/witgen/machines/write_once_memory.rs
executor/src/witgen/mod.rs
executor/src/witgen/multiplicity_column_generator.rs

#2361 introduced a new `Identity` type, which could be - among other things - a bus send or a bus receive. Also, there was another map from bus ID to receive.
Actually, the receives are not needed in the list of identities, so I removed them from the type entirely. They were ignored everywhere anyway. As a bonus, we can now also remove the `BusReceive::interaction_id`.

Separate Bus Receives from Identities

---

ast/src/analyzed/display.rs
ast/src/analyzed/mod.rs
executor/src/witgen/data_structures/identity.rs
pil-analyzer/src/condenser.rs
std/prelude.asm
std/protocols/bus.asm

In our manual bus witgen, we currently assume that all second-stage witness columns in source order are always of the form: "folded" payloads for bus interaction 1, accumulators for bus interaction 1, "folded" payloads for bus interaction 2, ...
As we implement #2337, this will no longer be the case (we might not have a folded payload, or there might be two interactions using the same accumulator).
I tried to write code to find the accumulators from the polynomial identities, but I failed. So now, they are simply part of the `PhantomBusInteraction` annotation, which I think is fair. I still hope that we can automatically find the "folded" columns if they exist.

Add accumulator columns to `PhantomBusInteraction`

---

std/math/extension_field.asm
std/math/fp2.asm
std/protocols/fingerprint.asm

In our PIL std lib, we have an `Ext` that abstracts over `Fp2` and `Fp4`. But in cases where we don't need any extension field (e.g. BN254), we wrapped base field elements as `Fp2` anyway. This is a bit weird and can lead to issues when the optimizer removes the unused dimension (e.g., it might still be referenced by a prover function or witgen annotation). I had this problem in #2426.
Now, there is an `Ext<T>::Fp` variant that simply wraps `T`.

Add `Fp` to extension field implementation

---

executor/src/witgen/jit/compiler.rs
executor/src/witgen/jit/function_cache.rs
jit-compiler/src/compiler.rs
jit-compiler/src/includes/README.txt
jit-compiler/src/includes/field_generic_up_to_64.rs
jit-compiler/src/includes/field_goldilocks.rs
jit-compiler/src/includes/types.rs
jit-compiler/src/lib.rs
jit-compiler/src/util_code.rs

The JIT compiler used for computing fixed column and the new code for witgen used two different "util" code snippets. Since the field implementation for the new witgen code is more advanced, it is now moved to the generic jit compiler and used by both. It also adds some types that will later be used by prover functions (PilVec, Callable, etc). Those types were present already in the fixed column jit code.

Combine util functions for jit.

---

ast/src/analyzed/display.rs
ast/src/analyzed/mod.rs
executor/src/witgen/data_structures/identity.rs
pil-analyzer/src/condenser.rs
std/prelude.asm
std/protocols/bus.asm

Depends on #2427 (because otherwise a referenced column might be removed by the optimizer).
This PR is completely analogous to #2412: We add a list of expressions that evaluate to the folded payload to `PhantomBusInteraction`. This lets us easily find the referenced columns in the manual bus witgen, see #2428.

Add folded payload columns to `PhantomBusInteraction`

---

executor/src/witgen/bus_accumulator/mod.rs

Depends on #2426.
With this PR, we use the annotations added in #2412 and #2426 to find the columns being generated. This allows us to detect when the folded payload is not persisted as a witness column.
The background is that @Schaeff is working on #2425, which would undo persisting the folded payloads in some cases, allowing us to spend fewer witness columns per bus interaction. With this PR, this should be fine: The column type will change from witness to intermediate, which means that the bus witgen will not output any folded columns.
It can be tested by changing the `materialize_folded` bool to `false`, e.g. [here](https://github.com/powdr-labs/powdr/blob/e77d3801c1decff039fd0ec6bbeb55ed734357fb/std/protocols/bus.asm#L48) and running:
```
cargo run pil …
```

Manual Bus Witgen: Output folded columns only if they exist

---

executor/src/witgen/bus_accumulator/mod.rs
pipeline/tests/asm.rs
std/protocols/bus.asm
test_data/asm/static_bus_multi.asm

Depends on #2428 and implements the second bullet point from https://github.com/powdr-labs/powdr/issues/2337#issue-2787875072.
**Test Coverage**
Not sure why CI isn't running but currently `static_bus_multi.asm` passes test with `cargo run pil test_data/asm/static_bus_multi.asm --force --linker-mode bus --prove-with mock --field bn254` but NOT if `--field gl` with all else equal. See bottom for error from `--field gl`, which are obviously field extension constraints not passing for `folded` columns. 
**Questions**
1. Probably the biggest problem is with the degree-3 bound of Plonky3. The non batched version already has a degree of 3 (https://github.com/powdr-labs/powdr/blob/main/std/protocols/bus.asm#L86-L89). Therefore, this batched version has a degree of 4 and therefore doesn't work …

Batch two bus interactions to the same set of accumulator columns

---

executor/src/witgen/affine_expression.rs
executor/src/witgen/data_structures/caller_data.rs
executor/src/witgen/data_structures/mutable_state.rs
executor/src/witgen/global_constraints.rs
executor/src/witgen/identity_processor.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/machines/double_sorted_witness_machine_16.rs
executor/src/witgen/machines/double_sorted_witness_machine_32.rs
executor/src/witgen/machines/dynamic_machine.rs
executor/src/witgen/machines/fixed_lookup_machine.rs
executor/src/witgen/machines/mod.rs
executor/src/witgen/machines/second_stage_machine.rs
executor/src/witgen/machines/sorted_witness_machine.rs
executor/src/witgen/machines/write_once_memory.rs
executor/src/witgen/processor.rs

this PR changes the signature of `Machine::process_plookup` from
```rust
fn process_plookup<'b, Q: QueryCallback<T>>(
&mut self,
mutable_state: &'b MutableState<'a, T, Q>,
identity_id: u64,
caller_rows: &'b RowPair<'b, 'a, T>,
) -> EvalResult<'a, T>;
```
To
```rust
fn process_plookup<'b, Q: QueryCallback<T>>(
&mut self,
mutable_state: &'b MutableState<'a, T, Q>,
identity_id: u64,
parameters: &[AffineExpression<AlgebraicVariable<'a>, T>],
range_constraints: &dyn RangeConstraintSet<AlgebraicVariable<'a>, T>,
) -> EvalResult<'a, T>;
```
Previously, each machine evaluated the parameters themselves, using the `caller_rows` and the calling bus send, stored in the connection. But in the future, the calling bus send will not be static, so I moved this to the caller.
This will enable #2447 and …

Witgen: Pass range constraints separately

---

std/utils.asm

As suggested by @georgwiese in the bus interaction PR, this util provides a generic interface for transposing a matrix of any type while ensuring that the input is rectangular.

Pil util for transposing generic matrix

---

ast/src/analyzed/display.rs
ast/src/analyzed/mod.rs
executor/src/witgen/bus_accumulator/mod.rs
executor/src/witgen/data_structures/identity.rs
pil-analyzer/src/condenser.rs
std/prelude.asm
std/protocols/bus.asm

Depends on #2457. Bus logic, bus interaction type, display, and witgen changes to support helper column being an Option::None in case of odd number of bus interactions or Option::Some in case of even number of bus interactions.

Bus multi interaction optional helper

---

executor/src/witgen/jit/block_machine_processor.rs
executor/src/witgen/jit/function_cache.rs
executor/src/witgen/jit/interpreter.rs
executor/src/witgen/machines/block_machine.rs

If one item in the RHS of the connection has `operation_id` in its name and has a known concrete value, create a specialized function for this value.

Specialize functions for operation id.

---

pilopt/src/lib.rs
pilopt/tests/optimizer.rs

Pilopt: Optimize associative ADD operations

---

backend/Cargo.toml
backend/src/stwo/prover.rs

Add trace logging for the Stwo backend as needed in issue #2462.  
Stwo already has detailed tracing, so I simply enable it from the Powdr backend side.

Add logging for stwo backend

---

ast/src/analyzed/mod.rs
executor/src/witgen/bus_accumulator/mod.rs
pil-analyzer/src/condenser.rs

When adding new fields to `PhantomBusInteraction`, we forgot to update the `Children` implementation.
- change the definition of `PhantomBusInteraction` to use expressions, in order for these fields to be visited by the `Children` implementation. Move the expectation that these fields are simple references to witgen.
- update the `Children` implementation
cc @qwang98

Fix bus interaction `Children` implementation

---

executor/src/witgen/jit/block_machine_processor.rs
executor/src/witgen/jit/processor.rs

Fixes point 2 of https://github.com/powdr-labs/powdr/issues/2327

Move block shape check

---

executor/src/witgen/jit/debug_formatter.rs
executor/src/witgen/jit/processor.rs
executor/src/witgen/jit/single_step_processor.rs

This improves error reporting because the failing sends are the reason for the algorithm not finishing. Other non-complete identities are not important for success.

Format incomplete sends separately.

---

executor/src/witgen/jit/identity_queue.rs
executor/src/witgen/jit/processor.rs

The idea behind the "skip" feature was that if we have an update to a variable coming from solving an identity, this variable causes all identities that contain the variable to be re-added to the queue. The identity we currently processed is among those. I thought we do not need to re-add it because we just processed it, but it turns out that in some situations, you can derive more information from the same queue item, for example when a derived range constraint on a variable together with existing constraints allows you to fully solve the identity.

Do not skip the current queue item.

---

riscv/src/large_field/runtime.rs

Not much better than the original check, as it still allows for greater than 2**32 values, but at least it uses two fewer variables.

Simplifying the check that the address is 4-byte aligned.

---

.github/workflows/build-cache.yml
cargo-powdr/template/rust-toolchain.toml
examples/fibonacci/rust-toolchain.toml
examples/keccak/rust-toolchain.toml
powdr-test/examples/fibonacci/rust-toolchain.toml
powdr-test/examples/serialized-inputs/rust-toolchain.toml

I'm not really sure if this is the right fix. For the riscv targets, we are using nightly-2024-08-01 - is that on purpose? Maybe we should keep the examples on 2024-08-01 as well?

Update nightly toolchains.

---

autoprecompiles/Cargo.toml
autoprecompiles/src/lib.rs

Add the necessary code to translate a SymbolicMachine into a PILFile, run powdr optimizations and convert the optimized contraints/interactions back to a SymbolicMachine.

Autoprecompiles: powdr optimizations

---

executor/src/witgen/jit/block_machine_processor.rs
executor/src/witgen/jit/code_cleaner.rs
executor/src/witgen/jit/compiler.rs
executor/src/witgen/jit/effect.rs
executor/src/witgen/jit/identity_queue.rs
executor/src/witgen/jit/interpreter.rs
executor/src/witgen/jit/processor.rs
executor/src/witgen/jit/single_step_processor.rs
executor/src/witgen/jit/variable.rs
executor/src/witgen/jit/witgen_inference.rs

Extracted from #2488, to keep the diff smaller
In #2488, I want to identify a `MachineCallVariable` by a `bus_id: T` instead of an `identity_id: u64`. As a result, it gets a new `<T>` parameter, which propagates to `Variable` and quite far into the codebase. This PR adds it already. The changes here should be quite mechanic.

Add type parameter to `MachineCallVariable`

---

executor/src/witgen/analysis/mod.rs
executor/src/witgen/data_structures/mutable_state.rs
executor/src/witgen/identity_processor.rs
executor/src/witgen/jit/block_machine_processor.rs
executor/src/witgen/jit/code_cleaner.rs
executor/src/witgen/jit/compiler.rs
executor/src/witgen/jit/effect.rs
executor/src/witgen/jit/function_cache.rs
executor/src/witgen/jit/identity_queue.rs
executor/src/witgen/jit/includes/interface.rs
executor/src/witgen/jit/interpreter.rs
executor/src/witgen/jit/processor.rs
executor/src/witgen/jit/single_step_processor.rs
executor/src/witgen/jit/variable.rs
executor/src/witgen/jit/witgen_inference.rs
executor/src/witgen/machines/block_machine.rs
executor/src/witgen/machines/double_sorted_witness_machine_16.rs
executor/src/witgen/machines/double_sorted_witness_machine_32.rs
executor/src/witgen/machines/dynamic_machine.rs
executor/src/witgen/machines/fixed_lookup_machine.rs
executor/src/witgen/machines/machine_extractor.rs
executor/src/witgen/machines/mod.rs
executor/src/witgen/machines/second_stage_machine.rs
executor/src/witgen/machines/sorted_witness_machine.rs
executor/src/witgen/machines/write_once_memory.rs
executor/src/witgen/processor.rs

With this PR, machines are no longer called by the send's identity ID, but by the bus ID. We still assume that a send maps to a bus ID statically, i.e., `BusSend::bus_id()` returns `Some(...)`. This can be relaxed in a future PR, allowing the receiver to be dynamic.
I recommend starting the review by looking into the [changes of the `Machine` trait](https://github.com/powdr-labs/powdr/pull/2488/files#diff-9f434c590cca98f5e5198ee0a62044e930b78487ee751ab211a7ee641501e330).

Witgen: Match machine calls by Bus ID

---

executor/src/witgen/machines/machine_extractor.rs

Extracted from #2541
Fixes a bug that the machine parts doesn't include the intermediate definitions that only appear in one of the receives. An example of this is the [Arith large](https://github.com/powdr-labs/powdr/blob/main/std/machines/large_field/arith.asm) machine, which has intermediates like `x1c` in their list of arguments, but doesn't refer to the in any constraint.

Bug fix: Include intermediates from receives in machine parts

---

test_data/asm/sqrt.asm

Extracted from #2541
This makes JIT witgen work for the sqrt example.

sqrt test: Use compute_from

---

pipeline/src/test_util.rs
pipeline/tests/pil.rs

Depends on #2535 and #2557. Split `assert_proofs_fail_for_invalid_witnesses_pilcom` into `assert_proofs_fail_for_invalid_witnesses_pilcom_composite` and `assert_proofs_fail_for_invalid_witnesses_pilcom_monolithic`. These two APIs are needed because we might generate different witnesses for pilcom composite vs pilcom monolithic under two scenarios:
1. The two backends can have different witnesses to start with. This hasn't been an issue because most of our test cases are very simple machines.
2. After updates in #2535, if we eventually implement different optimizations for the two different backends, they might compute two different witnesses.

Fix pilcom proof fail test functions

---

.github/workflows/nightly-tests.yml
executor/src/witgen/jit/prover_function_heuristics.rs

This should fix the [failing nightly test](https://github.com/powdr-labs/powdr/actions/runs/13937842213/job/39009058952#step:14:42451).

Mark PIL docstring as `no_run`

---

backend/src/lib.rs
backend/src/plonky3/stark.rs
cli-rs/src/main.rs
cli/src/main.rs
pipeline/benches/jit_witgen_benchmark.rs
pipeline/src/pipeline.rs
pipeline/src/test_util.rs
pipeline/tests/asm.rs
pipeline/tests/executor.rs
pipeline/tests/mock_backend.rs
pipeline/tests/pil.rs
pipeline/tests/powdr_std.rs
powdr/src/lib.rs
riscv/benches/executor_benchmark.rs
riscv/src/continuations.rs
riscv/tests/common/mod.rs
riscv/tests/riscv.rs

After discussing with @Schaeff, we formulated a plan:
1. Currently, our pipeline is `compile pilopt tune pilopt witgen0 prove0 witgen1 prove1 finalize`, where `prove0 witgen1 prove1 finalize` is backend aware.
2. In this PR, `tune pilopt witgen0 prove0 witgen1 prove1 finalize` are all backend aware, meaning that a backend argument is required for these steps to run.
I made some specific implementation decisions:
3. In this PR, the `tune` step is a `BackendFactory` API, while all other APIs remain the same places as before. For example, `witgen0` is backend aware because it requires a `backend_tuned_pil` to run. However, `witgen0` only runs differently because different backend tuned pil's are provided by different backend, not *directly* because of the different backend (it has the same …

PoC for two passes of pilopt

---

executor/src/witgen/jit/function_cache.rs
executor/src/witgen/jit/interpreter.rs

This first derives the code and then makes the decision of whether or not to use the interpreter based on the derived code.
Depends on #2582

Split compile function and use interpreter for large code.

---

executor/src/witgen/jit/function_cache.rs
executor/src/witgen/jit/interpreter.rs

This implement prover functons for the interpreter except for the "input/output" prover functions. I would like to merge this already since the input/output prover functions are mainly used in the main machine which does not have jit support yet anyway.

Prover functions for interpreter.

---

executor/src/witgen/data_structures/identity.rs
executor/src/witgen/jit/processor.rs
executor/src/witgen/jit/witgen_inference.rs
executor/src/witgen/multiplicity_column_generator.rs

With this PR, there is no more `.unwrap()` on `BusSend::static_bus_id()` (previously `bus_id()`) and `BusSend::try_match_static()`.
Note that this will only generate a machine call when the bus ID is "known concrete". Getting there might require branching. To relax this (and require only known, but not concrete), I think we could change [`Effect::MachineCall`](https://github.com/powdr-labs/powdr/blob/main/executor/src/witgen/jit/effect.rs#L25) to take a symbolic expression instead of a concrete value, but [`CanProcessCall::can_process_call_fully()`](https://github.com/powdr-labs/powdr/blob/d039c7bd819c59fd5b44dd6e971a65f5ae4780e7/executor/src/witgen/jit/witgen_inference.rs#L625) still expects a concrete value, which can't easily be changed, so I think this is the best we can do.

Implement dynamic bus (JIT)

---

cli/src/main.rs

Now that witgen depends on backend type, `powdr pil` requires a backend type to run through witgen. It only runs till optimized pil if `--prove-with` is not provided.
To match the description, this PR defaults backend to Mock if `--prove-with` is not provided, so `powdr pil` can still run till witgen. To prove with any backend, `--prove-with` is still required.

Powdr PIL runs witgen with mock backend by default

---

powdr/src/lib.rs

Add a `pipeline_from_elf` method  to the session builder, in order to be capable of creating sessions from a non-rust ELF riscv32imc file.
The proposed change is to still use `guest_path` as an input function, and change the behavior based on what item is pointed at by the path:
* if the path is a directory, it will try to compile it as a rust project
* if the path is a file, it will try to interpret it as a riscv ELF file

session builder: create pipeline from ELF files

---

autoprecompiles/Cargo.toml
autoprecompiles/src/lib.rs

Reduces the number of witness columns in the auto-precompile from 133 to 104 in the following test:
`cargo run execute guest --skip 37 --autoprecompiles 1 --optimize`

Set Opcode Flags

---

.github/workflows/build-cache.yml
.github/workflows/pr-tests.yml

Sets the timestamp of files to the commit timestamp, so that cargo can know which files were not modified in the PR.

CI: Avoid rebuilding cached files.

---

.github/workflows/build-cache.yml
.github/workflows/pr-tests.yml

Don't fix the problem, due to depth=1, and might even cause others, due to git timestamp being unreliable to track changes since last build.

Revert "CI: Avoid rebuilding cached files. (#2648)"

---

autoprecompiles/src/lib.rs
autoprecompiles/src/powdr.rs

- use existing visitor traits (Children, AllChildren)
- introduce Column type which keeps name and id together
- introduce UniqueColumns trait to get all Columns in an AST node
- change API to return `Column -> Column` subs instead of `name -> name`

Use column type instead of names in apc

---

.github/workflows/build-cache.yml
.github/workflows/pr-tests.yml

Instead of setting `mtime` to the committed date, which @lvella noted is error-prone, this PR does the following so that we can utilize the build cache:
- check out the commit the build cache was built for
- set mtime to the time the cache was built
- check out the commit we are running the tests on
This hopefully has the effect that all modified files will have the current time as mtime and will trigger re-builds correctly

Check out cache, set mtime and re-check out actual commit.

---

constraint-solver/src/solver.rs

Applying [Chris' suggestion](https://github.com/powdr-labs/powdr/pull/2664#issuecomment-2827676136) to fix an infinite loop in the solver.
I'm not sure how to best reproduce the infinite loop, but [this modification of a test](https://github.com/powdr-labs/powdr/pull/2662/files#diff-bfd27fea42d3539a6d0372f55d103dbae51ac96bab39fb1b3aa4a76ef8a512d8) does a trick. I manually checked that there is no infinite loop anymore, but it makes the test less pure, so I don't want to commit it.
I think this change makes sense anyway.

Solver: Swap conjunction order

---

constraint-solver/src/quadratic_symbolic_expression.rs
constraint-solver/src/solver.rs
constraint-solver/src/symbolic_expression.rs
constraint-solver/src/variable_update.rs
executor/src/witgen/jit/block_machine_processor.rs
executor/src/witgen/jit/identity_queue.rs
executor/src/witgen/jit/processor.rs

Replace the mechanism of "variable update" by "substitutions". This has the benefit that we can substitute a variable also by a more complex value.
The next step (not this PR) would be to also allow substitution by QSEs, which we will need if we want to apply equivalences.

Implement substitutions.

---

constraint-solver/src/constraint_system.rs
constraint-solver/src/solver.rs
constraint-solver/tests/solver.rs

`BusInteractionHandler`: Remove associated type

---

autoprecompiles/src/lib.rs
autoprecompiles/src/powdr.rs

Cherry-picked from #2673
Currently, the `replace_linear_witness_columns` step in pilopt can introduce intermediate polynomials, but then `powdr-openvm` panics when trying to convert them to symbolic expression.
As a short-term fix, I added that intermediates are always in-lined.
On #2673, this in-lines intermediates like:
`c__0_6 = 2013265665 * c__1_6 + 2013200385 * c__3_6 + 48`

Implement intermediates

---

constraint-solver/src/constraint_system.rs
constraint-solver/src/solver.rs
constraint-solver/tests/solver.rs

@chriseth [was right](https://github.com/powdr-labs/powdr/pull/2674#pullrequestreview-2802939786), we can turn an associated type into a type parameter.
I think the reason it was an associated type was something related to object safety in a previous version.

`BusInteractionHandler`: Remove associated type (final2)

---

autoprecompiles/Cargo.toml
autoprecompiles/src/lib.rs
autoprecompiles/src/optimizer.rs
constraint-solver/src/constraint_system.rs
pilopt/src/qse_opt.rs

Adds a new `optimizer` module, which is similar but not identical to the optimizer introduced in #2643. It should be possible to completely remove pilopt once we implement the equivalence of the `replace_linear_witness_columns` step there as well.
This PR does not require changes in `powdr-openvm`, but I opened https://github.com/powdr-labs/powdr-openvm/pull/94 to demonstrate that the tests pass.

Implement solver-based pilopt

---

autoprecompiles/src/lib.rs
autoprecompiles/src/optimizer.rs

Builds on #2673.
With this PR, we expect a bus interaction handler passed to `Autoprecompiles::build`. https://github.com/powdr-labs/powdr-openvm/pull/91 adapts to this change (but simply passing `DefaultBusInteractionHandler` would also work).

Add Bus Interaction Handler to `optimize()`

---

pilopt/src/qse_opt.rs

In the conversion from QSE to algebraic expression, we always try to pull negation to the outside in the hope that it cancels with something else. It was not done at the very outside (at the constraint level) though, where it can just be ignored.

Try to extract negation at end.

---

autoprecompiles/src/lib.rs
autoprecompiles/src/optimizer.rs
pilopt/src/inliner.rs

This PR has the following changes:
- In the optimizer, I added a call `replace_constrained_witness_columns` and some logging.
- I removed the rule that a substitution is only executed if the substituted variable is used, for two reasons:
- The check was expensive (e.g. on Keccak the in-liner took longer than the solver...)
- I think it's fair to just remove these identities then. It changes the statement being proven, but the statement is trivial: "I know some values that can be computed from other values in the table via a low-degree expression"
As seen in https://github.com/powdr-labs/powdr-openvm/pull/108, this leads to moderate improvement in the Keccak benchmark.

Use in-liner in APC optimizer

---

constraint-solver/src/constraint_system.rs
pilopt/src/inliner.rs

Builds on #2695
In the in-liner, we black-listed any variables that appear in bus interactions. I don't think this is necessary, and it prevents some optimizations. But maybe I'm overlooking something. This has also been [discussed in a previous PR](https://github.com/powdr-labs/powdr/pull/2677#discussion_r2075080921).

Apply In-liner to bus interactions as well

---

constraint-solver/src/constraint_system.rs
constraint-solver/src/quadratic_symbolic_expression.rs
constraint-solver/src/solver.rs
constraint-solver/tests/solver.rs

Gives the bus interaction handler a way to return an error. That should be helpful in #2698, because there, we're explicitly looking for witnesses that violate a constraint.
The user of the trait does not have to do anything, because there is a default implementation which simply checks if the old and new range constraints overlap. So `powdr-openvm` does not need to be updated. However, it enables a simplification (https://github.com/powdr-labs/powdr-openvm/pull/114).

Add checked version of `handle_bus_interaction`

---

constraint-solver/src/quadratic_symbolic_expression.rs

Extracted from #2698.
With this PR, `QuadraticSymbolicExpression::solve` returns an error if it finds a unique assignment that contradicts a range constraint.

Check range constraint before returning assignment

---

constraint-solver/src/quadratic_equivalences.rs
constraint-solver/src/quadratic_symbolic_expression.rs
constraint-solver/src/symbolic_expression.rs
constraint-solver/src/symbolic_to_quadratic.rs
constraint-solver/tests/solver.rs

QSE equivalence did not take coefficients into account. This PR normalizes by dividing by the coefficient of the variable we are interested in.

Properly implement coefficients for QSE equivalence

---

autoprecompiles/Cargo.toml
autoprecompiles/src/lib.rs

With backtracking, it should be able to solve for the opcode flags covered by this heuristic.
This PR does not need any adjustments to `powdr-openvm`, but I opened a PR using this branch to show that CI passes: https://github.com/powdr-labs/powdr-openvm/pull/122

Remove opcode heuristic

---

autoprecompiles/src/lib.rs
autoprecompiles/src/optimizer.rs
openvm/src/bus_interaction_handler/mod.rs
openvm/src/lib.rs

This PR is an alternative to #2721, also fixing the regression of #2717. It actually leads to benefits beyond that.
The idea is to only keep columns that are connected to *stateful* bus interactions (i.e., memory and the execution bridge), because this is the only way to affect the state of the VM. This is actually a special case of the `remove_trivial_bus_interactions` step (trivial bus interactions are connected to no columns, and therefore removed), so I removed that (and simplified the `ConcreteBusInteractionHandler`).
[This](https://gist.github.com/georgwiese/56d768e86bbf6def28260ca92f0b5180) is a diff of the generated PIL of the Keccak APC. I spot-checked a few instances of removed columns and there were often columns that were range-checked but otherwise un-constrained.

Remove disconnected columns

---

ast/src/analyzed/algebraic_expression_conversion.rs
ast/src/analyzed/mod.rs
pilopt/src/qse_opt.rs

Turned the conversion into a generic routine. This should help keeping the crates disentangled, because it allows us to keep the ast not depend on QSE and the solver not depend on pilopt.

Generic conversion from algebraic expressions into generic algebraic structures.

---

autoprecompiles/src/lib.rs
openvm/src/lib.rs

This bug was both a soundness bug and a performance bug, leading to fewer columns being removed (although also too many bus interactions being removed, see below).

Bug fix: constrain the entire data to be equal

---

openvm/Cargo.toml
openvm/src/powdr_extension/mod.rs
openvm/src/powdr_extension/plonk/air.rs
openvm/src/powdr_extension/plonk/chip.rs
openvm/src/powdr_extension/plonk/mod.rs
openvm/src/powdr_extension/plonk_chip.rs
openvm/src/powdr_extension/vm.rs

Bootstrapping a chip that implements a PlonK circuit. Implements the AIR, but leaves all other chip methods with `todo!()`.

Add PlonK chip

---

openvm/src/powdr_extension/chip.rs
openvm/src/powdr_extension/executor.rs
openvm/src/powdr_extension/mod.rs

Extracts (one of the two...) `PowdrExecutor` into its own file. I just moved the code (the only change is that I made the fields public for now, to minimize code change).
I think the next steps should be:
- Make it do most of what `generate_air_proof_input` does as well
- Refactor (so the behavior is more encapsulated)
- Re-use it for witness generation of the PlonK chip

Extract executor

---

autoprecompiles/src/lib.rs

Removed these passes and tests still pass, seems to be covered by `autoprecompiles::optimizer::optimize`:
```
/// - Removes trivial constraints (e.g. `0 = 0` or bus interaction with multiplicity `0`)
```

Remove passes

---

openvm/Cargo.toml
openvm/src/bus_interaction_handler/bitwise_lookup.rs
openvm/src/bus_interaction_handler/memory.rs
openvm/src/bus_interaction_handler/mod.rs
openvm/src/bus_interaction_handler/tuple_range_checker.rs
openvm/src/bus_interaction_handler/variable_range_checker.rs
openvm/src/customize_exe.rs
openvm/src/lib.rs
openvm/src/utils.rs

The goal here is to make more explicit which powdr crates are needed for powdr-openvm.
After this PR, next concrete steps are:
- Extract the elf stuff from powdr-riscv into another crate so that this new crate can be used by powdr-openvm instead of powdr-riscv, since that one has tons of other dependencies
- constraint-solver only depends on powdr-number which is great!
- powdr-autoprecompiles depends on a bunch of other powdr crates. Ideally we'd eventually be able to remove from the dep list: ast, parser, parser-util, pil-analyzer, pilopt

reduce deps in powdr-openvm

---

constraint-solver/src/quadratic_symbolic_expression.rs
constraint-solver/src/symbolic_expression.rs

Without this, we get problems because we keep on adding `&mut` to the type in recursion causing a compile-time type error.

Move &mut to type.

---

openvm/src/powdr_extension/chip.rs
openvm/src/powdr_extension/executor.rs
openvm/src/powdr_extension/vm.rs

Continuing #2733, this PR moves most of `PowdrChip::generate_air_proof_input` into the `Executor`. As a result, it is more encapsulated (all its fields are private now), and the interface is such that we should be able to use it in the `PlonkChip` as well: `Executor::generate_witness` returns a matrix of all variable values, for each call to the APC. In the `PowdrChip`, this is the witness directly; in the `PlonkChip`, we can compute the witness from this matrix.
This PR *mostly* moves code. I would prefer to leave any bigger changes to a different PR, so that it doesn't get too entangled.

Executor: Generate AIR proof input

---

constraint-solver/src/quadratic_symbolic_expression.rs
constraint-solver/src/range_constraint.rs

Does the same as before, just with simpler code. But it also does more, because the new code can also transfer range constraints for things like `3 * X + 7 * Y = 0`.

More transfer constraints

---

constraint-solver/src/solver.rs
constraint-solver/tests/solver.rs
pilopt/src/qse_opt.rs

This is a preparatory pull request to allow assignments of anything that is not a concrete number.
This is needed once we reason that two columns are equivalent.
I do not plan to use it for anything more fancy than `X = Y`, or maybe `X = k * Y`, but maybe not even that.

Allow non-numeric asignments.

---

cli-openvm/src/main.rs
openvm/src/lib.rs

This allows users of the `powdr-openvm` lib to pass build features.

api features option

---

.github/workflows/build-cache.yml
.github/workflows/nightly-tests.yml
.github/workflows/pr-tests.yml

- remove target triple
- more succinct rustup command
- install 2025-02-14 for openvm in nightly tests

Fix nightly tests and simplify CI

---

openvm/src/powdr_extension/chip.rs
openvm/src/powdr_extension/executor.rs

- Following the insight by @georgwiese that `eval` is actually not called many times, this PR changes `PowdrAir` to store the AST nodes based on `AlgebraicExpression` (as opposed to openvm SymbolicExpression).
- During trace generation, we do work on each row of the table, which currently includes some table lookups in the table of airs. Move as much as possible out of the part which runs for each row, saving map lookups.
- Avoid collecting into a vector when processing bus interactions

Witgen: improve tracegen

---

openvm/src/powdr_extension/chip.rs
openvm/src/powdr_extension/executor.rs
openvm/src/powdr_extension/plonk/chip.rs

Continuing implementing the Plonk Chip, now only `generate_air_proof_input` is missing! Everything should be analogous to `PowdrChip`.

Implement more Plonk Chip functions

---

openvm/src/plonk/air_to_plonkish.rs

Current plonk compiler transfer an air expression to plonk gate, but it doesn't evaluate the expression. 
for example: 
`a * b * c = 0`
it will compile it to 
```
a * b = temp0
temp0 * c = temp1
```
This PR set the last gate output, which is the output of the expression (temp1 in the above example) to be zero

Make plonk expression evaluated to be zero

---

openvm/src/plonk/air_to_plonkish.rs

When q_o is zero, set temp to be Unused, to not break the plonk circuit witness generation [here](https://github.com/powdr-labs/powdr/blob/fd00f930bd58a09b53f128e0d77092e53f8b4750/openvm/src/powdr_extension/plonk/chip.rs#L232)

Set temp to be unused in zero assertion 

---

openvm/src/customize_exe.rs
openvm/src/lib.rs
openvm/src/powdr_extension/vm.rs

Building on #2787, this PR adds an option to compile a precompile into a PlonK circuit. It also adds tests, which are currently marked as `should_fail`, because we don't implement bus interactions yet and therefore have an imbalanced bus.
Example:
```
$ RUST_LOG=powdr_openvm::powdr_extension::plonk::chip=debug cargo test -r keccak_plonk_small_prove_mock -- --nocapture
...
Generating air proof input for PlonkChip PowdrAutoprecompile_0
Number of calls: 240
Plonk gates: 10124
Trace width: 8
Trace height: 4194304
...
LogUp multiset equality check failed.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test tests::keccak_plonk_small_prove_mock - should panic ... ok
```

Add Option to compile an APC to a PlonK circuit + tests

---

pilopt/src/inliner.rs

keep track of which constraints/expressions contain a given variable to avoid going through the whole constraint system

inliner indexing

---

openvm/Cargo.toml
openvm/src/customize_exe.rs

This came up in the Reth benchmarks. Without this our basic blocks collection fails to see these extension branch instructions. These don't come up in the ELF file because they're extensions.

add bigint branching opcodes as well

---

autoprecompiles/src/constraint_optimizer.rs
autoprecompiles/src/stats_logger.rs

Turns the variable in the constraint optimizer into a generic parameter. The goal of this is that we can later add auxiliary variables which are enum alternatives in an enum that also contains the original variable - without having to touch the optimizer code.

Abstract constraint optimizer.

---

autoprecompiles/src/memory_optimizer.rs

A follow-up on [this comment](https://github.com/powdr-labs/powdr/pull/2835#discussion_r2127540768): We don't need to assume that memory addresses must be divisible by 4, that is something that surrounding constraints have to enforce. The memory optimizer is sound if it assumes only key-value-store semantics.
I still left left that the address space must be known at compile time and left a sanity check that runs specifically on registers (and is not trivial to generalize, because assumes that addresses are known at compile time). In principle, we could generalize it further and consider `(address_space, address)` be the address type.

Simplify Memory Optimizer

---

openvm/src/lib.rs

To avoid importing constraint-solver in the reth benchmark repo

Reexport degree bound

---

openvm/src/bus_interaction_handler/memory.rs
openvm/src/lib.rs
openvm/tests/apc_builder.rs
openvm/tests/optimizer.rs

We can actually encode the `x0` semantics in the memory bus interaction handler.
Note that this still keeps a register access to `x0` that could be removed, but now at least we're not allocating  4 witness columns for the value *and* we might be able to derive more values at compile time.

Register 0 returns 0

---

autoprecompiles/src/legacy_expression.rs
autoprecompiles/src/lib.rs
autoprecompiles/src/powdr.rs
openvm/src/customize_exe.rs
openvm/src/lib.rs
openvm/src/plonk/mod.rs
openvm/src/utils.rs

We used to store the name in a string in `AlgebraicReference`. Now, it's an `Arc<String>`, so that if a column is mentioned many times, its name is only allocated once.

Use `Arc<String>` for reference name

---

autoprecompiles/src/bus_map.rs
openvm/src/utils.rs

This PR changes `BusMap: bus_ids: BTreeMap<u64, BusType>` to `BusMap: bus_ids: BTreeMap<u64, Option<BusType>>`, by doing this we can avoid adding CopyConstraintLookup into BusType enum when adding this new bus type by plonk chip, get_pil can behave correctly, see discussion [here](https://github.com/powdr-labs/powdr/pull/2871#discussion_r2149829356)

Make pil export work with unknown bus ids

---

cli-openvm/src/main.rs
openvm/src/customize_exe.rs
openvm/src/extraction_utils.rs
openvm/src/lib.rs
openvm/src/powdr_extension/chip.rs
openvm/src/powdr_extension/executor/periphery.rs
openvm/src/powdr_extension/plonk/chip.rs
openvm/src/powdr_extension/vm.rs
openvm/tests/apc_builder.rs

Some refactoring:
- avoid collecting a large string in `export_pil`, add basic test
- introduce `OriginalVmConfig` which wraps SdkVmConfig and serves airs, bus map, etc, with internal caching
- refactor to make the external API higher level. `compile_exe_with_elf` can be used directly by `openvm-reth-benchmark`, see https://github.com/powdr-labs/openvm-reth-benchmark/pull/7

Clean up API

---

openvm/src/customize_exe.rs

Currently Pgo::Cell creates APCs for all BBs, but immediately after the sorting the first `n_acc` BBs are created again regardless of PgoType.
This PR isolates the apc_caching for the first `n_acc` BBs as a separate API that's only invoked by Pgo::Instruction and Pgo::None.
As per my reth bench mark test `MODE="execute"  APC=1000 APC_SKIP=0 PGO_TYPE=cell /usr/bin/time -v ./run.sh` PLUS `panic!` immediately after compilation, this reduces maximum resident size (memory consumption) from 92 gigs to 72 gigs.

Cache fewer APC for Pgo::Cell

---

cli-openvm/src/main.rs
openvm/src/lib.rs

The OVM CLI `Pgo` command and `powdr_ovm::pgo` function mostly collects the execution frequency of each PC in the original program, and therefore has become a misnomer now that the concept of PGO is mostly implemented in `customize_exe.rs`.
This PR removes the `Pgo` command and also inlines `powdr_ovm::pgo` function to `get_pc_idx_count`, which should be the correct name for the intended purpose.

Deprecate OVM CLI PGO

---

cli-openvm/src/main.rs
openvm/src/lib.rs

We need the `CompiledProgram` entry point because in the reth benchmark we already have the elf binary

restore pgo API

---

openvm/src/customize_exe.rs
openvm/src/extraction_utils.rs
openvm/src/lib.rs

Pgo input is now "max total columns" instead of "max apc columns", because there can be many non APC columns. To be exact, roughly ~580 for RV32 chip set and ~15K in the set used in `reth-benchmark`. Tested and works for Keccak. 
This PR calculates the total non APC columns number, logs them by chip in case we interested in what airs they belong to, and then subtract the non APC total from the max total the user supplies to PGO to obtain the max APC columns, which is then used in the KnapSack algorithm to limit APC generation in Pgo::Cell mode.
This PR's method is a bit of simplification, we are not sure if all chips in the original config's chip inventory get eventually proven. There are three scenarios (in order of ascending restrictiveness): 
1. All columns in original inventory stay …

[PR for Review] Detect and count non-Powdr columns for cell PGO max column use

---

Cargo.toml

fixes metric collection for PowdrAir
depends on: https://github.com/powdr-labs/openvm/pull/31

bump openvm and stark-backend

---

cli-openvm/src/main.rs

Adding CLI option as a utility and also an example for reth-benchmark, which currently can't parse `Cell(Option<usize>)` and only defaults to `Cell(None)`.

PGO max column CLI

---

autoprecompiles/src/bitwise_lookup_optimizer.rs
autoprecompiles/src/constraint_optimizer.rs
autoprecompiles/src/expression_conversion.rs
autoprecompiles/src/memory_optimizer.rs
autoprecompiles/src/optimizer.rs
constraint-solver/src/boolean_extractor.rs
constraint-solver/src/constraint_system.rs
constraint-solver/src/grouped_expression.rs
constraint-solver/src/indexed_constraint_system.rs
constraint-solver/src/inliner.rs
constraint-solver/src/journaling_constraint_system.rs
constraint-solver/src/lib.rs
constraint-solver/src/solver.rs
constraint-solver/src/solver/bus_interaction_variable_wrapper.rs
constraint-solver/src/solver/exhaustive_search.rs
constraint-solver/src/solver/quadratic_equivalences.rs
constraint-solver/src/test_utils.rs
constraint-solver/src/utils.rs
constraint-solver/tests/solver.rs
executor/src/witgen/jit/block_machine_processor.rs
executor/src/witgen/jit/identity_queue.rs
executor/src/witgen/jit/processor.rs
executor/src/witgen/jit/single_step_processor.rs
executor/src/witgen/jit/witgen_inference.rs
pilopt/src/qse_opt.rs

Renames QuadraticSymbolicExpression to GroupedExpression. The advantage of doing it his way is also that we can slowly change what is called `QuadraticSymbolicExpression` afer this PR, namely the one with SymbolicExpression as RuntimeConstant to GroupedExpression and easily see which on is generic already and which is not.

Rename quadratic symbolic expression.

---

autoprecompiles/src/lib.rs
autoprecompiles/src/powdr.rs
openvm/src/customize_exe.rs
openvm/src/extraction_utils.rs
openvm/src/lib.rs
openvm/src/powdr_extension/chip.rs
openvm/src/powdr_extension/plonk/chip.rs
openvm/tests/optimizer.rs

When looking at metrics to rank apcs, we currently only take into account main columns (excluding second stage columns)
Fix that.

Use all columns in pgo

---

autoprecompiles/src/basic_blocks.rs
autoprecompiles/src/lib.rs
openvm/src/customize_exe.rs
openvm/src/extraction_utils.rs
openvm/src/instruction_formatter.rs
openvm/tests/apc_builder.rs

Moving block detection to the APC crate. 
After this PR, a larger chunk of the `customize` function is openvm-agnostic.

Move block detection to APC crate

---

autoprecompiles/src/lib.rs
autoprecompiles/src/symbolic_machine_generator.rs
openvm/src/extraction_utils.rs
openvm/src/powdr_extension/executor/mod.rs
openvm/src/powdr_extension/vm.rs

This way, the selected AIR can depend on the entire instruction, not just the opcode.

Generalize `InstructionMachineHandler`

---

autoprecompiles/src/bitwise_lookup_optimizer.rs
autoprecompiles/src/lib.rs
autoprecompiles/src/symbolic_machine_generator.rs
openvm/src/customize_exe.rs

`SymbolicInstructionStatement` is only used to constraint the pc lookup.
Reuse the same type for the pc bus lookup and the instruction.

Simplify `SymbolicInstructionStatement` treatment

---

autoprecompiles/src/adapter.rs
autoprecompiles/src/blocks/detection.rs
autoprecompiles/src/blocks/mod.rs
autoprecompiles/src/blocks/pgo.rs
autoprecompiles/src/lib.rs
autoprecompiles/src/symbolic_machine_generator.rs
openvm/src/customize_exe.rs
openvm/src/extraction_utils.rs
openvm/src/opcode.rs
openvm/src/powdr_extension/executor/mod.rs
openvm/tests/apc_builder.rs

This PR does two things:
- it partially removes the notion of opcode in the autoprecompile crate, and instead relies on user provided functions to know if an instruction is allowed/branching
- it uses VmOpcode as much as possible in the openvm crate instead of usize
After this PR, the only remaining notion of opcode in the apc crate is in the `SymbolicInstructionStatement` where it is still a single field element. @georgwiese shared ideas to remove that too, or at least shift it to the client, see #3055

Partially remove opcode concept from apc crate, use `VmOpcode` in openvm crate

---

autoprecompiles/src/lib.rs
openvm/tests/apc_builder_outputs/guest_top_block.txt
openvm/tests/apc_builder_outputs/single_add_0.txt
openvm/tests/apc_builder_outputs/single_and_0.txt
openvm/tests/apc_builder_outputs/single_beq.txt
openvm/tests/apc_builder_outputs/single_bge.txt
openvm/tests/apc_builder_outputs/single_bgeu.txt
openvm/tests/apc_builder_outputs/single_blt.txt
openvm/tests/apc_builder_outputs/single_bltu.txt
openvm/tests/apc_builder_outputs/single_bne.txt
openvm/tests/apc_builder_outputs/single_loadb.txt
openvm/tests/apc_builder_outputs/single_loadbu.txt
openvm/tests/apc_builder_outputs/single_loadh.txt
openvm/tests/apc_builder_outputs/single_loadhu.txt
openvm/tests/apc_builder_outputs/single_loadw.txt
openvm/tests/apc_builder_outputs/single_sll.txt
openvm/tests/apc_builder_outputs/single_sll_by_8.txt
openvm/tests/apc_builder_outputs/single_sra.txt
openvm/tests/apc_builder_outputs/single_srl.txt
openvm/tests/apc_builder_outputs/single_storeb.txt
openvm/tests/apc_builder_outputs/single_storeh.txt
openvm/tests/apc_builder_outputs/single_storew.txt
openvm/tests/apc_builder_outputs/single_sub.txt
openvm/tests/apc_builder_outputs/single_xor.txt

In order to get a feel for the optimizer, I think it is good to also output the column count. It is rather difficult to get the column count before optimization, but in the end we are only interested in the effect of a new optimization step anyway, so I think this is fine.

Store column count.

---

autoprecompiles/src/bitwise_lookup_optimizer.rs
autoprecompiles/src/constraint_optimizer.rs
autoprecompiles/src/memory_optimizer.rs
autoprecompiles/src/optimizer.rs
constraint-solver/src/grouped_expression.rs
constraint-solver/src/solver.rs
openvm/src/lib.rs
openvm/tests/apc_builder_outputs/guest_top_block.txt
openvm/tests/apc_builder_outputs/memcpy_block.txt

Turns `Solver` into a trait to abstract away the bus interaction handler and also allow other implementations in the future.
It also makes the solver persistent across optimization loops so that we do not have to derive the same range constraints all over again.
This is also a preparatory PR to make the solver more independent from the constraint system: The constraint system inside the solver will have way more redundancies in the future.

Turn solver into trait.

---

constraint-solver/src/indexed_constraint_system.rs
constraint-solver/src/solver.rs

This way, we guarantee that there are no duplicates, which can cause performance issues.
Although, it seems like on the OpenVM Keccak test case (#3104), there are not many duplicates and performance decreases slightly:
```
$ cargo bench --bench optimizer_benchmark
Benchmarking optimize-keccak/optimize: Warming up for 3.0000 s
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 45.8s.
optimize-keccak/optimize
time:   [4.5420 s 4.5712 s 4.6035 s]
change: [+3.5320% +4.2324% +5.0959%] (p = 0.00 < 0.05)
Performance has regressed.
```

Variable Occurrences: Use BTreeSet

---

openvm/Cargo.toml
openvm/benches/optimizer_benchmark.rs

```
$ cd openvm
$ cargo bench --bench optimizer_benchmark
Benchmarking optimize-keccak/optimize: Warming up for 3.0000 s
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 44.2s.
optimize-keccak/optimize
time:   [4.3703 s 4.3856 s 4.4020 s]
change: [-1.2781% -0.5240% +0.2094%] (p = 0.21 > 0.05)
No change in performance detected.
```

Add `optimize()` benchmark

---

autoprecompiles/src/optimizer.rs

Bus interaction variables were introduced in order to be able to derive knowledge about complex expressions used in bus interactions. The system is quite good in handling affine expressions, though, so in order to keep the number of variables (and constraints) down, we only replace non-affine expressions in bus interactions.

Only transform non-affine bus interactions.

---

autoprecompiles/src/constraint_optimizer.rs
constraint-solver/src/grouped_expression.rs
constraint-solver/src/indexed_constraint_system.rs

This PR adds a new optimizer step:
https://github.com/powdr-labs/powdr/blob/5568270f775c5abb36dbe23fb1738b0438c24c88/autoprecompiles/src/constraint_optimizer.rs#L96-L108
This can be useful to remove "left-over" range constraints, e.g. from removed memory bus interactions:
- Imagine a memory bus interaction receiving a previous time stamp and then having a range constraint like `[current_timestamp - prev_timestamp - 1] in [BIT16]` to enforce that it is smaller than the current timestamp.
- Then, `prev_timestamp` would only be mentioned in this stateless bus interaction after the memory bus interaction is removed by the memory optimizer.
- The `remove_disconnected_columns` step would not remove it, because `current_timestamp` is also mentioned and it is connected to a stateful bus …

Remove free variables

---

autoprecompiles/src/evaluation.rs
autoprecompiles/src/lib.rs
openvm/src/extraction_utils.rs
openvm/src/lib.rs

As @qwang98 pointed out, my implementation of `evaluate_apc` was too inefficient, because it recalculated the statistics for the original AIRs for each instruction of the basic block. This PR fixes it by requiring a new function `InstructionHandler::get_instruction_air_stats`.

Improve `evaluate_apc`

---

autoprecompiles/Cargo.toml
autoprecompiles/src/blocks/mod.rs
autoprecompiles/src/blocks/pgo.rs
autoprecompiles/src/lib.rs
cli-openvm/Cargo.toml
cli-openvm/src/main.rs
openvm/src/lib.rs

Generalize so that we can use `PgoType` and adjacent CLI functions in more use cases in a generic way.

Generalize CLI structs

---

riscv-elf/Cargo.toml
riscv-elf/src/rv64.rs

This print seems pretty noisy.

Use `tracing` crate in `riscv-elf`

---

openvm/extensions/hints-circuit/src/executors.rs
openvm/extensions/hints-guest/src/lib.rs

When the input is non-square, the prover returns the square root of the input times a predefined non-quadratic residue.
The idea is that the guest should also prove the non-square case, so it must check that:
`result * result == input * PREDEFINED_NON_QR`.
Chose `3` as the predefined non_qr.

fix k256 sqrt hint

---

openvm/benches/optimizer_benchmark.rs
openvm/src/bus_interaction_handler/bitwise_lookup.rs
openvm/src/bus_interaction_handler/memory.rs
openvm/src/bus_interaction_handler/mod.rs
openvm/src/bus_interaction_handler/tuple_range_checker.rs
openvm/src/bus_interaction_handler/variable_range_checker.rs
openvm/src/customize_exe.rs
openvm/tests/apc_builder.rs
openvm/tests/optimizer.rs

We used the default tuple range checker sizes, but it should be read from the config. For example, in the reth benchmarks, the sizes are actually different, leading to potential soundness or completeness bugs.

Read tuple range checker sizes from config

---

autoprecompiles/src/blocks/pgo.rs
openvm/src/customize_exe.rs
openvm/src/extraction_utils.rs
openvm/src/lib.rs
openvm/tests/apc_builder.rs
openvm/tests/apc_builder_outputs/beqz.txt
openvm/tests/apc_builder_outputs/bnez.txt
openvm/tests/apc_builder_outputs/single_beq.txt
openvm/tests/apc_builder_outputs/single_bne.txt
openvm/tests/apc_builder_outputs/single_loadbu.txt
openvm/tests/apc_builder_outputs/single_storeb.txt
openvm/tests/apc_builder_outputs/single_storeh.txt

We used 5 for OpenVM's default constraint max degree bound for a long time since that's what was in their SDK example, but they actually use and suggest app log blowup = 1 for app proofs, which leads to max_degree = 3. This PR changes the default to 3.
The basic PR is quite simple, see the first commit. A lot of the `max_degree` propagation in the second commit is because of the `get_air_metrics` function that needs it to call an OpenVM internal function, and the max degree is not available in any existing data structure at that point.
I thought the easiest was just to add it to these functions, and I had to change one trait. But that felt easier/less invasive than changing associated types/constants of other traits. @Schaeff let me know if this is fine or if you prefer another route.

Fix default degree bound

---

openvm/extensions/hints-guest/src/lib.rs

In the `hint_k256_inverse_field_10x26` and `hint_k256_sqrt_field_10x26` functions, this PR ensures that the returned result actually consists of 26 bits limbs, as the name suggests. (Except for the most significant limb, which is 22 bits.) This means that the field element is weakly normalized and can be used safely by the guest program.

Ensure weakly normalized

---

autoprecompiles/src/range_constraint_optimizer.rs

Reverts #3169 
It seems to have caused a performance regression with the optimization for SHA taking 40min in CI (previously < 10).
I checked locally and it is indeed the range constraint optimizer. On my system, it takes > 5min to optimize 7328 range constraints, which happens a few times during the test.

Revert "Remove (some) redundant range constraints (#3169)"

---

.github/workflows/nightly-tests.yml

The `illegal instruction` error is back on nightly, see here: https://github.com/powdr-labs/powdr/actions/runs/16954946528/job/48054989302
We suspect it could because `test_apc` uses the same cache as the normal tests, but that cache has its build done in a different machine so the dependencies could have instructions that cannot run on the server. If this is the case, it happens most likely from the C/C++ dependency.
Anyway, we don't know that for sure, but this PR seems to fix it, see here https://github.com/powdr-labs/powdr/actions/runs/16944315837/job/48021334148.

Use a different cache for test_apc

---

pipeline/build.rs
pipeline/tests/powdr_std.rs

Hot fix to reduce the 1h+ test time of `reparse:: keccakf32_memory_test` of #3140

Ignore Keccak reparse test

---

.github/workflows/nightly-tests.yml
openvm/scripts/run_guest_benches.sh

I wanted to refactor the `run_guest_benches.sh` to make it a bit more flexible. With this, it should be possible to test the ECC guest easily (#3118), which actually has 3 guests (manual, out-of-the-box software, hint-optimized software).
I also brought the matmul test back.
The file structure is not exactly the same as before, but similar (and more organized):
https://github.com/powdr-labs/bench-results/tree/gh-pages/results/2025-08-20-1538
(which is from this run: https://github.com/powdr-labs/powdr/actions/runs/17099625118/job/48492387082)

Refactor `run_guest_benches.sh`

---

autoprecompiles/src/constraint_optimizer.rs
constraint-solver/src/grouped_expression.rs

This new optimizer step removes duplicate factors in a single algebraic constraint.
It was detected by the assertion that is now commented, which assumed that if all factors of one constraint also appear in another constraint then the number of factors is also less or equal the number of factors in the other constraint.
By running the duplicate factor removal right before that other step this assumption gets true.

Remove duplicate factors.

---

autoprecompiles/src/pgo/cell/mod.rs
openvm/src/customize_exe.rs

We used to export instruction in their JSON format, e.g. `{"opcode":512,"a":1879048082,"b":1879048082,"c":2013265793,"d":268435454,"e":268435454,"f":0,"g":0}`.
I changed this to be the pretty-printed string instead. I think this makes more sense, because we don't reading them like this is hard and we don't want to re-implement the pretty-printing in Python.
I checked that currently our Python scripts don't really read this value, they only use the length of the list, so this PR doesn't break them. In the future, I'm hoping to get Claude to generate an interactive version of the effectiveness plot, so that we can also explore the source code of each block.

Candidate JSON: Pretty-print instructions

---

autoprecompiles/src/blocks/mod.rs
openvm/src/customize_exe.rs

It is much more convenient for debugging to have a `Display` available, especially when debugging the generic code.

Display for Block.

---

openvm/guest-ecc-powdr-affine-hint/Cargo.toml
openvm/scripts/run_guest_benches.sh

k256 is updated with the newer openvm-guest-hint and we can test ecc with larger input 50

k256 updated, ecc tests with larger input

---

autoprecompiles/src/constraint_optimizer.rs

This optimizer function call is now called inside `remove_redundant_constraints` because that depends on it to work correctly.

Fix invalid conflict resolution.

---

openvm/src/powdr_extension/executor/mod.rs

The code removed here is an execution optimization to not have to perform more computation than needed. However it relies on some assumptions on the optimizer that don't always hold, therefore it's safer to remove it.
This fixes some benchmarks that were broken on nightly.

remove witgen opt

---

autoprecompiles/src/constraint_optimizer.rs

As a real-life example, consider this constraint:
```
(opcode_loadb_flag0_1 + opcode_loadb_flag1_1) *
(
from_state__timestamp_0
- rs1_aux_cols__base__prev_timestamp_1
- rs1_aux_cols__base__timestamp_lt_aux__lower_decomp__0_1
- 131072 * rs1_aux_cols__base__timestamp_lt_aux__lower_decomp__1_1
- + 2
) = 0
```
And assume that `rs1_aux_cols__base__prev_timestamp_1` does not appear in other constraints, i.e., is a free variable.
Then this constraint is redundant: For any assignment of the other variables, the prover can always solve for the value of `rs1_aux_cols__base__prev_timestamp_1` that makes the second factor evaluate to 0.
The previous implementation would not catch that: It would just call `constraint.try_solve_for(free_variable).is_some()`, which would return `false`, see the …

Improve free variable detection

---

.github/workflows/nightly-tests.yml

somehow they run out of memory if run as part of the full suite

run larger tests by themselves

---

openvm/src/powdr_extension/executor/mod.rs

This will be a series of PRs that reduces trace gen code duplication in multiple powdr APC clients, planned as the follows:
1. [This PR] Simplify OVM client trace gen code using existing optimization in other client, also unifying data types for later PR.
2. [Next PR] Create `TraceHandler` trait for implementation in different powdr APC clients, with trait functions mostly generating unified data types across different clients. Add `TraceHandler` as an associated type in `Adapter`.
3. [Another PR] Potentially cache `TraceHandler` outputs in the executor for clients that run execution multiple times (so that we don't recompute in `generate_trace` each time).
4. [Another PR] Further clean up including potentially revive things like `is_valid_index`.

Simplify trace gen

---

openvm/src/extraction_utils.rs
openvm/src/powdr_extension/executor/mod.rs

Currenlty we obtain air name via two methods: `executor.air().name()`, and `executor.air_name()` and they apparently return different results.
Needed for #3251, so that we can use `Adapter::InstructionHandler` to get air names of dummy instructions in witgen.

Unify air names

---

openvm/src/powdr_extension/chip.rs
openvm/src/powdr_extension/executor/mod.rs

The `RangeCheckerSend` struct in OVM are based on `SymbolicExpression` by first converting from `AlgebraicExpression`. These `RangeCheckerSend` are then evaluated via the (Symbolic)`RowEvaluator`.
However, we don't need the conversion back and forth between `Symbolic` and `Algebraic` and can directly use the (Algebraic)`RowEvaluator`. I think this conversion is likely due to legacy code so we can remove them.

Remove symbolic row evalutor

---

autoprecompiles/src/expression.rs
openvm/src/powdr_extension/chip.rs
openvm/src/powdr_extension/executor/mod.rs

In OVM witgen, we currenlty have (Symbolic)RowEvaluator, which is used to remove range check side effects (as they are SymbolicExpression based). We also use it to replay APC bus interactions, which are first converted from AlgebraicExpression to SymbolicExpression. However, this step is unnecessary, as this PR creates an (Algebraic)RowEvaluator which we can use to evaluate APC bus interaction replay. This new row evaluator is in the APC crate and can be used across different clients.

Algebraic `RowEvaluator`

---

.github/workflows/nightly-tests.yml
openvm/guest-u256-manual-precompile/src/main.rs
openvm/guest-u256/src/main.rs
openvm/scripts/run_guest_benches.sh
openvm/src/lib.rs

Changes:
- For Keccak and Matmul, we only ran the benchmark with 0 and 100 APCs. I changed it to run with 0, 3, 10, 30. I think more does not make sense, because the effectiveness plots ([matmul](https://github.com/powdr-labs/bench-results/blob/gh-pages/results/2025-09-15-0630/matmul/100apc/effectiveness.png), [keccak](https://github.com/powdr-labs/bench-results/blob/gh-pages/results/2025-09-15-0630/keccak/100apc/effectiveness.png)) do not suggest that there are more basic blocks worth accelerating.
- For reth, I also added more steps.
- Named experiments more consistently (`apc000`, `apc003`, ...)
- Added existing benchmarks for SHA, Pairing, and U256
- Increased the size of the U256 benchmark to get more meaningful results
Manual nightly run: …

Nightly: Run more benchmarks

---

openvm/src/powdr_extension/executor/inventory.rs
openvm/src/powdr_extension/executor/mod.rs
openvm/src/powdr_extension/executor/periphery.rs
openvm/src/powdr_extension/vm.rs

Fixed the bug below via solution 1 below.
Currently fails `keccak_prove_simple` with a compile time error during during `GenericSdk::new(app_config).unwrap();` in Powdr and `PowdrExecutor::new` in OVM and eventually panics with `AirNotFound` when calling `next_air` in `create_chip_complex` which creates dummy chip complex with the dummy periphery. On the high level, dummy periphery will help with witgen in isolating side effects for some chips, but it should only affect bus witgen, so I think we can still continue with regular trace witgen.
```
thread 'tests::keccak_prove_simple' panicked at openvm/src/powdr_extension/executor/mod.rs:86:18:
Failed to create chip complex: AirNotFound { name: "openvm_circuit::arch::integration_api::VmAirWrapper<openvm_rv32im_circuit::adapters::alu::Rv32BaseA …
```

[Ovm 1.4] memory and dummy periphery

---

Cargo.toml
autoprecompiles/src/adapter.rs
autoprecompiles/src/pgo/none.rs
openvm/src/customize_exe.rs
openvm/src/extraction_utils.rs
openvm/src/lib.rs
openvm/src/powdr_extension/executor/mod.rs
openvm/src/powdr_extension/plonk/chip.rs
openvm/src/powdr_extension/trace_generator/mod.rs
openvm/src/powdr_extension/vm.rs

Bugs fixed:
1. `guest_prove_simple`: the selected APC isn't executed at all, and therefore `OriginalArenas` remain `Uninitialized`, which causes a panic when we try to access `number_of_calls` in `generate_witness`. We should still allow cases where an APC isn't executed (in `Pgo::None` mode only). Therefore, the fix is to have both `OriginalArenas::number_of_calls` and `OriginalArenas::number_of_calls_mut`, where the former returns `0` for `Uninitialized` and the latter panics. The former is used in `generate_witness` while the latter is used in `Preflight::execute`.
2. `guest_plonk_prove_mock`: `ChipInventory::next_air:<T>` call should specialize `T` on `PowdrAir` or `PlonkAir` depending on the implementation. Previously we only specialize on `PowdrAir` and therefore the test panics.
3. …

[OVM 1.4] fix test bugs
